### ISSUE TITLE
Performance observability

### ISSUE THREAD

**Issue by shah** [lumeland/lume#106]
As you start your TypeScript journey (or even before!) I suggest adding some _observability_ across all the major pipeline steps. For example, if I have 100 pages being generated but 5 of them take 95% of time to generate, we should be able to see that when the pages are being tracked. For large sites some parts of site take much longer to generate so the developer should be responsible for caching those pages but she'd need to be told which ones they are.

Something like this?

```bash
🔥 Deno prepare (900ms)
🔥 /images /images (copy: 25ms)
🔥 /index.html /index.tmpl.ts (load: 1025ms, render: 255ms, process: 190ms, etc: ??)
🔥 /styles.css /styles.css (??)

🍾 Site built into ./_site (1255ms)
```

It would be good to build [OpenTelemetry](https://opentelemetry.io/) and [OpenMetrics](https://openmetrics.io/) (Prometheus) into Lume so that large sites can fine tune performance through observability.

**Comment by oscarotero** [comment]
That's good idea. Deno has support for the performance web API, so it should be something easy to do.

**Comment by shah** [comment]
Also @oscarotero when there are thousands of pages, how does one turn off the generated file details list and show only a summary of pages generated? Is that in `_config.js`? I did not see a `--verbose` CLI option either.

**Comment by oscarotero** [comment]
@shah I've added performance metrics functionality to Lume. It's not released yet but you can test it installing the last commit with `lume upgrade --dev`.

Runnign `lume --metrics` will display some metrics from the build process. You can save them to a file for better inspection with `lume  --metrics=filename.json`.

And about the `--verbose` option, it's a good idea. I'll add it. 
Thanks!

**Comment by shah** [comment]
Great, thanks @oscarotero - I'd consider adding an `observability` property in `_config.ts` so that it can be controlled from CLI or config. Something like this:

```js
observability: {
    telemetry: { ...what to capture for traceability  },
    metrics: { ...all metrics options  },
}
```

**Comment by oscarotero** [comment]
In `_config.ts` you can simply set `metrics: true` to enable them and get it from the `site.metrics` property. For example, if you want to inspect them, just create a "afterBuild" event:

```js
const site = lume({ metrics: true });

site.addEventListener("afterBuild", () => {
    // Get all metrics:
    const entries = site.metrics.entries;
});
```

**Comment by oscarotero** [comment]
I just added a `--verbose` option. [More info](https://github.com/lumeland/lume/blob/master/CHANGELOG.md)

**Comment by shah** [comment]
@oscarotero here's what I see with `--metrics` please LMK if I'm doing something incorrectly?

![image](https://user-images.githubusercontent.com/47497/122679509-267fd980-d1b9-11eb-8a87-7a0ce427082e.png)

**Comment by shah** [comment]
@oscarotero for the `config.ts` model I tried this:

```ts
import { lume, postCssPlugin, slugifyURLsPlugin } from "./deps.ts";

const site = lume.default({
  location: "https://lectio.netspective.com/",
  metrics: true,
});

site
  .copy("images")
  .use(postCssPlugin.default())
  .use(slugifyURLsPlugin.default({ alphanumeric: false }))
  .ignore(
    "README.md",
    "config.ts",
    "*.code-workspace",
    "Justfile",
    ".env",
    ".env.example",
  );

site.addEventListener("afterBuild", () => {
  // Get all metrics:
  // const entries = site.metrics.entries;
});

export default site;
```

This results in:

![image](https://user-images.githubusercontent.com/47497/122679714-eff68e80-d1b9-11eb-9296-fd9ef9bbd10f.png)

**Comment by oscarotero** [comment]
I think it's something related with Deno's cache. Try to remove the cache folder. I had the same problem and after remove the cache it works fine.

**Comment by oscarotero** [comment]
btw, `ignore` doesn't support patterns like `*.code-workspace`. Just real files or directories.

**Comment by oscarotero** [comment]
mmm, no it's not the cache. I have to investigate more

**Comment by shah** [comment]
Yep, it's not the cache, same output after clearing caches.
I'll add a ticket to add support globs or `*.code-workspace` style for ignore.

**Comment by oscarotero** [comment]
there's already a ticket (https://github.com/lumeland/lume/issues/53) but it's not easy to support for performance reasons.

**Comment by shah** [comment]
Also, while you're checking the `--verbose=0` or `--verbose=1` or `--verbose=2` did not seem to change any behavior.

**Comment by oscarotero** [comment]
I think there's a problem detecting these new options (metrics and verbose) in --dev installation.

**Comment by shah** [comment]
Got it, no worries - you can put it in with the next release. Thanks!

**Comment by oscarotero** [comment]
I know what's happens. You have to import the same lume module defined in the import_map. I mean, this works:

```js
import lume from "lume/mod.js";
```

But this doesn't work:

```js
import lume from "./my-lume-fork/mod.js";
```

Because the `mod.js` module is not the same as the uses by cli, so options passed by cli aren't applied.

**Comment by shah** [comment]
Got it! I try not to use import maps since they're less portable, I usually stick with `deps.ts`.
Here's my `deps.ts`:

```ts
export * as lume from "https://deno.land/x/lume@v0.23.2/mod.js";
export * as slugifyURLsPlugin from "https://deno.land/x/lume@v0.23.2/plugins/slugify_urls.js";
export * as postCssPlugin from "https://deno.land/x/lume@v0.23.2/plugins/postcss.js";
export * as dotenv from "https://deno.land/x/dotenv@v2.0.0/mod.ts";
export * as pg from "https://deno.land/x/postgres@v0.11.2/mod.ts";
```

To use `upgrade --dev` you're suggesting I use import map or are you suggesting I switch to import maps for production and dev?

**Comment by oscarotero** [comment]
Import maps are configured automatically by `lume upgrade` command. So they are always available, just need to change your deps.ts to use them.
Anyway, I'll try to change the way the cli arguments are applied to the final Lume instance for better portability.

**Comment by shah** [comment]
Confirmed - when I use this `deps.ts` the metrics are working:

```ts
export * as lume from "lume/mod.js";
export * as slugifyURLsPlugin from "lume/plugins/slugify_urls.js";
export * as postCssPlugin from "lume/plugins/postcss.js";
export * as dotenv from "https://deno.land/x/dotenv@v2.0.0/mod.ts";
export * as pg from "https://deno.land/x/postgres@v0.11.2/mod.ts";
export * as gitBeaker from "https://cdn.skypack.dev/@gitbeaker/core";
```

The minor issues that the compiler fails in VS Code (and shows syntax errors) without special import map setup so if we can stick with direct URLs that would be ideal.

**Comment by oscarotero** [comment]
Ok, but note that on importing the dependencies statically, `lume upgrade [--dev]` won't work because you are stuck to a fixed version of lume.

**Comment by shah** [comment]
Agreed, I use `udd` to update Deno dependencies and I'll have to be careful about that and switch to import map manually. Having something special for `upgrade --dev` makes sense as long import maps aren't required for non-devl versions.

**Comment by shah** [comment]
Overall the metrics look good now but we should create the output in more useful formats, starting in OpenMetrics (which very close to Prometheus exposition format or PEF). By emitting in both JSON and OpenMetrics/PEF we'll be able to use proper metrics ingestion systems for alerting. When you're ready to implement, [this is a good Deno library](https://github.com/base698/promts) as is [this one](https://github.com/marcopacini/ts_prometheus) to use. If we need ability to track Deno metrics we can also check out [this library](https://deno.land/x/observability).

**Comment by oscarotero** [comment]
Ok, but I don't want to include dependencies or big developments for this in de Lume core. I prefer have a simple solution that can be extended with plugins. The print and save actions are here: https://github.com/lumeland/lume/blob/master/metrics.js#L39 so it would be easy to create a plugin that can configure or replace this default solution with something more powerful or adapted to specific needs. A plugin example could be:

```js
import Metrics from "lume/metrics.js";

class MyCustomMetrics extends Metrics {
  print() {
    // Custom print
  }
  async save(file) {
    // Custom save
  }
}

export default function () {
  return (site) => site.metrics = new MyCustomMetrics();
}
```

**Comment by shah** [comment]
Great point @oscarotero and I _completely_ agree that everything should be a plugin whenever possible. _Collecting_ the metrics and providing observability _capabilities_ (e.g. traceability) should be in the core. I love the idea of _exporting_ the observability to different formats/file with events in `config.ts` or plugins.
