### ISSUE TITLE
Understanding most errors is hard because of printError()

### ISSUE THREAD

**Issue by fserb** [lumeland/lume#116]
I think Lume is used by people who are somewhat familiar with Deno (at least you need to be familiar enough to create a config file and most documentation assumes one can code a bit of Javascript).

That said, I think hiding the exception stack by default is a bad idea.

When I have a problem in my config, most of the time there's no good info on `printDataError`, and I end up getting something like:

```
Error: Cannot read property 'toLowerCase' of undefined

Task completed in 0m1.283s
```

This is unexpected and not really useful since most of the time the error message (even if it had the accompanying src page file that caused it) will still not uniquely identify where the error is coming from. 

I think it's a fair effort to try to associate a particular error to a source page file (that `printDataError` does) and I think Lume should definitely keep doing this and I'll try to track why I'm not getting it on those cases: I'm not sure if it's data files or preprocessors, or a Markdown/Nunjuck plugin. This reinforces my point! I got an error and I have no clue where the error is even coming from. Did I mess up my config? Is the plugin I'm using broken? Did I forgot a field somewhere?

I know I'm able to set `{verbose: 2}`, but my point is a bit deeper than that. Deno errors are not made to be presented without the stack. They make almost as much sense as just writing "Error" and nothing else.

I think we should remove the `debug` option on `printError()` and always output the full exception. It's usually not that verbose (2 to 10 lines); even non "core" developers can understand what it is (and most people using Lume will be familiar with them); it makes the error messages meaningful; and it makes it easier for users to create issues when it comes to that.

The way it currently is, we are almost saying _"there's an error, I'll sometimes tell you what is the offending file, but in any case change something until it works"_.

**Comment by oscarotero** [comment]
Ok, get it.
Maybe for errors it doesn't make sense.
