### ISSUE TITLE
Is _data.* read multiple times or is it a singleton?

### ISSUE THREAD

**Issue by shah** [lumeland/lume#118]
I am using `_data.ts` to setup my common data across pages. One of my variables is _sourced_ from a PostgreSQL database so in `_data.ts` I connect to the database, read the content, and store in a variable that I then use across multiple pages. Everything is working well with respect to generating HTML.

What I noticed was that `_data.ts` seems to be sourced for each page (and is running my database connection for each page). Since the data is common to all pages, I assumed `_data.ts` would only be loaded once and then the variables are made available to all page templates but that does not seem to be the case.

So I'm wondering is `_data.*` _meant_ to sourced once for _each page_ or once _per build_? For now I've solved my problem by creating a singleton in `_data.ts` but wanted to report this issue to see what you thought.

**Comment by oscarotero** [comment]
`_data` files/folders are loaded only once.

You can see here a real example: https://github.com/tarugoconf/tarugo21/blob/master/_data/eventbrite.js#L12
This file get data from the eventbrite API and export it with the name `metrics`.

Maybe you are exporting a function that is executed for each page instead the result?

**Comment by shah** [comment]
Ok great to know that, _by design_, `_data.ts` should only be loaded once. I'll try to figure out what I might have done to load it multiple times because for me (to get typesafety) I have to manually import `_data.ts` in my pages so it's possible I caused my own grief :-).
