### ISSUE TITLE
Outward Facing Types

### ISSUE THREAD

**Issue by shadowtime2000** [lumeland/lume#12]
Deno has builtin Typescript support so I was a little surprised to see this written in JS. I can understand not wanting to use Typescript, but I think this should have files like the plugins and the site written in typescript so people can use ts if they want it without writing there own types. We could then keep the internals of it written in JS. I could do this.

**Comment by shadowtime2000** [comment]
Alternatively we could do a `.d.ts` for every file that should be used externally, though that could be a little harder to maintain with new features and stuff.

**Comment by oscarotero** [comment]
I'm not a big fan of Typescript but understand that for some people it's useful. Is required to be lume in Typescript to create 3rd party stuff in Typescript?

All the public api is in the `site.js` file (it has all functions to configure, register plugins, loaders, template engines, etc).
Is the file `site.d.ts` enough? Or we need to create a `.d.ts` for every file?

Is possible to have the types as jsdocs?

**Comment by shadowtime2000** [comment]
@oscarotero 

> Is possible to have the types as jsdocs?

[Types as JSDocs is available in the Node Typescript version](https://www.typescriptlang.org/docs/handbook/type-checking-javascript-files.html) though I don't believe it works in Deno.

> All the public api is in the `site.js` file (it has all functions to configure, register plugins, loaders, template engines, etc).
Is the file `site.d.ts` enough? Or we need to create a `.d.ts` for every file?

A `site.d.ts` could work, but it would require you to put a comment like this above the import i believe
```js
//@deno-types="https://cdn.jsdelivr.com/github/lumeland/lume/site.d.ts"
```
Since all the plugins are closures, I am assuming that is so because later options and configuration support would be added to them. In that case there would need to be a `.d.ts` for every plugin file, and they would have to write (in my opinion an ugly) comment above the imports. So if a somewhat advanced static site used all builtin plugins (12 atm), they would have to write 12 of those comments above every plugin import, and another for the site import.

**Comment by oscarotero** [comment]
Ok, understood.
So there are two options to add typings: by creating a bunch of `.d.ts` files or rewriting the whole library to Typescript.
At this moment, I don't want to do any of them. `.d.ts` requires a lot of work and maintenance (and I agree that it's ugly). And rewrite all lume to Typescript requires work too. Note that this library uses some dependencies converted directly from jsdelivr, jspm and esm.sh. I think Typescript can introduce more complexity and I'd like to keep things simple.

Maybe, in a future `1.0` version, when all dependencies are loaded from deno.land, a Typescript version makes more sense.

**Comment by shadowtime2000** [comment]
@oscarotero Or we could convert the `site.js` and the plugins to `.ts` and put in an `any` or an `unknown` for internal stuff.

**Comment by oscarotero** [comment]
Related #104

**Comment by oscarotero** [comment]
Ok, finally lume [0.25.0](https://github.com/lumeland/lume/releases/tag/v0.25.0) is fully written in Typescript.
So I can close this.
