### ISSUE TITLE
Using `site.dest()` to set metrics destination throws exception

### ISSUE THREAD

**Issue by shah** [lumeland/lume#124]
@oscarotero per our conversation on Discord, I'm trying to set the destination of the metrics file to the site's output directory in my `_config.ts` using your suggestion:

`site.options.metrics = site.dest(".observability-metrics.json");` 

Doing a build with that line in `_config.ts` results in:

```javascript
in _config.ts shows this error:
error: Uncaught (in promise) NotFound: No such file or directory (os error 2)
  async save(file: string) {
                         ^
    at deno:core/core.js:86:46
    at unwrapOpResult (deno:core/core.js:106:13)
    at async open (deno:runtime/js/40_files.js:46:17)
    at async writeFile (deno:runtime/js/40_write_file.js:58:18)
    at async Metrics.save (https://deno.land/x/lume@v0.25.1/metrics.ts:80:26)
    at async printMetrics (https://deno.land/x/lume@v0.25.1/cli/build.ts:50:33)
```

When I used the following, it works fine:

`site = lume({metrics: "_site/.observability-metrics.json"})`

It looks like a timing issue when using `site.dest(...)` (perhaps because dest isn't created?). I like my metrics to go to the destination folder because it's useful for CI/CD and my site has a `/health` directory.

**Comment by oscarotero** [comment]
The problem is `site.dest()` returns the full path to this file, but `site.options.metrics` expects a path relative to cwd.
The solution is use the `site.options.dest` value:

```js
site.options.metrics = join(site.options.dest, ".observability-metrics.json");
```

**Comment by shah** [comment]
That worked, thanks!

Another quick request: if `--quiet` is requested, `⏲ Metrics data saved in ...` message should probably be suppressed.

**Comment by oscarotero** [comment]
Ok, done in `master`. I'll release `v0.25.2` in a couple with this changes and other possible bugfixes.
