### ISSUE TITLE
v0.25.4 error: unable to parse import map JSON

### ISSUE THREAD

**Issue by bradeneast** [lumeland/lume#131]
After upgrading to v0.25.4, I'm getting an error when running any lume command (see video).
There doesn't seem to be anything in the changelog that would have caused this.

https://user-images.githubusercontent.com/43307367/126526623-a1b8fd27-917a-42ec-8020-406fec724674.mp4

**Comment by oscarotero** [comment]
mmm, that's weird. We have made some changes here (basically removed the base64 encode to the url). Let me check in windows.

**Comment by oscarotero** [comment]
Ok, I just released v0.25.5. Seems like in Windows the import map argument is not properly escaped by deno.
I'm closing this. Feel free to reopen if it's not fixed.

**Comment by kuspoes** [comment]
I tried to upgrade lume to 0.25.5 but got this error: 

```bash
$ deno upgraded && lume upgrade
....
Download https://deno.land/x/lume@v0.25.5/import_map.json
error: Unable to load 'https://deno.land/x/lume@v0.25.5/import_map.json' import map

Caused by:
    Import 'https://deno.land/x/lume@v0.25.5/import_map.json' failed: 404 Not Found

Update successful! You’re using the latest version of lume: v0.25.5!
See the changes in https://github.com/lumeland/lume/blob/v0.25.5/CHANGELOG.md

$ lume --version
🔥lume v0.20.2

$ lume -s
Download https://deno.land/x/lume@v0.20.2/plugins/code_highlight.ts
Download https://deno.land/x/lume@v0.20.2/plugins/date.ts
Download https://deno.land/x/lume@v0.20.2/plugins/markdown.ts
lume: Import 'https://deno.land/x/lume@v0.20.2/plugins/code_highlight.ts' failed: 404 Not Found
    at file:///home/kusaeni/project/deno/responsive/_config.js:2:0
TypeError: Import 'https://deno.land/x/lume@v0.20.2/plugins/code_highlight.ts' failed: 404 Not Found
    at file:///home/kusaeni/project/deno/responsive/_config.js:2:0
    at async buildSite (https://deno.land/x/lume@v0.20.2/cli/utils.js:19:19)
    at async Module.run (https://deno.land/x/lume@v0.20.2/cli/build.js:46:16)
    at async maybeRun (https://deno.land/x/lume@v0.20.2/cli.js:108:28)
    at async cli (https://deno.land/x/lume@v0.20.2/cli.js:116:5)
    at async https://deno.land/x/lume@v0.20.2/cli.js:55:5
```

Ubuntu 20.04.2 LTS - WSL

**Comment by oscarotero** [comment]
Hi @kuspoes.
Yes, It can happens on upgrade from some old versions.
Reinstall again (`deno run -A https://deno.land/x/lume/install.ts`) solve the problem.
Version 1.0.0 will be releases soon, and after that there won't be more backward breaking changes.
