### ISSUE TITLE
Lume (local) server always warns "Unable to detect your local IP address"

### ISSUE THREAD

**Issue by x80486** [lumeland/lume#138]
Every time I start the (local) server I'm getting this warning: `Unable to detect your local IP address`.

```shell
[x80486@uplink:~/lume-template]$ lume --serve
Loading config file /home/x80486/lume-template/_config.ts

🔥 /index.html /index.njk
🔥 /global.css /global.css

🍾 Site built into _site/
No such file or directory (os error 2)

  Server started at:
  http://localhost:3000/ (local)
Warning Unable to detect your local IP address
If you're on an Ubuntu machine, try installing net-tools with 'apt install net-tools'

200 http://localhost:3000/
```

I'm running Arch Linux, Deno `1.15.1`, and Lume `v1.1.1`:

```shell
[x80486@uplink:~/lume-template]$ uname -a 
Linux uplink 5.10.72-1-lts #1 SMP Sat, 09 Oct 2021 17:34:39 +0000 x86_64 GNU/Linux
[x80486@uplink:~/lume-template]$ deno --version 
deno 1.15.1 (release, x86_64-unknown-linux-gnu)
v8 9.5.172.19
typescript 4.4.2
[x80486@uplink:~/lume-template]$ lume --version 
v1.1.1
```

Is this something that could be solve changing something in Lume, or is it like that because of Deno? I would really like that warning to disappear, even though it doesn't do any harm 😆

**Comment by oscarotero** [comment]
This is because Lume uses [deno-local-ip](https://github.com/joakimunge/deno-local-ip) to detect the local-ip of the local server and this package depends on `net-tools` installed in your computer. I'm not familiarized with Arch Linux, so don't know if you can install it. Perhaps `pacman -S net-tools`??
