### ISSUE TITLE
Built-in assets compression

### ISSUE THREAD

**Issue by x80486** [lumeland/lume#141]
It would be great if `Lume` supports this "natively". I've read that we should be able to accomplish something similar by using _processors_, but I think HTML and CSS compression/minification could be offered out-of-the box, since it's far too common, and (I would assume) a high percentage of developers would take advantage of this pretty much by default.

**Comment by oscarotero** [comment]
The new incoming Lume version (1.5.0) will include the `parcel_css` plugin, to use [Parcel CSS](https://parceljs.org/blog/parcel-css/) minifier.
