### ISSUE TITLE
lume dosen't serve static files

### ISSUE THREAD

**Issue by silverscat-3** [lumeland/lume#144]
The local server that can be started with `lume --serve` is apparently not serving static files correctly and is not responding.

The built data appears to be normal.

**Comment by oscarotero** [comment]
what version of Deno / Lume do you have? (`deno -V`, `lume -V`).
Do you see any error?

**Comment by silverscat-3** [comment]
Sorry, I foget that!

```
$ deno -V
deno 1.16.0

$ lume -V
v1.2.1
```

Doesn't see any error.

**Comment by oscarotero** [comment]
I think it's a bug of Deno 1.16.
Upgrade to Deno 1.16.1 and let me know

**Comment by silverscat-3** [comment]
Ah, thank you! It's fixed! This was a bug in Deno 1.16.
