### ISSUE TITLE
Official Docker image

### ISSUE THREAD

**Issue by x80486** [lumeland/lume#148]
Lume should provide its own Docker image, based on the **tested and supported** Deno version.

Not sure if it only makes sense to have one with `lume@vX.Y.C/ci.ts` installed, and/or also another one with the (usual) Lume installation.

**Comment by oscarotero** [comment]
Hi, thanks for the suggestion.
I'm not a Docker expert. Do you like to work on that?

**Comment by x80486** [comment]
Sure, I can start all of that. Usually there is another repository for this, and I'm still not clear if two images or just one is needed, in the sense that I don't really get the differences between a usual Lume install, and the one done with the `ci.ts` file. My assumption is that a normal/usual Lume install, should serve al purposes.

**Comment by oscarotero** [comment]
Great, thanks!
I think one image is enough.

ci.ts is just a way to run lume without install it.
In this case, the image should have lume installed.

**Comment by x80486** [comment]
All right. If you create a `docker-lume` repository with a `README.md` and a `LICENSE` file, I will send pull requests to the same for this.

**Comment by oscarotero** [comment]
Nice!
I've create a repo https://github.com/lumeland/docker
and added to you as a collaborator, so you can push directly to the repo.

**Comment by x80486** [comment]
I pushed the initial work for this. The images are building and executing fine for the tests that I'm running. I will write a Deno (or Bash) script to update them at once whenever Lume releases a new artifact.

All that's left is to sign up for a Docker Hub account and publish them, probably that can be done using GitHub Actions also.

**Comment by oscarotero** [comment]
Ok, I just created the docker image here: https://hub.docker.com/r/oscarotero/lume
Can I get your Docker ID, so I can add you as a collaborator?

**Comment by x80486** [comment]
I've been reading about this, and it should be possible to [publish the image(s) directl](https://docs.github.com/en/actions/publishing-packages/publishing-docker-images/)y via GitHub Actions. There should be a way to authenticate with Docker Hub.

I don't currently have any Docker Hub username, I can create one, but I think it's not needed for this since it can be all automated. Let me know what are your thoughts?

**Comment by oscarotero** [comment]
Ok, I like it. If we can automatize it, much better. I'm going to close this issue and we can keep the conversation in the docker repository.
