### ISSUE TITLE
Feature request: a "verbose" mode when running CLI commands

### ISSUE THREAD

**Issue by johanbrook** [lumeland/lume#151]
Hi! Thanks for a great site generator! Solid work on docs and general quality of the tool 👏 

I'm in the process of moving from 11ty. I ran into this when running `lume`:

```
$ lume
ReferenceError: module is not defined
```

I'm sure that error stems from somewhere in my site, but it'd be good with some pointer (stacktrace or similar) to where I should start looking. I eventually figured this out (I had legacy `module.exports` in a `_data` JS file), but I guess I was lucky.

I'm running Lume v1.3.1.

Thanks!

**Comment by oscarotero** [comment]
Hi @johanbrook
Thanks for using Lume!

I'll take a look to these kinds of errors. They should be show with the stacktrace by default, without need to a `verbose`mode.

**Comment by johanbrook** [comment]
Errors look better now, no need for specific verbose mode. Thanks!
