### ISSUE TITLE
"includeFile" of the eta plugin is not working properly.

### ISSUE THREAD

**Issue by otowa23** [lumeland/lume#152]
If I use the eta plugin and use "includeFile", it does not expand properly and returns [object Promise].
I think it's a synchronous/asynchronous problem, but my skills are poor and I have no idea where to fix it.

**Comment by oscarotero** [comment]
Hi. Yes, it's an async function. You have to add the `await` keyword and it should work fine.
See this example: https://github.com/lumeland/lume/blob/master/tests/assets/eta/index.eta#L8

**Comment by otowa23** [comment]
I guess I just need to add await. I hadn't thought of that. Thank you.
