### ISSUE TITLE
Support React?

### ISSUE THREAD

**Issue by audrow** [lumeland/lume#153]
Hey, Lume looks great. Is there a good way to use React with Lume? If not, can a plugin be added to use React? Not being able to use React is the main reason that I'm looking at other options for making a static site. I understand if that's not in the design goals of Lume.

**Comment by oscarotero** [comment]
Hi, @audrow 
React is available but not enabled by default. You have to use the JSX plugin, that uses React under the hood. More info: https://lumeland.github.io/plugins/jsx/

If you want to run React in the front side, you can take a look to this demo repo https://github.com/lumeland/react-todo

**Comment by audrow** [comment]
Awesome, thank you @oscarotero and thank you for the quick reply!
