### ISSUE TITLE
Nunjuck's options stopped working

### ISSUE THREAD

**Issue by fserb** [lumeland/lume#156]
I have a:
```js
site.use(nunjucks({
  options: {
    autoescape: false,
  },
  plugins: {
  // some plugins.
  }
}));
```

With the `HEAD` version of Lume, the `autoescape` (which, btw, I think should be the default for Lume, but not the point) doesn't get used anymore.

I'm not sure what the issue here is:

1. Is this the proper way to pass options to a default plugin? I see that nunjuck ends up being initialized twice (one for the default and one from my `site.use()`.

2. On the 2nd call, I see that `options.options` has the proper `autoescape` value, but that is not doing what it used to do (i.e., disable autoescape). If I manually switch my templates to include `{{ content | safe }}`, then it works fine... I thought it could be a nunjuck's problem, but I don't see a version bump anywhere.

help?

[]s
F.

**Comment by oscarotero** [comment]
Hi @fserb 

To configure a default plugin, the `lume()` function in _config has a second argument for that. See here: https://lumeland.github.io/core/nunjucks/#configure-the-nunjucks-plugin

I have tried this and it works fine:

```js
const site = lume({
  location: new URL("https://example.com/"),
}, {
  nunjucks: {
    options: {
      autoescape: false
    }
  }
});
```

**Comment by fserb** [comment]
Ahn, I used to have that.

The reason I changed (and it used to work fine, but I get it it's a bit weird). Is that I have plugins on both Nunjucks and Markdown that I want to pass `site.options.dev`. Is there any way we can support accessing it before site is initialized?

**Comment by fserb** [comment]
Nevermind, I just added a:

```js
const dev = Deno.args.indexOf('--dev') != -1;
```

to the beginning of the file. Much simpler. :)

**Comment by oscarotero** [comment]
Yes, I was about to suggest something like that.
Perhaps, there could be something more solid (an environment variable like `LUME_DEV` for example) but this is the only way at this moment.
