### ISSUE TITLE
How to replace a default engine?

### ISSUE THREAD

**Issue by fserb** [lumeland/lume#157]
I have a plugin with:

```js
site.loadPages([".md"], textLoader, new MyEngine());
```

With the new code this breaks, because `Engines.engine` ends up like:

```js
Extensions {
  default: undefined,
  entries: [
    [ ".tmpl.ts", ModuleEngine { helpers: [Object] } ],
    [ ".tmpl.js", ModuleEngine { helpers: [Object] } ],
    [ ".md", MarkdownEngine { engine: [Object] } ],
    [
      ".njk",
      NunjucksEngine { env: [Object], cache: [Map], ... }
    ],
    [ ".md", MyEngine {} ]
  ]
```

and `Engines.engine.search()` returns the first entry. `Extensions` doesn't seem to worry about duplicates. Ideas?

**Comment by oscarotero** [comment]
Mmm. The `Extensions` class should replace existing values instead of duplicate them. 
Here https://github.com/lumeland/lume/blob/master/core/extensions.ts#L14 the function should remove the existing value before adding the new one.
Feel free to createa PR or I will fix it (I cannot right now).

**Comment by oscarotero** [comment]
I just released a new version with the duplicated extensions bugfix.
