### ISSUE TITLE
`page.data.url` disappears when `page.addData` is called

### ISSUE THREAD

**Issue by aiotter** [lumeland/lume#161]
# Description of the bug
When you set processor or preprocessor to call `page.addData`, `page.data.url` will be lost.

# Reproduction procedure
1. Create `index.md` at the root directory of the project.
2. Create `_config.ts` as following:

```ts
import lume from "lume/mod.ts";
import { Page, Site } from "lume/core.ts";

const site = lume();

site.use((site: Site) => site.process([".html"], (page: Page) => page.addData({ foo: "bar" })));
// OR: site.use((site: Site) => site.preprocess([".html"], (page: Page) => page.addData({ foo: "bar" })));

site.use((site: Site) => site.addEventListener("afterBuild", () => site.pages.forEach((page) => console.log(page.data))));

export default site;
```

3. You'll get the following result:
```js
{ tags: [], content: "index\n", date: 2022-01-10T09:35:35.019Z, foo: "bar" }
```

Commenting out the processor registration, or passing a function with no side effect as a processor will create the desired output:
```js
{ tags: [], content: "index\n", date: 2022-01-10T09:35:35.019Z, url: "/" }
```

**Comment by aiotter** [comment]
Workaround.
```ts
import lume from "lume/mod.ts";
import { Page, Site } from "lume/core.ts";

const site = lume();

site.use((site: Site) => site.process([".html"], (page: Page) => page.data.foo = "bar"));
site.use((site: Site) => site.addEventListener("afterBuild", () => site.pages.forEach((page) => console.log(page.data))));

export default site;
```
```js
{ tags: [], content: "index\n", date: 2022-01-10T09:35:35.019Z, url: "/", foo: "bar" }
```

**Comment by oscarotero** [comment]
Hi.
`page.addData()` is a function to use internally by Lume. To add data to a page use `page.data` property as you did in the workaround.

**Comment by aiotter** [comment]
I see!
Do you think it is possible to hide the `Page#addData` method so that it is clear for users that it is not intended to be called?
Like making it private or prepend `_`?

**Comment by oscarotero** [comment]
It's public because it's used by an external class [the `Source` class](https://github.com/lumeland/lume/blob/master/core/source.ts#L202) but prepending with `_` is a good idea.

**Comment by aiotter** [comment]
Nice work! Thanks 👍
