### ISSUE TITLE
Allow Options Passed to Template Engine Plugins

### ISSUE THREAD

**Issue by shadowtime2000** [lumeland/lume#17]
I see that every plugin is a closure that takes no arguments. I was wondering if we could option it up to have options passed to them for template engines and such so users can configure stuff.

**Comment by oscarotero** [comment]
Yes, that's the initial idea of using closures for that, but I didn't have time to think how it should work. For now, the only plugin accepting arguments is [dom](https://github.com/lumeland/lume/blob/master/plugins/dom.js) to configure the function to be executed. But my idea is design a more consistent and previsible way to configure plugins, with an object of settings. For example, I imagine something like this:

```js
import eta from "https://deno.land/x/lume/plugins/eta.js";

site.use(eta({
    extensions: [".eta", ".eta.html"],
    config: {
        tags: ["{{", "}}"],
        plugins: myPlugins
    }
}));
```

I mean, similar plugins should have similar settings. For example, plugins to add new template engines should have a way to configure the file extensions to apply to and an object to pass specific options to the library (eta, nunjucks, markdown-it, etc).

**Comment by oscarotero** [comment]
Almost all plugins allow to pass options, for example, for Eta you can configure the extensions (https://github.com/lumeland/lume/blob/master/plugins/eta.js).
So I can close this issue. More options can be added easily in the future.
