### ISSUE TITLE
simulate directories and files by sqlite/table

### ISSUE THREAD

**Issue by elycheikhsmail** [lumeland/lume#174]
is possible to simulate/replace directories and files by table(sqlite or mysql ...) for lume ?
I study possibility to build CMS like wordpress on top of lume, mysql and deno deploy

**Comment by oscarotero** [comment]
Yes. One unique file can create many pages. For example:

```js
import database from "./my-database.ts";

export default function * () {
    const articles = database.query("select * from articles");

    for (const article of articles) {
        // Return a page
        yield {
            url: "/articles/" + article.slug,
            content: article.content,
        }
    }
}
```

In short: use generators to generate as many pages as you want from an unique file.

**Comment by elycheikhsmail** [comment]
> Yes. One unique file can create many pages. For example:
> 
> ```js
> import database from "./my-database.ts";
> 
> export default function * () {
>     const articles = database.query("select * from articles");
> 
>     for (const article of articles) {
>         // Return a page
>         yield {
>             url: "/articles/" + article.slug,
>             content: article.content,
>         }
>     }
> }
> ```
> 
> In short: use generators to generate as many pages as you want from an unique file.

Thank you @oscarotero.
It seems you understand my question we can generate multiple pages from one file but I'm not sure if I understand enough your answer but I will try,
The dara source can come from any db or hard coded.
Can you give me complete simple example with data hard coded.

**Comment by kyuzu** [comment]
> Can you give me complete simple example with data hard coded.
```ts
export default function * () {
    const articles = ["foo", "bar", "baz", "some"];

    for (const article of articles) {
        // Return a page
        yield {
            url: "/articles/" + article.slug,
            content: article.content,
        }
    }
}
```
```

**Comment by oscarotero** [comment]
You have more info here: https://lume.land/docs/core/multiple-pages/

**Comment by kyuzu** [comment]
I think we can safely close this issue.
