### ISSUE TITLE
Distribute Lume through asdf plugins

### ISSUE THREAD

**Issue by x80486** [lumeland/lume#176]
`asdf` is a CLI tool that can manage multiple language runtime versions on a per-project basis.

While Lume is quite easy to install, sometimes it's desirable to handle multiple versions. I think it might look very similar to the [asdf-deno](https://github.com/asdf-community/asdf-deno) repository.

**Comment by oscarotero** [comment]
I'm not sure if this is useful. `lume import-map` generates the `import_map.json` and `deno.json` files, so you have the lume version number there. It also creates two tasks in the `deno.json` file, so you can run `deno task build` and `deno task serve` directly, without using the installed lume cli (example: https://github.com/lumeland/lume.land/blob/main/deno.json)

So, in theory you can manage different lume versions just editing these files.

**Comment by oscarotero** [comment]
> but I think this time https://deno.land/x/lume@vX.Y.Z/ci.ts is downloaded all the time for every command?

It's downloaded only the first time, the next time Deno use the cached version, so you don't need to be connected all the time.

If you want to work on a `asdf` plugin, I'm ok with that, but I don't know what's the advantage over the import map file.

**Comment by x80486** [comment]
OK, I think from the moment users can get into any recent version of `Lume` that wouldn't be needed. It's more convenient to have that in the `deno task`s.

Wouldn't that approach retire as well the Docker images? Basically with the proper `Deno` version, `Lume` will be able to run without problems.

**Comment by oscarotero** [comment]
Good point. Yes I think `deno task` combined with the `import_map.json` file makes more convenient to run any lume version without install it. Users can install Deno from the official docker image and run lume directly. The only problem is if an outdated deno version is used, but in this case lume shows an error message.

**Comment by x80486** [comment]
Great! Then at some point we can set the path to start retiring the `Docker` images. I think whenever `Deno` tasks become stable could be the starting point :thinking:
