### ISSUE TITLE
åäö does not work in slugs in dev mode

### ISSUE THREAD

**Issue by enjikaka** [lumeland/lume#179]
I have a few urls on https://barlingshult.se that include the swedish letters åäö. These work fine in the built version but when running lume locally with the `--serve --dev` flags it's not possible to navigate to resources under these slugs. I'm then greeted with the following error:

<img width="474" alt="Skärmavbild 2022-04-12 kl  18 51 14" src="https://user-images.githubusercontent.com/877455/163013885-45ae2bf6-ea32-4078-ab13-dadd4b7b8754.png">
 
The slug name is inferred from the folder name and not set customly. 
Source of the entire site: https://github.com/enjikaka/barlingshult

**Comment by oscarotero** [comment]
Ok, let me see.

**Comment by enjikaka** [comment]
<img width="479" alt="Skärmavbild 2022-04-12 kl  19 29 05" src="https://user-images.githubusercontent.com/877455/163020013-0f039fd1-ed80-43b0-89eb-414de4fcc25a.png">

Should probably note that the URL in address bar is correct. So it's not a write-to <a> issue, but rather how the dev server routes :)

**Comment by oscarotero** [comment]
It works fine in my local:

<img width="900" alt="imaxe" src="https://user-images.githubusercontent.com/377873/163021436-7b434be5-2bef-4efc-83ad-15855e2f2246.png">

What lume version do you have?

**Comment by enjikaka** [comment]
Hmm. I've ran `deno run -A https://deno.land/x/lume/install.ts` today sayding it installed v1.7.3 and using `deno run -A https://deno.land/x/lume/ci.ts --serve --dev` to run the dev server but running `deno run -A https://deno.land/x/lume/ci.ts --version` gives me `v1.4.3`. How do I get ci.ts to use latest? I thought it did since there wasn't any version lock in the URL.

**Comment by enjikaka** [comment]
Locked the URL in the make file now o not be confused again. I suppose there is some Deno cache spooking around? https://github.com/enjikaka/barlingshult/commit/a5493097592984c5ef8f53eb56187c725949722e

**Comment by oscarotero** [comment]
Yes, by using a module without version, deno download the latest available version at this moment and cache it. The lume cli fixes this, but if you don't want to depend on having lume installed in your computer, you can run `lume import-map`, that creates two files: A `import_map.json` file with your lume version and  a `deno.json` file containing two tasks, so you can run `deno task build` or `deno task serve` to run lume. (Tasks is a new thing in Deno, similar to run scripts with npm: https://deno.land/manual/tools/task_runner)

**Comment by enjikaka** [comment]
Okey, thanks for the info. I'll try the tasks!
