### ISSUE TITLE
Suppress update notice if the user ran `lume upgrade`

### ISSUE THREAD

**Issue by binyamin** [lumeland/lume#206]
This is funny, in an ironic sort of way. I updated lume to v1.10.0, and afterwards, it told me I should update lume to v1.10.0. It probably just checked at the beginning of the command, and didn't realize I ran the `lume upgrade` command.

```console
$ lume upgrade
...
Update successful!
You're using the latest version of Lume: v1.10.0!
See the changes in https://github.com/lumeland/lume/blob/v1.10.0/CHANGELOG.md

----------------------------------------
Update available v1.9.1  → v1.10.0
Run lume upgrade to update
----------------------------------------
```

![Image of the console's output, which is also written in the code-block above](https://user-images.githubusercontent.com/39805353/174346294-c587dfb0-dad8-4b0d-b3b4-f12f1b18813a.png)

**Comment by oscarotero** [comment]
Yep, good catch. I'll fix it in the next version.
Thanks!
