### ISSUE TITLE
SASS plugin includes

### ISSUE THREAD

**Issue by jrson83** [lumeland/lume#213]
# Version Info
Windows 11 (64 bit)
deno 1.23.2 (release, x86_64-pc-windows-msvc)
v8 10.4.132.8
typescript 4.7.2
lume v1.10.0

# Description

The SASS docs [Configuration](https://lume.land/plugins/sass/#configuration) chapter states:

> includes: An array of directories to search for the `@imported` files. By default is _includes.

When I move `.scss` files outside the `_includes` directory, they get transformed to `_site/whatever_dir/[file].css`, even if I do not specify any `sass.includes` path.

I created the following project structure:

```
lume-root
 ┣ _includes
 ┃ ┗ sass
 ┃ ┃ ┣ index.scss
 ┃ ┃ ┗ _test.scss
 ┣ deno.json
 ┣ import_map.json
 ┗ _config.ts
```

```scss
// index.scss
@import "./test";

body {
  background-color: #000;
}
```

```js
// _config.ts
import lume from "lume/mod.ts";
import sass from "lume/plugins/sass.ts";

const site = lume();

site.use(sass());

export default site;
```

When I run `deno task serve`, the `.scss` files are not getting transformed to `.css`.

In serve mode, if I make changes to the files they getting registered:
```shell
Changes detected:
- /_includes/sass/index.scss
```

I tried setting `sass.includes` with `./` and without `./` combinations as `string` and also as `Array<string>`, but nothing worked.

- ["./_includes/sass/"]
- ["./_includes/sass"]
- ["./_includes/"]
- ["./_includes"]

I created a different directory with an underscore `_styles` and moved the files in the directory, they not getting transformed. I also tried to specify the `sass.includes`.

So it seems, the plugins default is to search in every subdir of the rootdir, but not if the dir contains an underscore.
If you need I'll create an example for reproduction. Thanks for the great work!

**Comment by oscarotero** [comment]
The `_includes` folder contains files that can be included by other files but they aren't loaded and rendered if no other file include them. In your example, you have all scss files in the `_includes` folder but there isn't any other scss file outside this folder that import these files. Let's say you have this structure:

```
lume-root
 ┣ _includes
 ┃ ┗ sass
 ┃   ┗ component1.scss
 ┃   ┗ component2.scss
 ┣ deno.json
 ┣ import_map.json
 ┣ styles.scss
 ┗ _config.ts
```
And the `styles.scss` file (that it's ouside `_includes` so Lume will load it) import the other two files:

```scss
// styles.scss

@import "sass/component1.scss";
@import "sass/component2.scss";
```

This will output the `_site/styles.css` file with the content of the two imported files.

**Comment by jrson83** [comment]
> In your example, you have all scss files in the _includes folder but there isn't any other scss file outside this folder that import these files. Let's say you have this structure:

Okay, now I got it, If I set it up like this, it is working. Thanks for the explanation.

Closing.
