### ISSUE TITLE
Generator plugin

### ISSUE THREAD

**Issue by oscarotero** [lumeland/lume#215]
A plugin that inject the `lume` global variable with the lume version and other environment variables that can be used in the page, for example to create a `<meta name="generator">` tag.

"Inspired" by https://www.11ty.dev/docs/data-eleventy-supplied/#eleventy-variable

**Comment by binyamin** [comment]
It could be added to the "metas" plugin, for easy usage.

**Comment by oscarotero** [comment]
> It could be added to the "metas" plugin, for easy usage.

Good idea!

**Comment by binyamin** [comment]
Gotcha. I do think it would be useful to expose the Lume version as a global variable.
