### ISSUE TITLE
Detect and load `.env` files automatically?

### ISSUE THREAD

**Issue by oscarotero** [lumeland/lume#216]
Should Lume load automatically .env files in the root directory?

[bun.sh](https://bun.sh/) does it automatically. Deno's std library has dotenv implemented: https://deno.land/std@0.148.0/dotenv so it's easy to use it in Lume.

**Comment by bryophyta** [comment]
I'm not sure if you're seeking feedback on this, so please feel free to ignore this if not!

For what it's worth, I would be inclined against adding this behaviour, unless there's a significant reason for adding it. While it would definitely be convenient for most cases, I think there is an advantage to keeping `env` management more explicit. Especially given that, as you noted, it's not too inconvenient to add it to a project with Deno's standard lib.

Having said that, I could imagine that some people using Lume might not know Deno in great depth yet, so it would be nice to make it easy for them to use `.env` config. What would you think of the idea of adding a section to the docs which gives an example of how to add `env` management using Deno's standard libs?

Again, this is just my opinion. And I'd definitely be interested to hear the argument for the alternative view!

**Comment by kidonng** [comment]
I don't have opinions about the feature itself, but I'm very curious about use cases in a static site generator. Environmental variables are mostly for server side programs and for a SSG it would require at most `NODE_ENV`.

**Comment by bryophyta** [comment]
Interesting question! A couple of use-cases for environmental variables which I can think of, for a library like Lume:

- Set a target directory for the build process to build to (e.g. if you have an experimental build and a stable build).
- You might also use an abstraction like `dev`/`prod` to control other similar things about the build process (e.g. in dev you might want to skip lengthy processes like image processing).
- If you're running the build process in a continuous integration setup like Github Actions, you may want to be able to pass sensitive values like an API key or salt to the build process, without exposing them in your logs etc.

You could probably find good alternatives to using env variables for all of these use-cases, but it does seem to me like they'd be quite helpful. I'd be interested to hear your thoughts though -- do you think that using env variables would be unsuitable in these cases?

**Comment by oscarotero** [comment]
> I'm not sure if you're seeking feedback on this

@bryophyta Feedback is always welcome! It's interesting your thoughts about making the `env` variables more explicit and reduce the  "magic" from Lume.

> I'm very curious about use cases in a static site generator.

A real use case is a static site using the data from the Eventbrite API to show the number of tickets sold. The site is regenerated every hour to get up to date data. It requires a token and an event Id to connect to the API, that are stored in env variables.


> - Set a target directory for the build process to build to (e.g. if you have an experimental build and a stable build).
> - You might also use an abstraction like dev/prod to control other similar things about the build process (e.g. in dev you might want to skip lengthy processes like image processing).

I think these use cases can be addressed easily passing the env variable directly in the build script. For example: `ENV=prod deno task build`. Or creating two deno tasks like `deno task build` and `deno task build-prod`.
To me, the most interesing use case of env files is to store secret values that you don't want to include in the git repo. But I'm agree that maybe it's not a so common use case.

**Comment by kidonng** [comment]
> * Set a target directory for the build process to build to (e.g. if you have an experimental build and a stable build).

This should be using different config, not environment variables.

> * You might also use an abstraction like `dev`/`prod` to control other similar things about the build process (e.g. in dev you might want to skip lengthy processes like image processing).

This is what `NODE_ENV` does (pardon me for mentioning again, I just need a metaphor).

> * If you're running the build process in a continuous integration setup like Github Actions, you may want to be able to pass sensitive values like an API key or salt to the build process, without exposing them in your logs etc.

I think @oscarotero's example covers this well, and also quoting them:

> But I'm agree that maybe it's not a so common use case.

If lume starts to load `.env` automatically, then it probably needs to provide a config to opt out. Or lume can provide a option to load `.env` that is disabled by default.

But these are just too much hassle. Anyone who really wants `.env` need to do nothing more than put this one line in their `_config.ts`:

```js
import "https://deno.land/std/dotenv/load.ts"
```

That's it. And I would argue this is not much harder in Node, just an extra step to install `dotenv`. The whole point of it is to make things easier to configure.

To sum it all, I love tools picking up related files, but only if those are indeed related.
