### ISSUE TITLE
Module does not provide an export named 'loadWASM'

### ISSUE THREAD

**Issue by jrson83** [lumeland/lume#217]
I tried using [rehype-pretty-code](https://github.com/atomiks/rehype-pretty-code) from [esm.sh](https://esm.sh/rehype-pretty-code@0.3.2) with the experimental remark/rehype plugin:

```js
import rehypePrettyCode from "https://esm.sh/rehype-pretty-code@0.3.2";
```

I'm getting the following error on build/serve:

```shell
SyntaxError: The requested module '/v87/vscode-oniguruma@1.6.2/deno/vscode-oniguruma.js' does not provide an export named 'loadWASM'
    at async createSite (https://deno.land/x/lume@v1.10.0/cli/utils.ts:15:17)
    at async build (https://deno.land/x/lume@v1.10.0/cli/build.ts:29:16)
    at async Command.execute (https://deno.land/x/cliffy@v0.24.2/command/command.ts:1275:7)
    at async (https://deno.land/x/lume@v1.10.0/cli.ts:173:3)
```

I tried adding the [shiki](https://esm.sh/shiki@0.10.1) esm.sh module to my `import_map.json`. When I run `deno cache --reload _config.ts` I see it is downloading the required module from [vscode-oniguruma](https://esm.sh/v87/vscode-oniguruma@1.6.2/deno/vscode-oniguruma.js), but I still get the same error.

My `deno.json`:

```json
"compilerOptions": {
  "lib": [
    "dom",
    "dom.iterable",
    "dom.asynciterable",
    "deno.ns",
    "deno.unstable"
  ],
}
```

I also tried to use [shikigami](https://github.com/norskeld/shikigami) from [esm.sh](https://esm.sh/@nrsk/shikigami@1.1.2) with the markdown-it plugin and get the same error. I checked the repo from vscode-oniguruma. The `index.ts` has [no default export](https://github.com/microsoft/vscode-oniguruma/blob/main/src/index.ts#L394).

```js
import { loadTheme, shikigami } from "https://esm.sh/@nrsk/shikigami@1.1.2";
```

I'm not sure if this is related to `cliffy` or `lume`.

**Comment by oscarotero** [comment]
Running `deno info https://esm.sh/rehype-pretty-code@0.3.2` you can see the dependencies of this package, that contains `vscode-oniguruma`. Probably the error is on importing the library from `esm.sh`, that doesn't work for all packages.
In Lume I had to import some dependencies from other CDNs (markdown-it, for example, is imported from jspm.dev because esm.sh fails). The automatic conversion of CJS to ESM by esm.sh doesn't work always.

**Comment by jrson83** [comment]
Thanks for the info. After 3 hours trying to import from different sources, I give up now. There must be seriously something wrong. I'm at least stuck at:

```shell
SyntaxError: The requested module 'vscode-oniguruma' does not provide an export named 'createOnigScanner'
```

Well, it does inside the [main.d.ts](https://github.com/microsoft/vscode-oniguruma/blob/main/main.d.ts#L22), but however it seems not to get referenced when importing `release/main.js`, since there exist no types inside the `release` folder.

![2022-07-18_23h30_19](https://user-images.githubusercontent.com/45284565/179620964-a65aa3b2-5f2e-43c1-b71f-b280f0ae9acb.png)

**Comment by jrson83** [comment]
Closing, since it's not related to lume.
