### ISSUE TITLE
Recommended way to add post-`use()` configuration to markdown-it plugins?

### ISSUE THREAD

**Issue by bryophyta** [lumeland/lume#218]
Hi, I'm not sure if this issue belongs here or in the main lume repo, but I'm happy to re-open it there if that's better.

## Issue

For at least some markdown-it plugins, the recommended way of customising the output requires setting properties on the markdown-it instance's `.renderer.rules` object. An example is [customising the markup for footnotes in `markdown-it-footnotes`](https://github.com/markdown-it/markdown-it-footnote#customize).

As far as I can tell, the built-in implementation of markdown-it in lume doesn't expose the markdown-it instance after initialisation. If so, it won't be possible to make these kinds of customisations. If you create a custom instance of markdown-it then the built-in implementation can be overridden using `site.loadPages()` in the lume `_config.ts`. (Minimal reproducible example included below.)

This works, but I was wondering if this is the recommended way to make these sorts of customisations to renderers in lume or not? If so, do you think it would be worthwhile to document it? (I'm happy to open a PR.) If there is an alternative recommended method, would you be able to say anything about how you would suggest doing this? 

Thanks!

## Minimal working example

```ts
// _config.ts

import lume from "https://deno.land/x/lume@v1.10.0/mod.ts";
import { MarkdownEngine } from "https://deno.land/x/lume@v1.10.0/plugins/markdown.ts";
import textLoader from "https://deno.land/x/lume@v1.10.0/core/loaders/text.ts";

import markdownIt from "https://jspm.dev/markdown-it@13.0.0";
import footnote from "https://ga.jspm.io/npm:markdown-it-footnote@3.0.3/index.js";

// @ts-ignore: This expression is not callable.
const md = markdownIt();
md.use(footnote);

/**
 * add custom rule after markdown-it engine is initialised
 * @see https://github.com/markdown-it/markdown-it-footnote#customize
 */
md.renderer.rules.footnote_block_open = () => (
  "<h2>This is a custom footnote header</h2>\n" +
  '<section class="footnotes">\n' +
  '<ol class="footnotes-list">\n'
);

const site = lume({});

site.loadPages([".md"], textLoader, new MarkdownEngine(md));

export default site;
```

```markdown
<!-- index.md -->

# Footnote test page

This sentence has a footnote.[^1]

This is a new paragraph.

[^1]: This is the footnote.

```

Running the lume `ci.ts` from the command line with these from the directory containing these files renders a page with the custom footnote heading, as intended: 
<img width="385" alt="screenshot of page with custom heading" src="https://user-images.githubusercontent.com/37048459/179854318-bf20b9ae-1ae2-45ed-9926-67c08dd4f0ae.png">

(The backref character link character at the end is rendered wrongly in the screenshot, but I'm pretty sure that this is an unrelated bug with my system.)

**Comment by oscarotero** [comment]
I just added the `rules` option to markdown. It will be available in the next version.

**Comment by bryophyta** [comment]
> I just added the rules option to markdown. It will be available in the next version.

wow, thanks for such a quick response!

just to clarify one point from your original response -- is the `site.formats.get()` method that you mentioned a part of lume's external API? Or is it only designed for use within the internals of lume? (I'm partly wondering whether as users we can consider it to be a stable API or not.)

**Comment by oscarotero** [comment]
I only consider stable API all `site` functions that allows to configure the site building (`site.copy()`, `site.use()`, `site.ignore()`, etc (all functions documented in the lume.land site).

All internal objects, like `site.formats`, could change in the future, for performance improvements, implementing new features, etc. I think they won't change much in the short term, but I cannot confirm 100%.
