### ISSUE TITLE
Question on renderOrder, to access data assigned from plugins

### ISSUE THREAD

**Issue by jrson83** [lumeland/lume#219]
I'm using the [remark plugin](https://github.com/lumeland/experimental-plugins/tree/main/remark), which now adds `vFile.data` to the markdown `pages.data`. It is working great, so I wrote another rehype plugin, to exctract an `excerpt` (the first paragraph, with max length of 140 characters), from every blog post. The `vfile.data.excerpt` gets appended to the `page.data.excerpt`, like  using the `rehype-extract-toc` plugin.

Now using the `.md` files layout file, I have access to the `page.data` which includes:

```js
url: "/posts/blog-post-02/",
excerpt: "Lorem markdownum exclamant. Saevit iussa, in parentem praenovimus gerit sceleratior ipse ima quam\nal...",
toc: [
  { depth: 2, value: "Praevisos ductae et poenae esse pereunt enituntur" },
  { depth: 2, value: "Illis Hyadasque dederat" },
  { depth: 2, value: "Adversi firmat nigra et traiectus quos" },
  { depth: 2, value: "Dignior lucis multa comitavit tenet" }
],
```

In my `index.tsx` page file, for which the `excerpt` data was supposed to be, I loop through the posts:

```js
export default ({ search }: SiteData) => {
  const posts = search.pages("type=post", "date=desc", 3);
  return (
    <section>
      <h1>Recent blog posts</h1>
      {posts.map(({ data }) => (
        <article>
          <h2>{data.title as string}</h2>
          {data.excerpt}
        </article>
      ))}
    </section>
  );
};
```

Here I don't have access to the data, since like I read in the docs [render order](https://lume.land/docs/core/render-order/), the pages didn't exist before the `index` page was rendered. I tried changing the `renderOrder` from all posts inside `./posts/_data.ts`: `export const renderOrder = -1;`

But after build I can see no navbar items at all, (they are defined through `menu` inside the pages), the blog posts getting displayed, but the `page.data` still not contains `excerpt` & `toc`.

When I use `export const renderOrder = 1;` inside the index page, the navbar does not contain the index page, the blog posts getting displayed, but the `page.data` still not contains `excerpt` & `toc`.

Here is my `_config.ts` order:

```js
site
  .copy("assets", ".")
  .use(readingTime())
  .use(date())
  .use(slugifyUrls())
  .use(remark({
    remarkPlugins,
    rehypePlugins,
  }))
  .use(preactjsx())
  .use(postcss())
```
If you can give any advice, I would be pleased.

**Comment by oscarotero** [comment]
This is not related with `renderOrder`. The reason is the data inserted by remark plugin is not persistent. It's only available while the page is being rendered (the page file and the layouts used by the page), allowing to insert the `toc` inside the page layout.

I have to think in a way to make this data persistent, in order to be used by other pages. Meanwhile, a simple way to extract an excerpt is this https://github.com/lumeland/theme-simple-blog/blob/main/mod.ts#L24-L26, using a `<!-- more -->` comment in the post content.

**Comment by jrson83** [comment]
> I have to think in a way to make this data persistent

That would be cool. For my readingTime plugin I figured out I had to use `site.preprocess` to make the data persistent.

> Meanwhile, a simple way to extract an excerpt is this https://github.com/lumeland/theme-simple-blog/blob/main/mod.ts#L24-L26, using a  comment in the post content.

Thanks I will try it out.

**Comment by jrson83** [comment]
@naiyerasif would be awesome if you had time to look into this issue and maybe implement the solution @oscarotero suggested yesterday in the help channel:

> The only solution I can think is store the data in a sub-key
> instead of store the data in the root of the page (page.data.toc) 
> it should be stored in a predefined key, like page.data.vfile.toc)

Here is the rehypeExtractExcerpt plugin maybe you can additionally use for testing/recreation:

```typescript
import { hastUtilToString, unified, unistUtilVisit } from "../deps.ts";

export interface RehypeExtractExcerptOptions {
  /** The var name of the vFile.data export. defaults to `excerpt` */
  name?: string;

  /** The character length to truncate the excerpt. defaults to 140  */
  maxLength?: number;

  /** The ellipsis to add to the excerpt. defaults to `...` */
  ellipsis?: string;

  /** Truncate the excerpt at word boundary. defaults to `true` */
  wordBoundaries?: boolean;
}

const defaults: RehypeExtractExcerptOptions = {
  name: "excerpt",
  maxLength: 140,
  ellipsis: "...",
  wordBoundaries: true,
};

const rehypeExtractExcerpt: unified.Plugin<
  [RehypeExtractExcerptOptions?],
  hastUtilToString.Root,
  void
> = (userOptions?: RehypeExtractExcerptOptions) => {
  const options = { ...defaults, ...userOptions };

  return (tree: hastUtilToString.Root, vfile: unified.VFileWithOutput<unknown>) => {
    const excerpt: string[] = [];

    unistUtilVisit.visit(tree, "element", (node: hastUtilToString.Element) => {
      if (node.tagName !== "p") {
        return;
      }

      excerpt.push(
        truncateExcerpt(
          hastUtilToString.toString(node),
          options.maxLength!,
          options.ellipsis!,
          options.wordBoundaries!,
        ),
      );

      return unistUtilVisit.EXIT;
    });

    vfile.data[options.name!] = excerpt[0];
  };
};

function truncateExcerpt(
  str: string,
  maxLength: number,
  ellipsis: string,
  wordBoundaries: boolean,
): string {
  if (str.length > maxLength) {
    if (wordBoundaries) {
      return `${str.slice(0, str.lastIndexOf(" ", maxLength - 1))}${ellipsis}`;
    }
    return `${str.slice(0, maxLength)}${ellipsis}`;
  }
  return str;
}

export default rehypeExtractExcerpt;
```

**Comment by naiyerasif** [comment]
What @oscarotero has suggested is a workaround and not a solution. We should have a discussion around how Lume can have an API for any data that is accessible to `search` and `paginate` that can be safely enriched by plugins.

I was thinking about introducing some sort of global store that can be referred by `search` but this is something that needs deliberation and community feedback.

**Comment by oscarotero** [comment]
The data object passed to the renderers is a copy of the original page data object (here: https://github.com/lumeland/lume/blob/master/core/renderer.ts#L240) to prevent issues caused by modify this object later (like here: https://github.com/lumeland/lume/blob/master/core/renderer.ts#L271-L272), specially after rendering the page again after an update.

This is the reason why data stored in this object is accessible only when the page is being rendered, but is not really stored in the `page.data` object, hence, is not present on using `search` and `paginate`.

One simple solution could be include the page in the data object, like:

```ts
let data = { ...page.data, page };
```

So plugins can store data in the `data` object, like they do now or in the `data.page.data` object (so they are persistent).
