### ISSUE TITLE
Search for 404 Page

### ISSUE THREAD

**Issue by Abiti-936** [lumeland/lume#220]
I am Playing with Lume & I have deployed a simple site to Deno Deploy & Working Fine, but after implementing a 404 page I can't get the 404 page, when pages are not Found. I have seen that because there's a hard coded Not Found response in https://github.com/lumeland/lume/blob/master/core/server.ts#L137-L140.

Can We search for 404.html before sending Not Found Response?

**Comment by oscarotero** [comment]
You have to configure the `not_found` middleware in the server file.
Take a look to https://github.com/lumeland/base-blog/blob/master/server.ts#L11-L14
I have to update the documentation with this.

**Comment by Abiti-936** [comment]
Thanks, that's works!
