### ISSUE TITLE
Invalid `url` values are not caught

### ISSUE THREAD

**Issue by bryophyta** [lumeland/lume#222]
When specifying a `url` for a page in its yaml header, some values will fail silently. For example:

```markdown
---
# index.md

url: 0
---

# Hello world
```

This page will be built as `_site/index.md`. I believe that this is because the top-level checks that happen on the `url` value are to see if it is `false` or has `typeof string` or `typeof function`. https://github.com/lumeland/lume/blob/8e6bb7b112861b2699a37d89501aeb000768298f/core/renderer.ts#L175-L220

Because values like `0` are parsed as numbers, they fail these conditions (thereby bypassing the validation that happens for strings) and end up with the default `url`.[^1] My assumption is that this is not the desired behaviour?

Do you have a sense of what the desired behaviour would be, here? I'm not sure whether it would be better for it to crash, or to warn the user, or to coerce the value to a string. But if you have a view on what the desired behaviour should be, I'd be happy to try and write up a PR to implement it.

[^1]: Similarly, if an array is provided as the `url` value, this will also fail silently and the page will be built with its default url.

**Comment by oscarotero** [comment]
A quick workaround for your use case is force a string using quotes:

```md
---
# index.md

url: "0"
---

# Hello world
```

I think the behavior should be to throw an error with a message like `Invalid url value. It must be a string or a function returning a string`.

Your PR is very appreciated. Thank you!
