### ISSUE TITLE
v1.10.2 - Continuously Downloading React Packages while running commands

### ISSUE THREAD

**Issue by mskian** [lumeland/lume#237]
v1.10.2 - Continuously Downloading React Packages while running commands 

OS - Ubuntu - 20.04 LTS

## Example

```sh
/home/groot/.deno/bin/lume --version

Download https://esm.sh/v90/@types/react-dom@~18.2/server~.d.ts
Download https://esm.sh/v90/@types/react@~18.2/index.d.ts
Download https://esm.sh/v90/@types/react-dom@~18.2/server~.d.ts
Download https://esm.sh/v90/@types/react@~18.2/index.d.ts
🔥lume v1.10.2
````

**Comment by oscarotero** [comment]
I remember to have a similar issue some time ago. It looks like something wrong happens with the deno's cache. I had fixed it by removing the DENO_DIR folder. Can you try if that works for you? Run `deno info` to know the DENO_DIR location and remove this folder.

**Comment by mskian** [comment]
Tried still the issue happens

no issues lume `v1.10.1` and `v1.10.0`

**Comment by oscarotero** [comment]
Looks like the types files don't exist: https://esm.sh/v90/@types/react-dom@~18.0/server~.d.ts
so they cannot be downloaded and cached. It's weird because React wasn't updated. `v1.10.1` use the same version.

**Comment by mskian** [comment]
yes that file does not exist that's the reason every time it tried to reach

**Comment by oscarotero** [comment]
Should this be reported to esm.sh repository?

**Comment by oscarotero** [comment]
@mskian It looks like this issue have been fixed in V91 https://github.com/ije/esm.sh/issues/402

Can you please try again?

**Comment by mskian** [comment]
Fixed now no issues
