### ISSUE TITLE
Custom loaders cannot return Arrays

### ISSUE THREAD

**Issue by SheetJSDev** [lumeland/lume#242]
The following data loader should pull data from a spreadsheet and return an array of sheet objects:

```js
import { readFile, utils } from 'https://deno.land/x/sheetjs/xlsx.mjs';

function wbLoader(path) {
  const wb = readFile(path);
  return wb.SheetNames.map(n => ({
    name: n,
    data: utils.sheet_to_json(wb.Sheets[n])
  }));
}

site.loadData([".xlsx"], wbLoader);
```

When testing, the array is translated into an object without the `length` field.

For example, with the test file [users.xlsx](https://github.com/lumeland/lume/files/9396848/users.xlsx), the loader function generates the Array:

```js
[
  {
    name: "USA",
    data: [
      { name: "Oscar Otero", color: "black" },
      { name: "Laura Rubio", color: "blue" }
    ]
  },
  {
    name: "Europe",
    data: [
      { name: "Ozzy Osbourne", color: "black" },
      { name: "Jacques Clouseau", color: "pink" }
    ]
  }
]
```

The pages receive something different.  To see this, throw the data in index.jsx:

```jsx
export default ({users}) => {
  throw new Error(JSON.stringify(users));
}
```

The result is an object:

```json
{
  "0": {"name":"USA","data":[{"name":"Oscar Otero","color":"black"},{"name":"Laura Rubio","color":"blue"}]},
  "1": {"name":"Europe","data":[{"name":"Ozzy Osbourne","color":"black"},{"name":"Jacques Clouseau","color":"pink"}]}
}
```

Ideally a raw array could be passed through.  If not, adding the length would allow JSX pages to use `Array.from`.

Note: returning an object with an array property works but it adds an extra step in the page

```js
function wbLoader(path) {
  const wb = readFile(path);
  return ({ data: wb.SheetNames.map(n => ({
    name: n,
    data: utils.sheet_to_json(wb.Sheets[n])
  })) });
}
```

```liquid
{% for sheet in users.data %}
  <h2>{{sheet.name}}</h2>
  <table><thead><th>Name</th><th>Color</th></thead><tbody>
    {% for row in sheet.data %}
    <tr>
      <td>{{row.name}}</td>
      <td>{{row.color}}</td>
    </tr>
    {% endfor %}
  </tbody></table>
{% endfor %}
```

**Comment by oscarotero** [comment]
Yes, it's a bug.
I'm on vacation right know, but will fix it within a few days

**Comment by oscarotero** [comment]
I just fixed it. You can try the dev version (`lume upgrade --dev`) as long as the new version is not published.

Additionally, a way to fix it in the stable Lume version is returning the data in the `content` property. Example:

```js
function wbLoader(path) {
  const wb = readFile(path);
  return {
    content: wb.SheetNames.map(n => ({
      name: n,
      data: utils.sheet_to_json(wb.Sheets[n])
    }))
  };
}
```

**Comment by SheetJSDev** [comment]
Awesome!  Didn't test the dev version yet, but the workaround in the stable version does work.  Unfortunately it isn't mentioned in the relevant doc page (https://lume.land/docs/core/loaders/ ).

https://docs.sheetjs.com/docs/demos/content#lume includes a complete example.
