### ISSUE TITLE
Pagefind plugin

### ISSUE THREAD

**Issue by oscarotero** [lumeland/lume#253]
Pagefind is a fully static search library that aims to perform well on large sites, while using as little of your users’ bandwidth as possible, and without hosting any infrastructure.

https://pagefind.app/

**Comment by mskian** [comment]
share more info about this plugin with example

**Comment by oscarotero** [comment]
Working on it here: https://github.com/lumeland/experimental-plugins/tree/main/pagefind

The default configuration will attach a search box automatically in your pages, with simply:

```ts
import lume from "lume/mod.ts";
import pagefind from "lume/plugins/pagefind.ts";

const site = lume();
site.use(pagefind());

export default site;
```

Currently you can see a example of the search box in the [pagefind website](https://pagefind.app/):
<img width="1128" alt="image" src="https://user-images.githubusercontent.com/377873/189697295-dd949b5f-48ad-41b1-969e-de4268f1628a.png">

**Comment by mskian** [comment]
Thank you :-)

**Comment by mskian** [comment]
disallow page find page from search engine

```sh
Disallow: /pagefind/
```

Because Webmaster tool spot this as Blocked due to access forbidden (403)
