### ISSUE TITLE
Unable to paginate generated pages

### ISSUE THREAD

**Issue by paulrobertlloyd** [lumeland/lume#275]
I have a section of my site where I want to generate pages from a data source. I also want to generate an index page (that may then be paginated) which includes links to those generated pages. As far as I can tell, it is not possible to paginate over generated pages.

Here is a reduced test case. The page generator:

```js
// ./src/test/page.tmpl.js

export const layout = "page-layout.tmpl.js";

export default function* () {
  yield {
    url: "/test/one/",
    tags: ["page"],
    content: "This is the first page",
  };
  yield {
    url: "/test/two/",
    tags: ["page"],
    content: "This is the second page",
  };
  yield {
    url: "/test/three/",
    tags: ["page"],
    content: "This is the third page",
  }
;}
```

And the paginated pages generator:

```js
// ./src/test/index.tmpl.js

export const layout = "index-layout.tmpl.js";

export default function* ({ search, paginate }) {
  const pagination = paginate(search.pages("page"), {
    size: 36,
    url: (n) => n === 1 ? `/test/index.html` : `/test/page/${n}.html`,
  });

  for (const page of pagination) {
    yield page;
  }
}
```

In this scenario, the individual pages are generated, but not the paginated pages. Of note:

* If I log `search.pages("page")`, an empty array is returned.
* If I update `search.pages()` to search for a tag (or other query) for a set of non-generated pages, the paginated pages are generated.

**Comment by oscarotero** [comment]
Yes, this is because all pages are generated in parallel, so the paginator may be rendered before the other pages even exists. You can configure the render order to ensure that the paginator is executed after the other pages are generated.
See this: https://lume.land/docs/core/render-order/

**Comment by paulrobertlloyd** [comment]
Ah, I missed this. Works like a charm – thanks!
