### ISSUE TITLE
Inline plugin: Only pass attributes to SVG if declared in source HTML

### ISSUE THREAD

**Issue by paulrobertlloyd** [lumeland/lume#276]
I have an SVG image I want to inline in my HTML. Using the following source HTML:

```html
<img src="/assets/icons.svg" inline>
```

generates the following HTML

```html
<svg xmlns="http://www.w3.org/2000/svg" hidden width="0" height="0" class="" id="">
  …
</svg>
```

This is so helpful! However, as I’ve not defined any `class` or `id` attributes on the inlined image, empty attributes shouldn’t be included on the generated inline SVG element.

**Comment by oscarotero** [comment]
Mmm, this is a bug. I'll fix it in the next version.
Thanks!

**Comment by paulrobertlloyd** [comment]
That was fast – thanks again!
