### ISSUE TITLE
Publish standalone binaries

### ISSUE THREAD

**Issue by hayd** [lumeland/lume#28]
Given https://github.com/denoland/deno/pull/8539 it would be nice to have lume binaries published (by CI) on each release.

**Comment by shadowtime2000** [comment]
+1 to this

**Comment by shadowtime2000** [comment]
This would be great for projects in other languages that want to use Lume for technical documentation. I am wondering though, will a standalone binary still be able to import the config and the `((JS|TS)X?)` templates (sorry just had to make a regex).

**Comment by oscarotero** [comment]
This is a fantastic idea and definitively I want that.
Unfortunally, seems like it doesn't work fine. After execute the emitted binary, I get the following error:

```
error: ReferenceError: __default is not defined
    at file://$deno$/bundle.js:5935:16
```

**Comment by oscarotero** [comment]
It looks like is a bundler bug: https://github.com/denoland/deno/issues/8970

**Comment by JordanShurmer** [comment]
Looks like that bug may have been fixed now. Worth a try again?

**Comment by oscarotero** [comment]
It keep failing:

```
➜  deno -V
deno 1.7.1
➜  deno compile --unstable -A cli.js
Check file:///Users/oscarotero/lumeland/lume/cli.js
Bundle file:///Users/oscarotero/lumeland/lume/cli.js
Compile file:///Users/oscarotero/lumeland/lume/cli.js
Emit lume
➜  ./lume -v
error: ReferenceError: exports is not defined
    at file://$deno$/bundle.js:7740:37
```

**Comment by oscarotero** [comment]
Bug reported here: https://github.com/denoland/deno/issues/9346

**Comment by shadowtime2000** [comment]
Actually as I was doing more research into it, it turns out we would have to rewrite some of our code so we can support binaries. Because we can't dynamically import files relative to binaries we will have to rewrite it to read the file and then convert it to base64 and then dynamically import that, and we would have to wait for support for base64 data urls in binaries [denoland/deno#9397](https://github.com/denoland/deno/issues/9397).

~~Don't forget to upvote the feature request!~~

**Comment by oscarotero** [comment]
In lume we don't have this problem (I think) but yep, looks like having to bundle the entire code to generate a self container binary generates some issues and reduce the flexibility. I'd like to have a different approach, for example, only transpile the typescript code but maintaining the ESM under a specific protocol. For example: `import myModule from "bin://src/my-module.js"`. But perhaps it's too complicated, I don't know.

**Comment by shadowtime2000** [comment]
@oscarotero How does Lume import the config file if it doesn't use dynamic imports? I think really that feature request may be the only way if we were to support binaries because of how you can't dynamically import files external to the binary.

**Comment by oscarotero** [comment]
@shadowtime2000 Mmmm, you're right. I thought dynamic imports couln't load modules from the bundled library (Lume in my case), but it could load modules from the user's cwd. Something like this:

```js
async function cli() {
    const file = Deno.cwd() + './_config.js';
    const mod = await import(file);
    console.log(mod);
}
cli();
```

But now I can see that this is not available neither (`TypeError: Self-contained binaries don't support module loading`).
I hope dynamic imports are enabled soon or, at least, base64 data urls as you have suggested.

I guess that ATM, the only way to create executable binaries with Deno is using the `_config.js` file as the entry point. For example:

```js
import lume from "https://deno.land/x/lume/mod.js";
import cli from "https://deno.land/x/lume/cli.js";
  
const site = lume();

cli(Deno.args, site);
```
