### ISSUE TITLE
lume init: nano_jsx plugin listed instead of preact_jsx

### ISSUE THREAD

**Issue by jrson83** [lumeland/lume#281]
I just tried the v12.0.0 `lume init` command. Instead of `preact_jsx`, the `nano_jsx` plugin is listed.

![2022-10-04_03h49_01](https://user-images.githubusercontent.com/45284565/193717218-ab4288b8-a587-4e10-af21-51b589c9e3d6.png)

**Comment by oscarotero** [comment]
Mmm, that's imposible. jsx_preact is included here: https://github.com/lumeland/lume/blob/master/core/utils.ts#L17

**Comment by jrson83** [comment]
I checked again, this seems to be related to system. After cleaning deno cash, reinstalling lume the issue was gone.
