### ISSUE TITLE
Option to quieten console output

### ISSUE THREAD

**Issue by paulrobertlloyd** [lumeland/lume#282]
Sometimes it’s necessary to log output to the console. Sometimes however messages can get missed if lots of pages/images are generated, and there are multiple rows of 🔥 and 🎨!

It would be helpful to have an option to quieten the CLI output, and not display which items have been generated. Perhaps there’s an option where you could set the level (info, warning, error, etc.), which would give site authors more control of what’s shown here.

**Comment by oscarotero** [comment]
There's the --quiet flag for that. For example: `deno task build --quiet`

**Comment by paulrobertlloyd** [comment]
Ah, perfect! I don’t think this is mentioned anywhere in the documentation (certainly doesn’t appear in a search for ‘quiet’).

**Comment by oscarotero** [comment]
Yes, you're right. I'll uptate the docs
