### ISSUE TITLE
Relations plugin: Page rendering order not respected

### ISSUE THREAD

**Issue by paulrobertlloyd** [lumeland/lume#285]
I’m using the Relations plugin to create relationships between different pages on my site. The following types of relationship work:

* Generated page relation to another generated page
* Markdown page relation to another markdown page

However, I am not able to get relations working from Markdown pages to generated pages. Even with the rendering order adjusted, and outputting to the console conforming that generated pages are being created first, relationships in Markdown pages don’t work, and the plugin displays a not found error (e.g. `Page not found: type=trip id=t5JD1`).

Adding logging to the plugin, `pages` that are integrated through don’t show any generated pages on the site.

From a thread on Discord:

> It looks like a bug. I didn't take into account the different rendering orders when I've created the plugin.

**Comment by oscarotero** [comment]
@paulrobertlloyd I just refactored the relations plugin and it should work fine now.
You can test it after upgrading Lume to the latest development version with `deno task lume upgrade --dev`.
Please, let me know if it works fine.

**Comment by paulrobertlloyd** [comment]
@oscarotero It works *beautifully*! Thanks 😄

**Comment by oscarotero** [comment]
Awesome!
