### ISSUE TITLE
Terser processor/plugin

### ISSUE THREAD

**Issue by probins** [lumeland/lume#29]
Following the discussion in other issues, I've created a `_config.js` to run all js files through the Terser minifier:
````js
import lume from "https://deno.land/x/lume/mod.js";
import textLoader from "https://deno.land/x/lume/loaders/text.js";
import "https://cdn.jsdelivr.net/npm/terser/dist/bundle.min.js";

const site = lume({
  src: "lib",
  dest: "outlib",
  prettyUrls: false
});

site.loadAssets([".js"], textLoader);
site.process([".js"], processor);

async function processor (file) {
  let content = file.content;

  let opts = {
    module: true,
    compress: true,
    mangle: true
  };

  let output = await globalThis.Terser.minify(content, opts);

  file.content = output.code;
}

export default site;
````
I've not thorougly tested the output yet, but in principle it works well. It's not a 'static site' in the traditional sense, but is using Lume as a file processor to minify all files in `lib/` into `outlib/`. Like Denopack, it imports the browser version of Terser, which creates the Terser global. Specifying `globalThis` is not strictly necessary, but makes it clear where this Terser reference is coming from. 

So, I can either document this as an example of what can be done, or create a processor and/or plugin for general use. Another issue mentions passing options to plugins, and this would also be useful here, for example, whether to generate sourcemaps (the appropriate module would have to be imported to support this, of course).

**Comment by shadowtime2000** [comment]
@probins I don't think we have to import the UMD build and use the `globalThis`, Terser exports native browser ES modules [in `/main.js/`](https://cdn.jsdelivr.net/npm/terser@5.5.1/main.js).

**Comment by probins** [comment]
I just tried that, but it fails trying to `import MOZ_SourceMap from "source-map";`. Could get around that with an import map, but I STM it's simpler to use the browser version.

**Comment by shadowtime2000** [comment]
@probins You could file a bug report for that, but until that is fixed we could import from [skypack](https://www.skypack.dev/view/terser), I checked it and it maps the `source-map` dependency to an ES module link. It should work, haven't tested it.

**Comment by probins** [comment]
yeah, but you're into the same issues discussed with other plugins. Using skypack, jspm or esm.sh is essentially a workaround, and you can't rely on Node code remaining compatible with Deno. Browser code OTOH should be compatible, even if using globals is not ideal.

**Comment by oscarotero** [comment]
Ok. Do you like to create a PR with this plugin? Maybe modify the current bundler plugin to use Terser that seems like it produce better results for browsers.

**Comment by probins** [comment]
Just been looking at producing a sourcemap, and this is more complicated than simply setting an option. You first have to `import "https://cdn.jsdelivr.net/npm/source-map@0.7.3/dist/source-map.js";`. Then you need the filename, and set that in the options so the links between the two can be created:
````
  let filename = file.src.path + file.src.ext;

  let opts = {
    module: true,
    compress: true,
    mangle: true,
    sourceMap: {
      filename: filename,
      url: filename + '.map'
    }
  };
````
and then you have to output 2 files for each input file. How can this be done in the processor function?

**Comment by oscarotero** [comment]
To create a new page, just need to create the page and add it with `site.pages.push(page)`.
You can see an example in the `css` plugin: https://github.com/lumeland/lume/blob/master/plugins/css.js#L31

**Comment by probins** [comment]
yes, that works well. As the processor has access to the site data, I think the simplest way to pass in options is to create a `_data` file in the directory with appropriate settings. The global references can be hidden in the `deps` file, which would `export { minify, MOZ_SourceMap }`, which could then be imported into the plugin as normal import refs.

So the code looks something like:
````js
site.loadAssets([".js"], textLoader);
site.process([".js"], processor);

async function processor(file) {
  let content = file.content;
  let filename = file.src.path + file.src.ext;

  let opts = {
    module: true,
    compress: true,
    mangle: true
  };

  if (file.fullData.sourceMap) {
    opts.sourceMap = {
      filename: filename,
      url: filename + '.map'
    }
  }

  let output = await minify(content, opts);

  file.content = output.code;

  if (output.map) {
    let mapFile = file.duplicate();
    mapFile.content = output.map;
    mapFile.dest.ext = ".js.map";
    site.pages.push(mapFile);
  }
}
````
Then default is not to produce a sourcemap, and have a `_data` file with `sourceMap: true` in the directory if you want them. Other options could be set in a separate `options` object in `_data`.

**Comment by oscarotero** [comment]
`_data` files shouldn't be used for configuration. We have `_config.js` for that.

If you create a plugin, it can accept an object with configuration values. The basic structure for a plugin is:

```js
export default function (options = {}) {
  return (site) => {
    // The plugin code
  };
}
```

You can see `css` plugin for a real example.

Doing so, in `_config.js` file, you can use the plugin and configure it:

```js
site.use(bundler({ map: true }));
```

**Comment by probins** [comment]
but the processors don't have access to the plugin options - `css` only works because the processor is in the same file as the plugin. Is the aim not for processors and plugins to be independent?

**Comment by probins** [comment]
in any case, `_data` files are already used for configuration: `layout`, for example.

**Comment by oscarotero** [comment]
> Is the aim not for processors and plugins to be independent?

No strong opinions here. Sometimes is more practical to have everything in a single file. For example, [markdown plugin](https://github.com/lumeland/lume/blob/master/plugins/markdown.js) register the markdown template engine and create a filter to render markdown in any other template engine. Because we are using the same markdownIt instance, the filter is defined in the same file.

I have other filters like [url](https://github.com/lumeland/lume/blob/master/filters/url.js) that are in its own file, but it requires access to the `site` instance, so it returns a function that returns another function, so [on register it](https://github.com/lumeland/lume/blob/master/mod.js#L17) I can set the current site instance.

So my recomendation is that if you want to create the processor in a different file, don't export the processor directly but a function that return the processor. So you can set additional arguments (like options) needed for the processor. As an example:

```js
// processor.js
export default function (options) {
  return function (page, site) {
    //processor code
  }
}
```

```js
// plugin.js
import processor from "../processors/procesor.js";

export default function (options) {
  return function (site) {
    //Generate the processor with the custom options
    const fn = processor(options);

    //Register it
    site.process([".js"], fn);
  }
}
```

> in any case, _data files are already used for configuration: layout, for example.

IMHO they are different things. `layout`, `permalink` defines how a page must be rendered and saved. But sourcemaps is a global configuration, that even can depend on some environment. For example, you may want to generate sourcemaps only in dev mode.

**Comment by probins** [comment]
Thinking about this a bit more, it's not just the sourcemap option that needs to be defined, it's all the terser options. In principle, these could be different for each file, but if that's what the user wants then they can use Terser directly. In a process like this, you would want the same for all files. A plugin could use sensible defaults, which users could change if they wish. The user could set this in `site.data("terserOptions")` which the plugin would have access to. If `terserOptions.sourceMap` is set, then it could create the extra files. `site` is already used in the processor, so this wouldn't be adding to the closure.

**Comment by oscarotero** [comment]
I guess this is a matter of taste and Lume is flexible enough to allow to make all these things.
I prefer to have configurations options separated from data of website. Note also that you can store config data in the `site` instance, like other configuration values like `src`, `dest` or `prettyUrls`. For example:

```js
const site = lume({
  src: "src",
  dest: "dist",
  terser: {
    module: true,
    compress: true,
    mangle: true
  }
});

const terserOpts = site.options.terser;
```

**Comment by probins** [comment]
I would call it 'configuration data'. :-) Have to say I don't see the difference between using data to specify whether a file should have a sourcemap, and using data to specify whether a file should be minified, as in https://lumeland.github.io/advanced/processors/

As sourcemap support comes from another module/package, alternative ways to include them would be:
* have 2 separate plugins, one with and one without
* use `import()` to fetch the sourcemap code conditionally:
````js
 if (sourceMap === true) {
  await import('sourcemapfile');
  output sourcemap
}
````
I think I'll raise an issue on Terser to ask them to create an ES-module version for use in Deno as well as browser. This implies they would have to either bundle in the source map code or import it where needed.

**Comment by probins** [comment]
I've just been looking at [the code](https://github.com/lumeland/lume/blob/master/site.js#L357), and it looks like the processor function is passed the `site` instance `this`, so there's no need for the closure, and processors can be put in an independent module if wanted without any problem. I don't mind whether the Terser options are put in `site.extraData` or their own property.

One further question: is it possible to chain/pipe processors? It might be useful, for example, to take the output from `bundler` and run it through Terser.

**Comment by oscarotero** [comment]
> it looks like the processor function is passed the site instance this, so there's no need for the closure

Yes, I've added this in the last version. It could be needed if you want to pass options, but I see that you're not convinced about that.

> One further question: is it possible to chain/pipe processors?

Yes, you can register multiple processors for the same extension, so they are executed in that order.

**Comment by oscarotero** [comment]
@probins I am testing it Terser and in some cases it returns an empty content.
For example, this nunjucks file: https://github.com/lumeland/test/blob/master/nunjucks/to-javascript.js.njk outputs the following javascript code https://github.com/lumeland/test/blob/master/_expected/nunjucks/to-javascript.js.

But after run terser, the output file is empty. Any idea of why this happens?
Other files like these: https://github.com/lumeland/test/tree/master/scripts works fine.

A quick `console.log` in the plugin looks like is a bug with Terser library, not the plugin itself. This is the content passed to terser:

```js
const apiKey = {"bar":"foo","foo":"bar"};

const urls = [
  "/subdirectory/bar",
  "/subdirectory/foo",
  "./foo",
  "../foo",
  "https://example-site.com/subdirectory/foo",
  "https://example.com/bar/foo",
];
```
And this is the result (note that the code only has the sourceMappingURL reference.
```
{
  code: "\n//# sourceMappingURL=to-javascript.js.map",
  map: '{"version":3,"sources":[],"names":[],"mappings":"","file":"/nunjucks/to-javascript.js"}'
}
```

**Comment by probins** [comment]
Terser ignores code which doesn't do anything. If you add `console.log(apiKey, urls)` at the end, it will output minified code.

**Comment by oscarotero** [comment]
Ah, got it.
Thanks!

**Comment by oscarotero** [comment]
@probins Thinking more about this, I going to change a bit the options structure for this plugin, in order to make it consistent with other plugins. In `css` (that probably I'll rename it to `postcss`) we have two options: 

```js
site.use(css({
    postcssPlugins: [], //Array of plugins
    map: true
}))
```

I think plugins shouldn't use the exact options object passed to the library, because this closes the door to other options specific to Lume. So I think terser should be:

```js
site.use(terser({
    options: {
        module: true,
        compress: true,
        mangle: true,
    },
    map: true
}))
```

Doing so, we can expand this object with more values for lume (for example: other file extensions, transpile typescript, etc).

**Comment by probins** [comment]
ok, that makes sense. But the docs will have to be changed too. I think this should be mentioned in https://lumeland.github.io/plugins/about-plugins/

**Comment by probins** [comment]
also, I think `sourceMap` is the better name for the option rather than `map`. `map` can mean many things, whereas `sourceMap` is specific.

**Comment by oscarotero** [comment]
Ok, I'll rename it to `sourceMap` to both.
I want to make Lume very easy to learn and use, so consistency in the API is key here. I think it depends of the type of plugin. For example, plugins that runs a processor like postcss, terser or svgo will use similar options structure. Other plugins to add support for template engines (nunjuks, eta, pug) don't need the same options (like `sourceMap`) but they should be consistent with each other.
