### ISSUE TITLE
slugify_urls replace Chinese character with empty string.

### ISSUE THREAD

**Issue by wangbinyq** [lumeland/lume#291]
I have some tags is only chinese, and use with the simple-blog theme, it yield urls like `/archive/${tag}/`.
But the tag part is gone, so it generate same urls like `/archive//`, cause lume error.

What I want is keep the chinese character as it is or replace with something like pinyin.

@oscarotero if you want to fix this, I can make a pr.

Here is the testcase I added.
```
equals(slugify("img/中文.png"), "img/.png"); // pass
quals(slugify("img/中文.png"), "img/中文.png"); // fail
```

**Comment by oscarotero** [comment]
The `slugify_urls` default options has the `alphanumeric` option as true (https://github.com/lumeland/lume/blob/master/plugins/slugify_urls.ts#L32), so it removes all non-alphanumeric characters. Try to set it to `false`.
There's also an option to replace specific characters.

But any improvement is welcome. Maybe chinese characters could be converted to pinyin if `alphanumeric` is enabled.

**Comment by wangbinyq** [comment]
If I add the funtional that tranform chinese or cjk characters to latin characters, may i need to add an option like `enablecjk`?

**Comment by oscarotero** [comment]
I think it should work out of the box. If we can detect cjk characteres and the `alphanumeric` option enabled it should make the replacement.
The current replacement implementation is this: https://github.com/lumeland/lume/blob/master/plugins/slugify_urls.ts#L90 but I guess it doesn't support cjk characters.

**Comment by wangbinyq** [comment]
OK, I will try to add cjk support.
