### ISSUE TITLE
TLS handshake error when running lume

### ISSUE THREAD

**Issue by johan-steffens** [lumeland/lume#298]
Hi there,

I have lume running in a CI/CD pipeline build. We're using it to generate internal static websites.

The issue I'm getting is that when I run the `lume` command to build the static website, I get an error: 
```
...
Loading config file file:///builds/strategic-projects/internal/infographic-ui/_config.ts
Download https://deno.land/x/lume@v1.12.1/plugins/code_highlight.ts
Download https://deno.land/x/lume@v1.12.1/plugins/sass.ts
Download https://deno.land/x/lume@v1.12.1/plugins/svgo.ts
Download https://deno.land/x/lume@v1.12.1/deps/highlight.ts
Download https://deno.land/x/lume@v1.12.1/deps/denosass.ts
Download https://deno.land/x/lume@v1.12.1/deps/svgo.ts
Download https://denopkg.dev/gl/binyamin/deno-sass@v1.55.0/mod.ts
TypeError: error sending request for url (https://denopkg.dev/gl/binyamin/deno-sass@v1.55.0/mod.ts): error trying to connect: tls handshake eof
    at https://deno.land/x/lume@v1.12.1/deps/denosass.ts:1:25
    at (https://deno.land/x/lume@v1.12.1/deps/denosass.ts:1:25)
    at async createSite (https://deno.land/x/lume@v1.12.1/cli/run.ts:51:17)
    at async build (https://deno.land/x/lume@v1.12.1/cli/build.ts:28:16)
    at async Command.execute (https://deno.land/x/cliffy@v0.25.2/command/command.ts:1463:7)
    at async (https://deno.land/x/lume@v1.12.1/cli.ts:147:3)
```

My _config.ts file is fairly stock standard:
```
import lume from "lume/mod.ts";
import sass from "lume/plugins/sass.ts";
import code_highlight from "lume/plugins/code_highlight.ts";
import svgo from "lume/plugins/svgo.ts";

const site = lume();

site.use(sass());
site.use(code_highlight());
site.use(svgo());
site.copy("assets/imgs");
site.copy("assets/lottieAnimations");

export default site;
```

Why would all the other depencies resolve successfully, but the one from denopkg.dev wouldn't?

**Comment by johan-steffens** [comment]
Is there a way to specify root CA certificates if I'm behind a VPN?

**Comment by oscarotero** [comment]
Is this a recurring error? I had this kind of specific problems that were fixed simply by re-running the CI.

**Comment by johan-steffens** [comment]
@oscarotero thanks for responding so quickly. Yes, this is happening every time unfortunately. 

I had some certificate issues with Deno as well, but resolved them by setting up a certs directory with root certs for our intranet. Is there a way to do the same thing with Lume?

**Comment by oscarotero** [comment]
Lume does nothing different to Deno, so if Deno works in your intranet, Lume should also work.
If the problem is just for this dependency, perhaps it's related with https://denopkg.dev/ (the cdn used to import sass).
Could you create a file that imports `https://denopkg.dev/gl/binyamin/deno-sass@v1.55.0/mod.ts` and try to run it?
