### ISSUE TITLE
Modification of the translation system

### ISSUE THREAD

**Issue by AugustinMauroy** [lumeland/lume#301]
# how it is now

https://lume.land/plugins/multilanguage/

# how it could be

> This change would make the work easier for the translators.

What I propose is simply that we have a `json` that contains the list of languages ex:`En, Fr, Es, De` and the date format. This file would be the config of the translation. Then to translate a content file you have to create a file adding the language ex:`about.en.md` => `about.fr.md`.

# Crowdin

with this relatively simple system we could add a crowdin integration.

**Comment by oscarotero** [comment]
I like the idea of Lume detecting that two files are different language versions of the same page (like `about.en.md` and `about.fr.md`). I will work on that. Thanks!
