### ISSUE TITLE
Deno.bundle() removed in Deno 1.7.0

### ISSUE THREAD

**Issue by probins** [lumeland/lume#31]
See https://deno.land/manual@v1.7.0/typescript/runtime for replacement

I think this is an improvement, but I'm still working through the implications. `compile()` and `transpileOnly()`, as discussed in another issue, have also disappeared.

I'd suggest making a new version and specifying it needs 1.7.0+ to work.

**Comment by oscarotero** [comment]
Yes, I need to take a look to the new API and will release a new version soon.
Thanks for the warning

**Comment by oscarotero** [comment]
Looks like `Deno.emit()` (like the old `Deno.bundle()`) cannot load a js/ts file passing the content, and resolve the imported modules automatically. If `sources` option is used, all imported scripts must be there. This makes this plugin a bit useless for lume. [question](https://discord.com/channels/684898665143206084/689420767620104201/801548227429138522)

**Comment by oscarotero** [comment]
New version `v0.13.0` released.

**Comment by probins** [comment]
ok, than this can be closed. I see they fixed the bug you reported already - though it'll be a while before it's effective, as the next release is in March.

**Comment by oscarotero** [comment]
Yeah, the problem is that the main entry point may be a nunjuks file that generate a js file, or something like that. This is why I want to provide the content of the entry point and Deno.emit() resolve the other imports (something similar to what the postcss plugin does).

**Comment by probins** [comment]
ok, I see what you mean. With rollup, you can pipe the entry point contents from stdin. Don't know whether that works with `deno bundle`.
