### ISSUE TITLE
nunjucks template-inheritance/block not working as intended

### ISSUE THREAD

**Issue by angelside** [lumeland/lume#314]
### Version

1.12.1

### Platform

Arch Linux

### What steps will reproduce the bug?

```shell
~ git clone https://github.com/angelside/lume-block-test.git
~ deno task serve
```

### What do you see instead?

```
Caused by Template render error: (/home/angelside/code/static/lume-block-test/index.njk)
  Error: no super block available for "breadcrumb"
```

### Additional information

Block and super structure not working with default frontmatter layout definition. 

But, it's working if replacing frontmatter with classic nunjucks extends _(Which is not the desired method, I like to use single data.yml file for layout)_.

```
---
layout: layout.njk
---
```

```
{% extends "_includes/layout.njk" %}
```

Docs: https://mozilla.github.io/nunjucks/templating.html#template-inheritance
Minimal example: https://github.com/angelside/lume-block-test

-------

layout.njk

```njk
<div class="breadcrumb">
    {% block breadcrumb %}
        block in base
    {% endblock %}
<div>
```

index.njk

```njk
{% block breadcrumb %}
    {{ super() }}
    block in index
{% endblock %}
```

**Comment by oscarotero** [comment]
I have to dig into the nunjucks internals code and see if it's possible to include the blocks defined in one template into another.

**Comment by oscarotero** [comment]
I have been trying to implement this but looks like it's not possible because it breaks other things.
A solution for your use case is creating a preprocessor to add the `extends` directive. For example:

```ts
site.preprocess([".njk"], (page) => {
  // Add the extends directive with the layout
  page.data.content = `{% extends "${page.data.layout}" %}\n${page.data.content}`;

  // Delete the layout from the frontmatter
  delete page.data.layout;
});
```
