### ISSUE TITLE
Live reload: Detect if https:// or http:// before deciding to use `ws://` or `wss://`

### ISSUE THREAD

**Issue by onionhammer** [lumeland/lume#316]
### Enter your suggestions in details:

For dev environments like codespaces, in-browser, github will generate an HTTPS URL or developing "in the cloud", but it will block "ws://"

(index):75 Mixed Content: The page at 'https://someurl-3000.preview.app.github.dev/' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://someurl-3000.preview.app.github.dev/'. This request has been blocked; this endpoint must be available over WSS.

**Comment by oscarotero** [comment]
Good catch. I'll work on that.
I guess it's only detecting the protocol in the client side javascript (here: https://github.com/lumeland/lume/blob/master/middlewares/reload_client.js#L10) right?

Something like:

```js
const protocol = document.location.protocol === "https:" ? "wss://" : "ws://";
```

**Comment by onionhammer** [comment]
Yeah that was my thought
