### ISSUE TITLE
Pagefind v0.10.3 Windows Release

### ISSUE THREAD

**Issue by bglw** [lumeland/lume#331]
Sorry for the hiccup in [latest build of Pagefind is not available on Windows](https://github.com/lumeland/lume/commit/2ef678fa68c9ebec0d99cf13a6d3e3b4932d22f0)! 

Windows binary is fixed again in [Pagefind v0.10.3](https://github.com/CloudCannon/pagefind/releases/tag/v0.10.3) 🙂

**Comment by oscarotero** [comment]
Nice! Thank you!
