### ISSUE TITLE
Fresh lume site fails: "could not find npm package markdown-it-attrs"

### ISSUE THREAD

**Issue by Sam-Spencer** [lumeland/lume#340]
### Version

1.14.2

### Platform

macOS

### What steps will reproduce the bug?

 1. Install the latest stable version of node (18.12.1)
 2. Create an empty directory
 3. Follow the instructions to get started with Luke **exactly** as they are provided in the docs
 4. Use a typescript config
 5. Do not add any plugins
 6. Create your first page: `index.md` (again, as stated in the docs)
 7. Run `deno task serve` (as per the docs)
 8. The following error prints in the terminal:

> error: Could not find npm package 'markdown-it-attrs' matching 4.1.6. Try retrieving the latest npm package information by running with --reload

### How often does it reproduce? Is there a required condition?

Every time

### What is the expected behavior?

Should be able to initialize a new lime site by following the provided instructions

### What do you see instead?

There is an ambiguous npm package error:

> error: Could not find npm package 'markdown-it-attrs' matching 4.1.6. Try retrieving the latest npm package information by running with --reload

Interestingly, that specific version of that specific npm package *does* exist and was published 10 days ago (at time of writing).

**Comment by oscarotero** [comment]
Hi, @Sam-Spencer 
This is a bug from Deno, related to how they cache the NPM packages. (See https://github.com/denoland/deno/issues/16901)

There are two possible solutions:

- Purge the Deno's cache folder (run `deno info` to get the cache path)
- Or run `echo "import 'lume/cli.ts'" | deno run --unstable -A --reload -` (The same command of `deno task lume` but with the `--reload` flag). This will refresh the Deno's cache.

**Comment by officialrajdeepsingh** [comment]
The following demo` echo "import 'lume/cli.ts'" | deno run --unstable -A --reload -`, then I run the following command, it will be fine for me.

```bash
 deno cache --reload ./_config.ts 
```

**Comment by oscarotero** [comment]
This was fixed in Deno. So I'm closing this.
