### ISSUE TITLE
Breadcrumb plugin

### ISSUE THREAD

**Issue by oscarotero** [lumeland/lume#353]
### Enter your suggestions in details:

Related: https://github.com/lumeland/lume/discussions/351

A helper (like `search` or `paginate`) to build breadcrumbs following the filesystem structure.

**Comment by oscarotero** [comment]
Working on the `nav` plugin here: https://github.com/lumeland/experimental-plugins/tree/main/nav

It's a new global object with the functions `nav.menu()` and `nav.breadcrumb()`.

It can be imported as following:

```js
import lume from "lume/mod.ts";
import nav from "https://raw.githubusercontent.com/lumeland/experimental-plugins/main/nav/mod.ts";

const site = lume();
site.use(nav());

export default site;
```

cc @simplerethink

**Comment by simplerethink** [comment]
@oscarotero Thank you! I tested the breadcrumb feature on a 4-level nested page and it's working!

Could `false` options be passed to exclude the first and last items? 

For example, I don't want the Home page and current page itself showing in the breadcrumb.

**Comment by oscarotero** [comment]
You can include conditions in the loop. For example:

```njk
<ul style="display: flex; list-style: none; gap: 1em; padding: 0;">
  {% for item in nav.breadcrumb(url) %}
    {% if item.url != "/" and item.url != url %}
      <li><a href="{{ item.url }}">{{ item.title }}</a></li>
    {% endif %}
  {% endfor %}
</ul>
```

**Comment by simplerethink** [comment]
Yes, true, I was considering that. Thanks for creating this plugin!

**Comment by oscarotero** [comment]
No problem.
I think it's better to have the full array of pages and you decide how to use it, instead of adding too much options to the breadcrumb function.
