### ISSUE TITLE
Access rendered content from outer pages

### ISSUE THREAD

**Issue by valpackett** [lumeland/lume#357]
### Enter your suggestions in details:

Inside the page layout, `{{ content }}` is the rendered content, already processed with all the `templateEngine`s.

Within `search.pages` results, there is only entirely unprocessed content, and one has to basically redo the entire pipeline manually. And I can't even get the `njk` filter—maybe due to `{% import %}` stuff in the content—to work in that context.

It would be great if the rendered content was cached and available for access in pages with higher `renderOrder`.

**Comment by oscarotero** [comment]
Hi 👋 

> And I can't even get the njk filter—maybe due to {% import %} stuff in the content—to work in that context.

I don't understand this. The njk filter should be available always, for example:

```
{{ content | njk }}
```

**Comment by valpackett** [comment]
I mean, using it just quietly ruins the output in a weird way, even cutting off a lot of things after the usage tag.

Templates:

```html
{% macro preview(post) -%}
	<li class="showcase-card h-entry">
		<a href="{{ post.url }}" class="showcase-spread u-url u-uid">
			<h3 class="p-name">{{ post.title }}</h3>
		</a>
		<p class="preview-meta">
			<time datetime="{{ post.date | date }}" class="dt-published">{{ post.date | date('HUMAN_DATE') }}</time>
			✦ {{ post.content | md | striptags | reading_time }} min read
		</p>
		<p class="p-summary">{{ post.desc }} ✦&nbsp;<a href="{{ post.url }}">read more&nbsp;→</a></p>
	</li>
{%- endmacro %}
```

```html
{% import "blog.njk" as blog %}

<h1>Blog</h1>

<ul class="showcase-grid">
	{%- for post in search.pages("blog=true", "date=desc") | data %}
	{{ blog.preview(post) }}
	{%- endfor %}
</ul>
```

Output:

```html
<ul class="showcase-grid">
	<li class="showcase-card h-entry">
		<a href="/blog/ergonice/" class="showcase-spread u-url u-uid">
			<h3 class="p-name">Yet another keyboard post, or, introducing ErgoNICE</h3>
		</a>
		<p class="preview-meta">
			<time datetime="2023-01-09" class="dt-published">January 9th, 2023</time>
			✦ 20 min read
		</p>
		<p class="p-summary">I made a custom split mechanical keyboard! Because it's me, this involved things like contributing to a PCB design tool and discovering a ridiculously optimized way to read a keyboard matrix. ✦&nbsp;<a href="/blog/ergonice/">read more&nbsp;→</a></p>
	</li>
	<li class="showcase-card h-entry">
		<a href="/blog/pixelbook/" class="showcase-spread u-url u-uid">
			<h3 class="p-name">FreeBSD and custom firmware on the Google Pixelbook</h3>
		</a>
		<p class="preview-meta">
			<time datetime="2019-10-05" class="dt-published">October 5th, 2019</time>
			✦ 15 min read
		</p>
		<p class="p-summary">A search for a new thin-and-light laptop, a journey through the Chromebook firmware trust architecture, some FreeBSD kernel development, and finally, something about actually customizing open source firmware. ✦&nbsp;<a href="/blog/pixelbook/">read more&nbsp;→</a></p>
	</li>
.....
```

Now if we change to `{{ post.content | njk | md | striptags | reading_time }}` or `{{ post.content | njk(post) | md | striptags | reading_time }}` or `{{ post.content | njk }}` or `{{ post.content | njk(post) }}`:

```html
<ul class="showcase-grid">
	<li class="showcase-card h-entry">
		<a href="/blog/ergonice/" class="showcase-spread u-url u-uid">
			<h3 class="p-name">Yet another keyboard post, or, introducing ErgoNICE</h3>
		</a>
		<p class="preview-meta">
			<time datetime="2023-01-09" class="dt-published">January 9th, 2023</time>
			✦ 
	</p></li><li class="showcase-card h-entry">
		<a href="/blog/pixelbook/" class="showcase-spread u-url u-uid">
			<h3 class="p-name">FreeBSD and custom firmware on the Google Pixelbook</h3>
		</a>
		<p class="preview-meta">
			<time datetime="2019-10-05" class="dt-published">October 5th, 2019</time>
			✦ 
	</p></li><li class="showcase-card h-entry">
```

The full source repo for the site is [here](https://codeberg.org/valpackett/val.packett.cool).

**Comment by oscarotero** [comment]
@valpackett Ok, I think it's because the `njk` filter is asyncronous. So the `for in` loop  must be changed to `asyncEach`. But that doesn't work either because according to the [nunjucks documentation for macros](https://mozilla.github.io/nunjucks/templating.html#macro): 

> Important note: If you are using the asynchronous API, please be aware that you cannot do anything asynchronous inside macros. This is because macros are called like normal functions. In the future we may have a way to call a function asynchronously. If you do this now, the behavior is undefined.

So the only solution is cache the rendered content anywhere. Currently, the only way to save the rendered content before apply the layouts is using a javascript layout for that.
For example:

1. Edit your posts to use the layout `layouts/blog.tmpl.js`.
2. This new javascript layout would work as a "middleware" with the following code:
```js
// Use the nunjucks layout
export const layout = "layouts/blog.njk";

export default function ({ page, content }) {
  // Save the content in a variable inside the page
  page.data.mainContent = content;
  
  // Return the content to be rendered by the nunjucks template
  return content;
}
```
3. Change `renderOrder` value for the `/blog/index.njk` page to be rendered after the posts. For example `1`. This ensure that all posts have the `mainContent` value variable defined before list them in the index page.
4. Now you can use the `post.mainContent` in your macros.

It's a bit hacky solution but it does the job.

**Comment by valpackett** [comment]
Ohh, that's so clever! I hadn't thought to use a js layout for that. Thanks!!

**Comment by oscarotero** [comment]
Yeah, it's not designed for that, but it's a nice way to edit the page data dynamically from the layouts :)

BTW, I just saw your site and it's great. Do you mind if I include it in the [Showcase section](https://lume.land/showcase/)?

**Comment by valpackett** [comment]
oh please do include it :3

**Comment by oscarotero** [comment]
Done!
Thanks!
