### ISSUE TITLE
Improve choosing plugins/dependencies in init script 

### ISSUE THREAD

**Issue by tristanisham** [lumeland/lume#358]
### Enter your suggestions in details:

Hello all,

The most important interaction a new user has with a tool like Lume is its init script. A comprehendible, quick, and instructive experience can mean the difference between a lifelong user and a permanent dismissal. My first time experience using Lume was not the former. 

I’d like to update the initialization process to make creating a new Lume site simple. To do this, it’s like to add:

- A dynamic TUI where users can choose as many plugins as they want by arrowing through a list and toggling any with “space”
- A check to determine if any plug-in dependencies are missing and a prompt to automatically add and order them. 
- Instructions, informing the user to run `deno task serve` to initialize their project. 
- General error message cleanup and the addition of suggestions on how to fix errors when they occur. 

I hope you find these suggestions well, and hopefully can expect a pull request in the coming weeks.

**Comment by oscarotero** [comment]
Hey!
Thanks for your suggestions. Yes, an improved initialization is always welcome!
I'm ussing cliffy.io to build the command line interface, and it has a prompt functionality (https://cliffy.io/docs@v0.25.7/prompt) which is a bit better to the default prompt provided by Deno, so maybe it would be nice to use it.

Other instructions like `deno task serve` are good ideas. Feel free to create pull request, they are welcome! I just ask you to don't include all things in the same PR. One PR per feature is much better.

Thanks!

**Comment by tristanisham** [comment]
Awesome! Thanks for the quick response. I'll start working on adding some stuff soon! I appreciate you mentioning Cliffy. I hadn't heard of it before. I'll reply to this with some of the models I have and submit a PR when it's ready.

**Comment by tristanisham** [comment]
#374 Is the pull request for this issue.

**Comment by tristanisham** [comment]
- [x] A dynamic TUI where users can choose as many plugins as they want by arrowing through a list and toggling any with “space”
- [ ]A check to determine if any plug-in dependencies are missing and a prompt to automatically add and order them.
- [ ]Instructions, informing the user to run deno task serve to initialize their project.
- [ ] General error message cleanup and the addition of suggestions on how to fix errors when they occur.
