### ISSUE TITLE
Could not init with jsx_preact plugin

### ISSUE THREAD

**Issue by guigui64** [lumeland/lume#359]
### Version

latest

### Platform

Linux

### What steps will reproduce the bug?

`deno run -Ar https://deno.land/x/lume/init.ts`, choose `y` for Typescript and select the following plugins: `jsx_preact mdx tailwindcss postcss`

### How often does it reproduce? Is there a required condition?

Always

### What do you see instead?

```
Lume configuration file saved: _config.ts
error: Uncaught (in promise) ReferenceError: __DENO_NODE_GLOBAL_THIS_1673619784__ is not defined
    at file:///home/guillaume/.cache/deno/npm/registry.npmjs.org/preact/10.11.3/dist/preact.mjs:1:18
```

**Comment by oscarotero** [comment]
It looks like a Deno issue on loading npm packages dynamically.
It will be fixed in the next version. Thanks!
