### ISSUE TITLE
Sitemap plugin should be able to set an accurate `lastmod` value for each page

### ISSUE THREAD

**Issue by dnk8n** [lumeland/lume#369]
### Enter your suggestions in details:

E.g.

 - If Headless CMS is used, then data can come from published date
 - If a route is used, then the file's metadata can be used
 - Any other configurable logic, ie pass a custom function to sitemap

**Comment by oscarotero** [comment]
Yeah, that's a good idea.
Let me think about it. Probably I will come with a solution in the next version.

**Comment by oscarotero** [comment]
Added the `lastmod` option that accepts a string with the key of the variable (by default "date") or a custom function that must return a `Date` instance.
