### ISSUE TITLE
Suggestion: use Github releases

### ISSUE THREAD

**Issue by probins** [lumeland/lume#37]
Main advantage: I get a Github notification when there's a new release, but I don't get one if commits/tags are pushed to the repo. Doesn't have to say very much; can just refer to the Changelog.

**Comment by oscarotero** [comment]
Yes, good idea!
In fact, I'm doing something similar for other projects ([Example](https://github.com/oscarotero/Embed/releases/tag/v4.3.0)).
This is easy with github actions.
