### ISSUE TITLE
UnoCSS Plugin

### ISSUE THREAD

**Issue by tuhanayim** [lumeland/lume#371]
### Enter your suggestions in details:

UnoCSS<sup>[[1]]</sup> plugin for Lume.

[1]: https://github.com/unocss/unocss

**Comment by oscarotero** [comment]
Thanks! I'll take a look.

**Comment by danklammer** [comment]
With Windi CSS being sunsetted. UnoCSS is a great replacement.

> While Windi CSS is no longer actively maintained (as of March 2023), you may consider UnoCSS as a "spiritual successor" of Windi CSS. 
>
> __(https://unocss.dev/guide/why)__


I am a big fan of the Lume's Windi CSS plugin, specifically the **inserted <style> tag for each page** option. I'm hoping this can be ported over.

Loving Lume so far — big fan of the simple but super flexible approach to a modern SSG. Thanks for all the great work on it!

**Comment by kwaa** [comment]
Work in progress here: https://github.com/lumeland/experimental-plugins/pull/22

**Comment by oscarotero** [comment]
I've included into Lume v2 (replacing windi css).
