### ISSUE TITLE
Expose Markdown-It disable function

### ISSUE THREAD

**Issue by bglw** [lumeland/lume#375]
### Enter your suggestions in details:

👋 

I'm looking to run `.disable('code')` on the default markdown-it instance, but digging through the way its options are exposed I can't see any sanctioned way to do so — only to pass options to the initial constructor, and set the rules. 

For now I'm digging deep to run:
```js
site.formats.get(".md").engines[0].engine.disable("code");
```

But it would be great to have a builtin way to achieve this 🙂

_(Also of note: [This rule is now actually disabled by default in 11ty](https://github.com/11ty/eleventy/issues/2438).)_

**Comment by oscarotero** [comment]
Hi!
Yeah, it makes sense. I just added a new hook to modify directly the markdownIt instance. So in your `_config.ts` file you can do:

```ts
site.hooks.markdownIt((engine) => engine.disable("code"));
```

It will be available when Lume 1.15.3 is released. Probably it should be disabled by default but I prefer to wait to Lume 2.0.
