### ISSUE TITLE
Named import for plugins and `lume`

### ISSUE THREAD

**Issue by scarf005** [lumeland/lume#377]
## Summary

i find [named import syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#named_import) easier to read and autocomplete. we could create mod.ts for `plugins/` and 
import everything from `lume/mod.ts` to make import easier.

### Before
```ts
import lume from "lume/mod.ts";
import jsx from "lume/plugins/jsx_preact.ts";
import mdx from "lume/plugins/mdx.ts";
```

### After

```ts
import { lume, jsx, mdx } from "lume/mod.ts";
```
or
```ts
import lume from "lume/mod.ts";
import { jsx, mdx } from "lume/plugins/mod.ts";
```

## Other

I'm interested in opening a PR if this idea is approved.

**Comment by oscarotero** [comment]
I had something like this in the past but as the number of plugins was growing, it was more obvious it was a bad idea.

The main problem is Deno will download not only all plugins (even if you don't import them) but also their dependecies. Some are light dependencies but others are more heavy with hundred of subdependencies, like tailwind, imagick, windi_css, etc.

So it's better to import only the modules you need.

**Comment by scarf005** [comment]
i see. thanks for the analysis!
