### ISSUE TITLE
Allow to configure the root directory of the server

### ISSUE THREAD

**Issue by boeckMt** [lumeland/lume#382]
### Enter your suggestions in details:

It would be nice if a user could set the server `root` in the [configuration Server options](https://lume.land/docs/configuration/config-file/#server-options) to serve static files that shouldn't be copied on every build.

That could be done somewhere here https://github.com/lumeland/lume/blob/73200d261f3bda81c04fb820d71e118aaca8060a/cli/build.ts#L97

---

Another nice option would be to allow swapping the server instance e.g.

```ts
...
import Server from "https:/deno.land/x/lume/core/server.ts";

const server = new Server({
  port: 8000,
  root: `${Deno.cwd()}/dist`,
});

server.start();


const site = lume({
  src: "./src",
  dest: "./dist/build",
  emptyDest: false,
  server: server
});

```

---

My use case is that I have many images that are in another directory and I don't want to copy them (like [Copy static files](https://lume.land/docs/configuration/copy-static-files/)) to the dist folder to prevent duplication and unnecessary work.

As a workaround I tried using a second server and [redirects](https://lume.land/docs/core/server/#redirects) but unfortunately that don't work.

```ts
const server = new Server({
  port: 3001,
  root: `${Deno.cwd()}/dist`,
});

server.addEventListener("start", (event) => {
  console.log(`Listening on http://localhost:${server.options.port}`);
});

server.start();

const site = lume({
  src: "./src",
  dest: "./dist/build",
  emptyDest: false,
  location: new URL("https://activations.zki.dlr.de"),
  server: {
    port: 3000,
    middlewares: [
      redirects: {
        "http://localhost:3000/portaldata/": "http://localhost:3001/portaldata/",
      }
    ],
  },
});

```

**Comment by oscarotero** [comment]
Probably this could be addressed creating a new a middleware. Something like this:

```ts
const server = new Server({
  port: 3000,
  root: `${Deno.cwd()}/dist`,
});

server.use(staticFolder({
  root: "/path/to/another/folder"
});
```

**Comment by oscarotero** [comment]
@boeckMt I have created [this middleware](https://github.com/lumeland/experimental-plugins/blob/main/static_folder/mod.ts). You can use it as following:

```js
import lume from "lume/mod.ts";
import staticFolder from "https://raw.githubusercontent.com/lumeland/experimental-plugins/main/static_folder/mod.ts";

const site = lume({
  server: {
      middlewares: [
        staticFolder({
          root: Deno.cwd() + "/path/the/folder",
        })
      ]
    },
});

export default site;
```

Let me know if it works for you.

**Comment by boeckMt** [comment]
@oscarotero tanks for the fast response and creation of this middleware!
It works perfectly :)

---
I'm currently trying to migrate a site from [metalsmith](https://github.com/metalsmith/metalsmith) which, by the way, works very well.

**Comment by oscarotero** [comment]
Great! I think this middleware may be useful to other users, so I'll move it to the official Lume repository.
