### ISSUE TITLE
Request: include .md source files in output, similar to .js sourcemaps.

### ISSUE THREAD

**Issue by nupanick** [lumeland/lume#402]
### Enter your suggestions in details:

I think it's cool how you can publish a website in a way that preserves the human-readable source, and I think it would make sense for Lume to allow a similar feature. I tried this:

```ts
const site = lume({
    src: '.',
});

site.copy(['.md']);
```

but it appears that once Lume has decided a file is being statically copied to the output, there's no way to also render it as html. Is there a workaround for this, or would it require a new config flag?

**Comment by oscarotero** [comment]
The same file cannot be copied and rendered. A way to achieve that is generating a page with the markdown code for each post. For example:

```js
// ./markdown.tmpl.js

export default function * ({ search }) {
  for (const page of search.pages("type=post")) {
    yield {
      url: page.data.url + "source.md",
      content: page.data.content
    }
  }
}
```

This file generate a new page for each post, adding `source.md` at the end of the url. For example, the url `/posts/first-post/` will have the `/posts/first-post/source.md` page.
