### ISSUE TITLE
Incorrect typing for `jsx_preact.ts`

### ISSUE THREAD

**Issue by indifferentghost** [lumeland/lume#403]
### Version

v1.16.0

### Platform

Linux/Firefox

### What steps will reproduce the bug?

Utilize `renderAsync` it always says it returns a string when we can clearly see that's not true.

```ts
  renderSync(content: unknown, data: Data = {}): string {
    const element = typeof content === "function"
      ? content(data, this.helpers)
      : content;

    if (element && typeof element === "object") {
      element.toString = () => renderToString(element);
    }

    return element;
  }
  ```

### What is the expected behavior?

Typescript inference should be enough here.

### What do you see instead?

hard typed as a string

### Additional Details?

https://github.com/lumeland/lume/blame/master/plugins/jsx_preact.ts#L66-L76

**Comment by oscarotero** [comment]
Yeah, good catch. `renderSync` must return a string or an object with the `toString()` function defined (which is the case here): https://github.com/lumeland/lume/blob/master/core/renderer.ts#L310

I'll fix it.
