### ISSUE TITLE
'alternates' variable from multilanguage plugin is not available in nunjucks anymore 

### ISSUE THREAD

**Issue by anick3** [lumeland/lume#404]
### Version

v1.16.1

### Platform

Linux

### What steps will reproduce the bug?

{{ alternates | dump }}

### How often does it reproduce? Is there a required condition?

always

### What is the expected behavior?

it should dump kv pairs of language codes to pages

### What do you see instead?

nothing

### Additional information

It worked until a few days ago. I suspect this commit introduced the issue:

https://github.com/lumeland/lume/commit/d692062dc237a1fa415cb1eafd4f4fe5bbbebf95

**Comment by oscarotero** [comment]
Yes, sorry. The breaking changes of the `multilanguage` plugin introduced in 1.16.0 includes also a change in the `alternates` object.

Now it's just an array of the page data objects. So you can do:

```njk
{% for alt in alternates %}
<a href="{{ alt.url }}" hreflang="{{ alt.lang }}">{{ alt.title }}</a>
{% endfor %}
```

**Comment by anick3** [comment]
Sorry to bother you again, but this does not work for me. There's nothing in the alternates object, it seems.

**Comment by anick3** [comment]
I love lume and I am very grateful for your work

Thank you very much for your hard work!

Lume enable(d|s) me to make a good website (-- it's still a work-in-progress, though), and eased up the process by just the right margin.

Lume hits the perfect compromise between keeping control and simplification of chores -- and that's exactly, what makes it so great!

I just want to say, that I love lume!

Thank you so very, very much!

**Comment by oscarotero** [comment]
Hey @anick3
Thank you very much for your kind words! This comment made my day :)
If you want to share your opinion about Lume on any social network (twitter, mastodon, youtube, a blog, etc), please, let me know so I can include it in the testimonials section at lume.land. :)
