### ISSUE TITLE
sourceMappingURL does not work for js

### ISSUE THREAD

**Issue by kuboon** [lumeland/lume#407]
### Platform

chrome & safari

### What steps will reproduce the bug?

Use sourcemap plugin with esbuild

### What is the expected behavior?

browser gets `js.map` file.

### What do you see instead?

js.map file was not loaded.

### Additional information

`/*# ~~ */` notation is for css. https://github.com/lumeland/lume/blob/6f656a17b3ddc83c7acd603d87af3fc155b1a4bb/plugins/source_maps.ts#L62

For Javascript it should be
`//#`

spec is here.
https://github.com/source-map/source-map-spec/blob/8b3e5f094d1943772725898e1104ab0dba5ddff2/source-map-rev3.md?plain=1#L219

**Comment by oscarotero** [comment]
I can't believe I didn't see this before (I'm using Firefox so it always worked fine to me)! Thanks so much!
I just fixed it. You can test it after upgrading to the latest development version of Lume (`deno task lume upgrade --dev`).

**Comment by kuboon** [comment]
@oscarotero Thank you. It worked.
