### ISSUE TITLE
1.17.1 issue in static copy Generation 

### ISSUE THREAD

**Issue by mskian** [lumeland/lume#419]
i have `.well-known` folder for my android app deep link verification

`1.16.xx` having no issues but latest version did not copy the that folder to `_site` folder

My repo conf File -https://github.com/mskian/copied-kavithai/blob/main/_config.ts

i tested the latest version locally
but not pull it to my repo due to this issue

**Comment by oscarotero** [comment]
Fixed in 1.17.2
