### ISSUE TITLE
Latest update breaks Cloudflare Pages deployment

### ISSUE THREAD

**Issue by mlanza** [lumeland/lume#420]
### Version

1.17.3

### Platform

Cloudflare Pages

### What steps will reproduce the bug?

I have a build settings for my Cloudflare Pages which has worked for ages:

```sh
curl -fsSL https://deno.land/x/install/install.sh | sh && /opt/buildhome/.deno/bin/deno run -A https://deno.land/x/lume/ci.ts --location=https://main.xxxxxxxxx.pages.dev
```

This ceased working recently.

### How often does it reproduce? Is there a required condition?

Every time I deploy.

### What is the expected behavior?

The deployment build succeeds as usual.

### What do you see instead?

18:26:32.632 | Cloning repository...
-- | --
18:26:34.826 | From https://github.com/xxxxx/xxxxxxx
18:26:34.826 | * branch            5a7852dc46b362121ba00c91e8262c6c962683ec -> FETCH_HEAD
18:26:34.827 |  
18:26:35.158 | HEAD is now at 5a7852d undo
18:26:35.159 |  
18:26:35.272 |  
18:26:35.302 | Success: Finished cloning repository files
18:26:35.909 | Installing dependencies
18:26:35.917 | Python version set to 2.7
18:26:39.242 | v12.18.0 is already installed.
18:26:40.424 | Now using node v12.18.0 (npm v6.14.4)
18:26:40.601 | Started restoring cached build plugins
18:26:40.612 | Finished restoring cached build plugins
18:26:40.988 | Attempting ruby version 2.7.1, read from environment
18:26:42.519 | Using /opt/buildhome/.rvm/gems/ruby-2.7.1
18:26:43.492 | Using PHP version 5.6
18:26:43.590 | 5.2.5 is already installed.
18:26:43.607 | Using Swift version 5.2.5
18:26:43.608 | Installing Hugo 0.54.0
18:26:44.294 | Hugo Static Site Generator v0.54.0-B1A82C61A/extended linux/amd64 BuildDate: 2019-02-01T10:04:38Z
18:26:44.297 | Started restoring cached go cache
18:26:44.311 | Finished restoring cached go cache
18:26:44.399 | go version go1.14.4 linux/amd64
18:26:44.412 | go version go1.14.4 linux/amd64
18:26:44.415 | Installing missing commands
18:26:44.416 | Verify run directory
18:26:44.416 | Executing user command: curl -fsSL https://deno.land/x/install/install.sh \| sh && /opt/buildhome/.deno/bin/deno run -A https://deno.land/x/lume/ci.ts --location=https://main.xxxxxxxxx.pages.dev
18:26:46.222 | #=#=#                                                                          ##O#- #                                                                                                                                                    0.0% ###########                                                               16.4% ####################                                                      28.8% ##################################                                        48.0% ##############################################                            64.0% #########################################################                 79.5% ####################################################################      95.7% ######################################################################## 100.0%
18:26:46.244 | Archive:  /opt/buildhome/.deno/bin/deno.zip
18:26:47.192 | inflating: /opt/buildhome/.deno/bin/deno
18:26:47.207 | Deno was installed successfully to /opt/buildhome/.deno/bin/deno
18:26:47.209 | Run 'deno --help' to get started
18:26:47.209 |  
18:26:47.209 | Stuck? Join our Discord https://discord.gg/deno
18:26:47.250 | Download https://deno.land/x/lume/ci.ts
18:26:47.746 | Warning Implicitly using latest version (v1.17.3) for https://deno.land/x/lume/ci.ts
18:26:47.747 | Download https://deno.land/x/lume@v1.17.3/ci.ts
18:26:48.156 | error: Module not found "https://deno.land/x/lume/ci.ts".
18:26:48.164 | Failed: build command exited with code: 1
18:26:48.920 | Failed: error occurred while running build command

### Additional information

I changed the build line to refer to the prior version explicitly and it works.

```sh
curl -fsSL https://deno.land/x/install/install.sh | sh && /opt/buildhome/.deno/bin/deno run -A https://deno.land/x/lume@v1.12.0/ci.ts --location=https://main.xxxxx.pages.dev
```
Also, I upgraded lume on my local machine and ran `lume --serve` and that fails.

```sh
TypeError: Could not find npm package 'date-fns' matching 2.30.0. Try retrieving the latest npm package information by running with --reload
    at async createSite (https://deno.land/x/lume@v1.12.0/cli/run.ts:51:17)
    at async build (https://deno.land/x/lume@v1.12.0/cli/build.ts:28:16)
    at async Command.execute (https://deno.land/x/cliffy@v0.25.1/command/command.ts:1433:7)
    at async (https://deno.land/x/lume@v1.12.0/cli.ts:147:3)
```
<img width="1440" alt="Screenshot 2023-05-11 at 7 17 59 PM" src="https://github.com/lumeland/lume/assets/39192/72373596-9c7d-48f2-b00a-e61f1cb3c57c">

I have a feeling its all related.

**Comment by oscarotero** [comment]
Hi. Yes, the file `ci.ts` was removed in v1.17.0 because Lume relies on Deno task to be executed, and ci.ts is no needed (It was keept for several versions for backward compatibility since this change).

You have to edit the build command to 
```
curl -fsSL https://deno.land/x/install/install.sh | sh && /opt/buildhome/.deno/bin/deno task build
```
Make sure you have a deno.json file with the build task. It shoud be something like:
```
{
  "tasks": {
    "lume": "echo \"import 'lume/cli.ts'\" | deno run --unstable -A -",
    "build": "deno task lume",
    "serve": "deno task lume -s"
  },
  "imports": {
    "lume/": "https://deno.land/x/lume@v1.17.3/"
  }
}
```

**Comment by mlanza** [comment]
That helped with things locally.  Here's what I had.
```json
{
  "importMap": "import_map.json",
  "tasks": {
    "build": "deno task lume",
    "serve": "deno task lume -s",
    "lume": "deno eval \"import 'lume/task.ts'\" --"
  }
}

```

It didn't fix the build on Cloudflare though.  I works as long as I leave the modified bash line in place.

**Comment by oscarotero** [comment]
`lume/task.ts` file was removed too in previous versions. The correct `lume` task is
```
echo "import 'lume/cli.ts'" | deno run --unstable -A -
```

**Comment by mlanza** [comment]
This makes no reference to the cloudflare destination site...

```sh
curl -fsSL https://deno.land/x/install/install.sh | sh && /opt/buildhome/.deno/bin/deno task build
```

It doesn't work.  This does:

```sh
curl -fsSL https://deno.land/x/install/install.sh | sh && /opt/buildhome/.deno/bin/deno run -A https://deno.land/x/lume@v1.12.0/ci.ts --location=https://main.xxxxx.pages.dev
```

Obviously, xxxx out name.

**Comment by oscarotero** [comment]
It should work if you have the import_map.json file updated with the latest version of Lume.

For example, [this project](https://github.com/lumeland/base-blog) works fine in Cloudflare (https://base-blog.pages.dev/)

**Comment by mlanza** [comment]
I do.  Still looking.
```json
{
  "imports": {
    "lume/": "https://deno.land/x/lume@v1.17.3/"
  }
}

```

**Comment by mlanza** [comment]
```
20:34:35.398 | Cloning repository...
-- | --
20:34:37.499 | From https://github.com/xxx/xxxx
20:34:37.500 | * branch            f99947067234702621aed71ea28dca5663f8de43 -> FETCH_HEAD
20:34:37.500 |  
20:34:37.857 | HEAD is now at f999470 update json
20:34:37.858 |  
20:34:37.978 |  
20:34:38.010 | Success: Finished cloning repository files
20:34:38.745 | Installing dependencies
20:34:38.754 | Python version set to 2.7
20:34:42.275 | v12.18.0 is already installed.
20:34:43.521 | Now using node v12.18.0 (npm v6.14.4)
20:34:43.694 | Started restoring cached build plugins
20:34:43.707 | Finished restoring cached build plugins
20:34:44.143 | Attempting ruby version 2.7.1, read from environment
20:34:45.675 | Using /opt/buildhome/.rvm/gems/ruby-2.7.1
20:34:46.704 | Using PHP version 5.6
20:34:46.805 | 5.2.5 is already installed.
20:34:46.827 | Using Swift version 5.2.5
20:34:46.828 | Installing Hugo 0.54.0
20:34:47.518 | Hugo Static Site Generator v0.54.0-B1A82C61A/extended linux/amd64 BuildDate: 2019-02-01T10:04:38Z
20:34:47.521 | Started restoring cached go cache
20:34:47.538 | Finished restoring cached go cache
20:34:47.627 | go version go1.14.4 linux/amd64
20:34:47.642 | go version go1.14.4 linux/amd64
20:34:47.646 | Installing missing commands
20:34:47.647 | Verify run directory
20:34:47.647 | Executing user command: curl -fsSL https://deno.land/x/install/install.sh \| sh && /opt/buildhome/.deno/bin/deno task build
20:34:48.750 | #=#=#                                                                          ##O#- #                                                                                                                                                    0.0% ##############################                                            42.8% ######################################################################## 100.0%
20:34:48.760 | Archive:  /opt/buildhome/.deno/bin/deno.zip
20:34:49.719 | inflating: /opt/buildhome/.deno/bin/deno
20:34:49.734 | Deno was installed successfully to /opt/buildhome/.deno/bin/deno
20:34:49.736 | Run 'deno --help' to get started
20:34:49.736 |  
20:34:49.737 | Stuck? Join our Discord https://discord.gg/deno
20:34:49.748 | Task build deno task lume
20:34:49.758 | Task lume echo "import 'lume/cli.ts'" \| deno run --unstable -A --
20:34:49.767 | error: the following required arguments were not provided:
20:34:49.768 | [SCRIPT_ARG]...
20:34:49.768 |  
20:34:49.768 | Usage: deno run --unstable --allow-all [SCRIPT_ARG]...
20:34:49.768 |  
20:34:49.768 | For more information, try '--help'.
20:34:49.768 |  
20:34:49.776 | Failed: build command exited with code: 1
20:34:50.542 | Failed: error occurred while running build command
```

**Comment by mlanza** [comment]
Got it.  Really appreciate the guidance and quick support. 

And Lume is great!  Simple!

**Comment by oscarotero** [comment]
No problem. Glad to help.

Looking at your logs, the error is in the command to run lume. You had `lume echo "import 'lume/cli.ts'" | deno run --unstable -A --` but it's `lume echo "import 'lume/cli.ts'" | deno run --unstable -A -` (note the single dash at the end).

I guess you have fixed it :)

**Comment by mlanza** [comment]
Yeah, when I looked at what was there before I didn't understand why the trailing single dash.  I thought it was a typo.  Then I figured it wasn't.
