### ISSUE TITLE
How can i use plugins like search and nav with Preact?

### ISSUE THREAD

**Issue by simon-lund** [lumeland/lume#422]
### Enter your suggestions in details:

I don't know if I missed it in the docs, but I don't know how to import a plugin to a Preact componemt.
If it's not in the docs, maybe you can add it to the individual plugin page for Preact/JSX?

**Comment by simon-lund** [comment]
Ah, the plugins can be imported like data.

**Comment by oscarotero** [comment]
Yes, `search` and `nav` are available like any other data variable.

```tsx
export default function ({ search, nav }) {
  const pages = search.pages("type=post");
  return pages.map((page) => <li>{ page.data.title }</li>);
}
```
