### ISSUE TITLE
How to use tailwind plugins  (plugins of tailwind, not the lume tailwind plugin)

### ISSUE THREAD

**Issue by max-l** [lumeland/lume#439]
### Enter your suggestions in details:

Tailwind has plugins, for adding certain features :  https://tailwindcss.com/docs/typography-plugin

Lume has a Tailwind plugin, 

To sort out confusion (there are two levels of plugins involved) :  my question is about "plugins of tailwind", how to get them to work, using the (lume) tailwind plugin

My conf looks like this: 

```
import tailwindcss from "lume/plugins/tailwindcss.ts";
import postcss from "lume/plugins/postcss.ts";

site
  .ignore("README.md")
  .ignore("app")
  .use(esbuild({
    extensions: [".jsx"],
    options: {
        jsxDev: ! isProduction,
        minify: isProduction
    }
  }))
  .use(tailwindcss({
    extensions: [".html", ".jsx"]
  })).use(postcss())
  .copy("img")
;

```

And my styles.css file looks like this : 
```
@tailwind base;
@tailwind components;
@tailwind utilities;
@tailwind typography;
```

The problem: the last line (@tailwind typography;) does nothing, while everything else works fine. 
It seems that adding a tailwind plugin (plugin of tailwind) is different than adding "build in" packages.

The doc shows how plugins are installed and configured  : 
   https://tailwindcss.com/docs/plugins

But I'm not able to translate the recipe for lume/deno

Note, that If I add junk in the style.css : 

```
@tailwind base;
@tailwind components;
@tailwind utilities;
@junk123 moreJunkABC;
```

There is no error in the console if I build or serve, things "work", without complaints, it seems as the postcss or lume is silencing the error.

**Comment by oscarotero** [comment]
I didn't try to install plugin in Tailwind, but this should work:

```js
import typography from "npm:@tailwindcss/typography";

site.use(tailwindcss({
  extensions: [".html", ".jsx"],
  options: {
    plugins: [typography]
  }
}))
```

**Comment by max-l** [comment]
It works like a charm !

Thanks !
