### ISSUE TITLE
lume build fails

### ISSUE THREAD

**Issue by Seb-Leb** [lumeland/lume#442]
### Version

v1.18.0

### Platform

wsl

### What steps will reproduce the bug?

running `deno task lume --serve`

I suddently get this without any upgrades or changes on our site:

`✘ [ERROR] No such file or directory (os error 2): readfile 'data:text/javascript;base64,ZXhwb3J0IGRlZmF1bHQgT2JqZWN0LmFzc2lnbg==' [plugin lumeLoader]

deno:https://esm.sh/v127/prop-types@15.8.1/denonext/prop-types.development.mjs:2:22:
  2 │ import * as __0$ from "data:text/javascript;base64,ZXhwb3J0IGRlZmF1bHQgT2JqZWN0LmFzc2lnbg==";
    ╵                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`

with the following config:
#### _config.ts
`import lume from "lume/mod.ts";
import esbuild from "lume/plugins/esbuild.ts";
import sourceMaps from "lume/plugins/source_maps.ts";

import tailwindcss from "lume/plugins/tailwindcss.ts";
import postcss from "lume/plugins/postcss.ts";
import typography from "npm:@tailwindcss/typography@0.5.9";

const port = 3000

async function pathAnhilator(request, next) {

    const [prefix, path] = request.url.split(`:${port}`)

    if(path.match("/proteins.*") || path.match("/downloads.*")) {
        const url = new URL(`${prefix}:${port}/`)
        return await next(new Request(url.href, {...request}))
    }
    else {
        return await next(request)
    }
}

const isProduction = Deno.env.get("PRODUCTION") === "True"

const apiHost = () => {

    const hostInEnv = Deno.env.get("openprot_api_host")
    if(hostInEnv) {
        return hostInEnv
    }

    const currentDir = Deno.cwd()

    if(currentDir.startsWith("/openprot-test/")) {
        return "https://api-test.openprot.org"
    }
    return "https://api.openprot.org"
}

const site = lume({
    server: {
        middlewares: [pathAnhilator],
        port
    }
})

site
  .ignore("README.md")
  .ignore("app")
  .use(esbuild({
    extensions: [".jsx"],
    options: {
        jsxDev: ! isProduction,
        minify: isProduction
    }
  }))
  .use(sourceMaps({

  })).use(tailwindcss({
    extensions: [".html", ".jsx"],
    options: {
        plugins: [typography]
    }
  })).use(postcss())
  .copy("img")
;

site.data("static_path_prefix", isProduction ? "/static" : "")
site.data("openprot_api_host", apiHost())

export default site;
`
#### deno.json
`{
  "importMap": "./import_map.json",
  "lock": false,
  "tasks": {
    "lume": "echo \"import 'lume/cli.ts'\" | deno run --unstable -A -",
    "build": "export PRODUCTION=True && deno task lume",
    "serve": "deno task lume -s",
    "esm:add": "deno run -A https://esm.sh/v124 add",
    "esm:update": "deno run -A https://esm.sh/v124 update",
    "esm:remove": "deno run -A https://esm.sh/v124 remove"
  },
  "compilerOptions": {
    "jsx": "react-jsx",
    "jsxImportSource": "https://esm.sh/v124/react@18.2.0",
    "lib": [
      "dom",
      "dom.iterable",
      "dom.asynciterable",
      "deno.ns"
    ]
  }
}
`
#### import_map.json
`{
  "imports": {
    "lume/": "https://deno.land/x/lume@v1.18.0/",
    "react-table": "https://esm.sh/@tanstack/react-table@8.9.1",
    "@remix-run/router": "https://esm.sh/v124/@remix-run/router@1.6.2",
    "d3-axis": "https://esm.sh/v124/d3-axis@3.0.0",
    "d3-array": "https://esm.sh/v124/d3-array@3.2.4",
    "d3-scale": "https://esm.sh/v124/d3-scale@4.0.2",
    "d3-selection": "https://esm.sh/v124/d3-selection@3.0.0",
    "d3-zoom": "https://esm.sh/v124/d3-zoom@3.0.0",
    "d3-shape": "https://esm.sh/v124/d3-shape@3.0.0",
    "d3-color": "https://esm.sh/v124/d3-color@3.0.0",
    "d3-interpolate": "https://esm.sh/v124/d3-interpolate@3.0.0",
    "d3-scale-chromatic": "https://esm.sh/v124/d3-scale-chromatic@3.0.0",
    "radash": "https://esm.sh/v124/radash@10.8.1",
    "react-dom": "https://esm.sh/v124/*react-dom@18.2.0",
    "react-dom/": "https://esm.sh/v124/*react-dom@18.2.0/",
    "react-dom/client": "https://esm.sh/v124/*react-dom@18.2.0/client",
    "react-router-dom": "https://esm.sh/v124/*react-router-dom@6.11.2",
    "react-router": "https://esm.sh/v124/react-router@6.11.2",
    "react": "https://esm.sh/v124/react@18.2.0",
    "react/": "https://esm.sh/v124/react@18.2.0/",
    "scheduler": "https://esm.sh/v124/scheduler@0.23.0"
  },
  "scopes": {}
}
`

### How often does it reproduce? Is there a required condition?

it suddently always fails to build.

### What is the expected behavior?

the site is usually built and served locally

### What do you see instead?

I see the following ouput:

`Task lume echo "import 'lume/cli.ts'" | deno run --unstable -A - "--serve"
Loading config file file:///mnt/c/Users/18194/Documents/altorf/python-lib/openprot_pipeline/site/_config.ts

✘ [ERROR] No such file or directory (os error 2): readfile 'data:text/javascript;base64,ZXhwb3J0IGRlZmF1bHQgT2JqZWN0LmFzc2lnbg==' [plugin lumeLoader]

    deno:https://esm.sh/v127/prop-types@15.8.1/denonext/prop-types.development.mjs:2:22:
      2 │ import * as __0$ from "data:text/javascript;base64,ZXhwb3J0IGRlZmF1bHQgT2JqZWN0LmFzc2lnbg==";
        ╵                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Error: Error processing page
- page: /main.jsx
- processor:
    at (https://deno.land/x/lume@v1.18.0/core/processors.ts:63:21)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async concurrent (https://deno.land/x/lume@v1.18.0/core/utils.ts:163:3)
    at async Processors.run (https://deno.land/x/lume@v1.18.0/core/processors.ts:53:9)
    at async Site.#buildPages (https://deno.land/x/lume@v1.18.0/core/site.ts:664:5)
    at async Site.build (https://deno.land/x/lume@v1.18.0/core/site.ts:530:9)
    at async build (https://deno.land/x/lume@v1.18.0/cli/build.ts:41:3)
    at async Command.execute (https://deno.land/x/cliffy@v0.25.7/command/command.ts:1794:7)
    at async Command.parseCommand (https://deno.land/x/cliffy@v0.25.7/command/command.ts:1639:14)

Caused by Error: Build failed with 1 error:
deno:https://esm.sh/v127/prop-types@15.8.1/denonext/prop-types.development.mjs:2:22: ERROR: [plugin: lumeLoader] No such file or directory (os error 2): readfile 'data:text/javascript;base64,ZXhwb3J0IGRlZmF1bHQgT2JqZWN0LmFzc2lnbg=='
    at failureErrorWithLog (https://deno.land/x/esbuild@v0.18.6/mod.js:1612:15)
    at (https://deno.land/x/esbuild@v0.18.6/mod.js:1024:25)
    at runOnEndCallbacks (https://deno.land/x/esbuild@v0.18.6/mod.js:1447:45)
    at buildResponseToResult (https://deno.land/x/esbuild@v0.18.6/mod.js:1022:7)
    at (https://deno.land/x/esbuild@v0.18.6/mod.js:1051:16)
    at responseCallbacks.<computed> (https://deno.land/x/esbuild@v0.18.6/mod.js:673:9)
    at handleIncomingPacket (https://deno.land/x/esbuild@v0.18.6/mod.js:728:9)
    at readFromStdout (https://deno.land/x/esbuild@v0.18.6/mod.js:649:7)
    at (https://deno.land/x/esbuild@v0.18.6/mod.js:1898:11)
    at eventLoopTick (ext:core/01_core.js:183:11)`

**Comment by oscarotero** [comment]
Okay, I just added support for `data:` urls to the esbuild plugin.
Can you test it before release a new version? You can upgrade Lume to the latest development version with `deno task lume upgrade --dev`.

**Comment by max-l** [comment]
I have the same problem, 

and I can confirm that the fix works.

That was fast  fix / feature, thanks !

**Comment by Seb-Leb** [comment]
Excellent! thank you!

**Comment by oscarotero** [comment]
Great, thanks for confirm. 
New version v1.18.1 released.

**Comment by lucab** [comment]
@oscarotero I've just started using `lume`, and I think I've hit a similar problem with a `node:process` import going through the esbuild plugin.

In my case, it seems to be coming from https://esm.sh/v128/async-validator@4.2.5/denonext/async-validator.mjs which is being pulled through some transitive dependencies.

The output says:
```
Caused by Error: Build failed with 1 error:
deno:https://esm.sh/v128/async-validator@4.2.5/denonext/async-validator.mjs:2:23:
ERROR: [plugin: lumeLoader] No such file or directory (os error 2): readfile 'node:process'
```

**Comment by oscarotero** [comment]
@lucab esbuild plugin is intended to bundle client side javascript. `node:process` specifier is a Node native module that never will work on browser.
I you want to polyfill this module, you can use the import map. For example:

```json
{
  "imports": {
    "node:process": "https://deno.land/std@0.177.0/node/process.ts"
  }
}
```

**Comment by lucab** [comment]
@oscarotero thanks for the hint, indeed I completely overlooked that detail.

Starting from your observation , it seems that the esbuild plugin is requesting the Deno version of the module to esm.sh (see the `denonext` in the URL above).
In turn, that causes esm.sh to add a `deno:process` polyfill to the code. Requesting the `es2015` version instead does inject https://esm.sh/v128/node_process.js as the polyfill for browsers. 
See the difference between the following:
 * `denonext` -> https://esm.sh/v128/async-validator@4.2.5/denonext/async-validator.mjs
 * `es2015` -> https://esm.sh/v128/async-validator@4.2.5/es2015/async-validator.mjs (the import URL is buggy though)

**Comment by oscarotero** [comment]
@lucab interesting!

The `fetch()` function in Deno set the User Agent header to Deno, so I guess this is detected by esm.sh to return code adapted to Deno. I tried to change the user agent to a browser and it returns the es2015 version:

```js
const path = "https://esm.sh/async-validator@4.2.5";
const response = await fetch(path, {
  headers: {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/115.0",
  }
});
const content = await response.text();

console.log(content)
```

So I probably the Lume's esbuild plugin should include this header automatically.
