### ISSUE TITLE
postcss: index.min.css -> index.min

### ISSUE THREAD

**Issue by iacore** [lumeland/lume#448]
### Version

1.18.1

### Platform

Linux

### What steps will reproduce the bug?

1. Clone https://git.envs.net/iacore/debug-deno-min-css
2. Run `deno task build`

### How often does it reproduce? Is there a required condition?

always

### What is the expected behavior?

index.min.css -> _site/index.min.css

### What do you see instead?

index.min.css -> _site/index.min

```
❯ deno task build
Task build deno task lume
Task lume echo "import 'lume/cli.ts'" | deno run --unstable -A -
Loading config file file:///home/user/computing/debug/lume-min-css/_config.ts


🔥 /index.min /index.min.css


🍾 Site built into ./_site
  1 files generated in 0.04 seconds
```

**Comment by oscarotero** [comment]
Hi! Thanks for reporting this.

I just fixed it and will be available in v1.18.2.
