### ISSUE TITLE
Make `url` settable and replace `permalink` with it

### ISSUE THREAD

**Issue by valtlai** [lumeland/lume#46]
Pages already have the `url` property, so if we could make it settable, the `permalink` property could be removed in favor of it. I think it would be nice if the getter (currently `url`) and setter (currently `permalink`) had a same name. Also that’s how `date` works.

This would be a breaking change, but we’re at `v0.x` so maybe it doesn’t matter. However, we can always make `permalink` an alias of `url` and possibly remove that later.

**Comment by oscarotero** [comment]
I like it! Yes, initially there was only the permalink variable, and then I created the url for convenience. But you're right that they are almost the same and `url` is more clear about its purpose. 
I'm working on it.

**Comment by oscarotero** [comment]
I close this because it's already implemented. It will be available in the next version
