### ISSUE TITLE
copying "Hello World" example renders garbled text

### ISSUE THREAD

**Issue by steventrouble** [lumeland/lume#463]
### Version

1.18.3

### Platform

Windows

### What steps will reproduce the bug?

```
deno run -Ar https://deno.land/x/lume/init.ts
> _config.ts
> Maybe Later
// Important: Copy-pasted from terminal
echo "hello world" > index.md
deno task serve
```

### How often does it reproduce? Is there a required condition?

Every time I try it.

### What is the expected behavior?

```
<!DOCTYPE html>
<p>Hello world</p>
```

### What do you see instead?

```
<!DOCTYPE html>
<p>��H�e�l�l�o� �w�o�r�l�d�
�
�</p>
```

### Additional information

Running latest Deno built from source with `cargo install deno --locked`

**The issue is that Windows Powershell's echo command outputs text in UTF-16, and Lume reads it as UTF-8.**

**Comment by oscarotero** [comment]
Thanks for reporting this bug, but I'm not sure if this can be fixed easily. Lume uses [`Deno.readTextFile`](https://deno.land/api@v1.35.3?s=Deno.readTextFile) function to read the text content and, indeed the function description makes it clear that the file is read as UTF-8 decoded string.

I guess this is a very edge case, but l'm leaving this open just in case there's a quick and easy solution for that.

**Comment by steventrouble** [comment]
One easy fix could be suggesting the user create the file manually rather than using echo. Or, having the template start off with the hello world file already added.

**Comment by oscarotero** [comment]
Okay, I just changed the quick start tutorial with your suggestion. It will be available in the next version.
thanks!
