### ISSUE TITLE
Layout doesn't applied to `.js` urls

### ISSUE THREAD

**Issue by cawa-93** [lumeland/lume#474]
### Version

v1.18.4

### Platform

Windows 11

### What steps will reproduce the bug?

Create a generator for `.js` file using layout

```js
// app.tmpl.js

const url = './app.js'
const layout = 'layout.njk'
```

```njk
<!-- _includes/layout.njk -->
console.log('app.js')
```
And run `serve`. 

### How often does it reproduce? Is there a required condition?
The only problem is when you try to generate the `.js` file. If you generate the usual html (`export const url = './app/'`), the layout is applied as expected.

### What is the expected behavior?

single `app.js` file with `console.log('app.js')` should be generated

### What do you see instead?

```node
⚠️ Warning Skipped page /app.js (file content is empty)
```
Although obviously the file should not be empty,

**Comment by oscarotero** [comment]
Layouts are used only for `.html` pages.
Any page that generates a non-html page (js, css, jpg, etc) doesn't not use the layout. 
See [regular pages vs asset pages](https://lume.land/docs/core/concepts/#page-files).
