### ISSUE TITLE
Add a `.serve()` function to the site value

### ISSUE THREAD

**Issue by leighmcculloch** [lumeland/lume#476]
### Enter your suggestions in details:

Lume allows using it as a library only without the CLI. For my workflows I've found that much easier to reason about than using the CLI. For example, in my sites instead of a `_config.ts`, I have a script for building, `build.ts` and that script creates the site, attaches plugins, etc, and then finally calls `site.build()`.

```ts
import lume from 'lume/mod.ts';
const site = lume();
// ...
await site.build();
```

Then, for a serve variant, I have another file `serve.ts` that contains:
```ts
import './build.ts';
import { serveDir } from 'std/http/file_server.ts';
Deno.serve((req: Request) => {
  return serveDir(req, {
    fsRoot: "./_site",
  });
});
```

Given that lume provides the simple ability to build with `site.build()`, it would be convenient if the serve functionality of the CLI was moved from the CLI into the site value. So that it would be possible to simply call `site.serve()`.

Related discussion at https://discord.com/channels/794537085641818124/1145219225342976090.

**Comment by oscarotero** [comment]
Lume local server uses the [`Server` class](https://lume.land/docs/core/server/) with some middlewares to handle 404 responses, prevent browser cache, watch the file changes and live reload.

Including all this logic inside the `Site` class would make the class more complicated, with too much responsabilities.

You can instantiate the Server class and add the [following middlewares](https://lume.land/docs/core/server/) to recreate the same server provided by Lume.
