### ISSUE TITLE
Requesting enhance better solution for JSX children

### ISSUE THREAD

**Issue by ngdangtu-vn** [lumeland/lume#479]
### Enter your suggestions in details:

Both JSX & Preact plugins pass children params as DivElement, the idea is great 'cause dev could avoid doing manually. This is, however, not very flexible as it could break layout. I have a different approach of using function. The idea is passing a function call `insertContent()` that allows dev to set the right `Element` type, attributes, and even do prepend or append to the `content`.

```JSX
export default ({ insertContent }) => (
   {insertContent(<><p>Para 1</p><p>Para 2</p><>, ['article', {className: 'awesome'}), <p>Para N</p>)}
)
```

I'm doing it PR, if you don't mind.

**Comment by oscarotero** [comment]
In addition to `children`, there's the `content` variable with the HTML string:

```js
export default function ({ content }) {
  const children = <div class="my-content" dangerouslySetInnerHTML: {{ __html: content }} />
}
```

**Comment by ngdangtu-vn** [comment]
So I shouldn't do the `insertContent()` right? I kinda want to avoid having `dangerouslySetInnerHTML` for the end side. What if I have more `dangerouslySetInnerHTML` that actually need my attention more than `children`. I like the children property idea, I just don't feel comfortable with how fixation it

**Comment by ngdangtu-vn** [comment]
I think a different template in this case would be better than try to solve this problem.
