### ISSUE TITLE
Resolved URL has space in it

### ISSUE THREAD

**Issue by iacore** [lumeland/lume#481]
### Version

v1.18.5

### Platform

Linux

### What steps will reproduce the bug?

- Create new lume project
- Import plugin https://lume.land/plugins/resolve_urls/
- Create a file named `a b.md` (the filename has a space)
- Put `[example link](./a b.md)` in `index.md`
- Run `deno task serve`
- `curl http://localhost:3000/ | grep "a b"`

### How often does it reproduce? Is there a required condition?

100%

### What is the expected behavior?

```
<a href="/a%20b/">example link</a>
```

### What do you see instead?
```
<a href="/a b/">example link</a>
```

### Additional information

Firefox seems to be able to use href with spaces correctly. 

However, Nu Validator says that it is incorrect.

> Illegal character in path segment: space is not allowed.

![example image](https://github.com/lumeland/lume/assets/74560659/341ad6e3-b514-463f-98c4-ef0023aceef2)

**Comment by oscarotero** [comment]
I just fixed it and will be available in the next release.
Thanks!
