### ISSUE TITLE
.tmpl.ts does not reload included parts from import

### ISSUE THREAD

**Issue by boeckMt** [lumeland/lume#483]
### Version

- Deno@1.36.4 
- lume@v1.18.5

### Platform

Windows

### What steps will reproduce the bug?

When using plain ES modules (.tmpl.ts) as templates, reloading in the browser does not work for imported sub-templates.

e.g. 

```ts
// default.tmpl.ts

import { PageData } from "lume/core.ts";
import headTmpl from "../_components/head.tmpl.ts";
import bodyTmpl from "../_components/body.tmpl.ts";

export default (data: PageData) => {
  return /*html*/ `<html>
  ${headTmpl(data)}
  <body>
    ${bodyTmpl(data)}
  </body>
</html>`;
};

```

May related to: https://github.com/lumeland/lume/issues/178

### What do you see instead?

No changes will be shown if anything is changed in a subtemplate.

### Additional information

A current workaround might be to define all subtemplates in the same file. However, this prevents reuse in some situations.

e.g. 

```ts
// default.tmpl.ts
import { PageData } from "lume/core.ts";

const bodyTmpl = (data: PageData) => {
  return /*html*/ `<div>
    ${data.content}
   </div>`;
};

const headTmpl = (data: PageData) => {
  return /*html*/ `<head>
  <title>${data.title}</title>
  ...
</head>`;
};

export default (data: PageData) => {
  return /*html*/ `<html>
  ${headTmpl(data)}
  <body>
    ${bodyTmpl(data)}
  </body>
</html>`;
};

```

**Comment by oscarotero** [comment]
This is not a bug, but is how Deno works.
Any module loaded with `import ...` is cached by Deno and there's no way to refresh the module after any change.

This is why Lume exposes the `comp` variable:

```js
// default.tmpl.ts

import { PageData } from "lume/core.ts";

export default (data: PageData) => {
  const { comp } = data;

  return /*html*/ `<html>
  ${comp.head(data)}
  <body>
    ${comp.body(data)}
  </body>
</html>`;
};
```

More info: https://lume.land/docs/core/components/

**Comment by boeckMt** [comment]
Thanks for the information, at first it did not work because I used the same extension for the components as for the templates. 

- _components/head.tmpl.ts";
- _components/body.tmpl.ts";

now using 
- _components/head.ts";
- _components/body.ts";

It works like a charm.
