### ISSUE TITLE
Page with `url: false` not retured by `search.pages`

### ISSUE THREAD

**Issue by hannobraun** [lumeland/lume#486]
### Version

1.18.5

### Platform

Linux

### What steps will reproduce the bug?

1. Search for pages by tag in a JSX template (e.g. `search.pages("update")`).
2. Confirm that this works as expected.
3. Set `url: false` for those pages.

### How often does it reproduce? Is there a required condition?

Reproduces every time.

### What is the expected behavior?

I expect the behavior of `search.pages` to not change, as [the documentation states](https://lume.land/docs/creating-pages/urls/#setting-url-to-false) that "\[the page\] is still visible by other pages, for example, in paginations"

### What do you see instead?

The same call to `search.pages` that previously worked as expected now returns an empty array.

### Additional information

I did some digging around the code. The `Searcher` [gets a reference to `this.pages` in the `Site` constructor](https://github.com/lumeland/lume/blob/b4b12ce0c11ff64d52703566463575bf6e40f415/core/site.ts#L190), then `this.pages` is [later modified to remove pages with `url === false`](https://github.com/lumeland/lume/blob/b4b12ce0c11ff64d52703566463575bf6e40f415/core/site.ts#L642-L648). This looks like it would also modify the array that the `Searcher` got. Maybe the `Searcher` needs a copy of that array, not a reference to it? (Sorry if this analysis is wrong. My JavaScript skills are very rusty, and my TypeScript skills very new.)

**Comment by oscarotero** [comment]
I think the issue is in the documentation. Probably this is the old behavior and at some point this was changed but the documentation wasn't updated.

Reimplement this behavior is complicated, because `search.pages()` only returns HTML pages, Lume consider a page is HTML if the url contains the `.html` extension (no matter if it's normal URL `/foo.html` or pretty URL `/foo/index.html`). But pages with url as `false` cannot be considered HTML pages, even if they weren't removed from the `site.pages` array.

Why do you need this?

**Comment by hannobraun** [comment]
Ah, that makes sense. Thank you for the explanation!

> Why do you need this? Maybe I can help you with a workaround.

I'm [building a page](https://www.hannobraun.com/) with article-like pages that I want to keep updated. For each update, I want to display some information (date of the update, link to the page that was updated, and a short description of the update) in several places:

- A "latest updates" list on the home page (already implemented)
- An RSS feed (currently working on it)
- A changelog on each updated page

Storing these updates as pages works well, as that gives me access via `search.pages` where I need it (except in the feed; might open another issue about that later :smile:) and allows me to store all relevant information as Markdown + front matter.

However, I don't actually want a page per update, hence `url: false`. My current workaround is to have a template for these updates that displays a 404-like page instead.

This works well enough, but it's not exactly pretty. And a "page" is the wrong abstraction to use anyway, since I don't actually want a page. I did it because I'm not aware of any better abstractions within Lume. But now that I think about it, I can just store those updates as regular files, load them using Deno APIs, and circumvent Lume completely. That's probably the better solution.

**Comment by oscarotero** [comment]
Okay. You can use the [`filter_pages` plugin](https://lume.land/plugins/filter_pages/) to filter the pages after rendering, so they are available on rendering but removed before being saved in the dest folder. For example:

```js
// Assuming that all your articles have the `type=article` variable
site.use(filterPages({
  fn: (page) => page.data.type === "article"
}));
```

**Comment by hannobraun** [comment]
Oh, nice, thank you!

So many useful plugins. Hard to keep them all straight :smile:
