### ISSUE TITLE
Simplify Twitter Card Tags and Remove Unused Keywords Meta Tag

### ISSUE THREAD

**Issue by cevdetarda** [lumeland/lume#487]
## Issue Description

The current implementation of the `metas.ts` plugin in Lume includes unnecessary Twitter Card tags (`twitter:*`) even when OpenGraph tags (`og:*`) are present. Twitter provides fallback behavior for OpenGraph tags, which means that we don't need to duplicate our efforts by including both sets of tags.

Additionally, the keywords meta tag is no longer utilized by search engines for SEO purposes. Therefore, it can be safely removed to reduce output sizes and maintain consistent development practices.

## Proposed Changes

- Remove the `twitter:title` tag if `og:title` is present, optimizing the Twitter Card tags.
- Simplify Twitter Card tags to include only `twitter:site` and `twitter:card` when `og:*` tags are present, eliminating redundant tags.
- Consider removing the keywords meta tag as it is no longer effective for SEO, resulting in a cleaner codebase and reduced output size.

## Additional Information

- [Twitter Card Markup Documentation](https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/markup) provides details on Twitter's card markup requirements.
- [Getting Started with Twitter Cards](https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/getting-started) offers guidance on implementing Twitter Cards effectively.
- [Social Media Meta Tags](https://head-2ml.pages.dev/#social-media) provides insights into best practices for social media meta tags.
- [Google's Statement on Keywords Meta Tag](https://developers.google.com/search/blog/2009/09/google-does-not-use-keywords-meta-tag) clarifies that Google does not use the keywords meta tag for ranking websites.
- [Twitter Confirmation on Keywords Meta Tag](https://twitter.com/ChristiJOlson/status/1266415751172247552) highlights that Twitter also does not use the keywords meta tag.

These changes will streamline the meta tag implementation, reduce redundancy, and ensure alignment with current SEO practices and social media card standards. 😄

**Comment by oscarotero** [comment]
I'm ok about removing redundant tags but not removing the keywords meta tag. This is not only about SEO, if users want to specify the keywords tag, they should be able to do.

**Comment by cevdetarda** [comment]
So, going to create a PR!
