### ISSUE TITLE
Ordering of `source` elements generated by the picture plugin

### ISSUE THREAD

**Issue by cgwrench** [lumeland/lume#492]
### Enter your suggestions in details:

I'm trying to use the picture plugin to add support for serving multiple image formats. I've found that the order of `source` elements isn't ideal.

With the following in my `_config.ts`:

```typescript
site.use(picture());
site.use(imagick({
    extensions: [".webp", ".jpg"]
}));
```

I've added two images to a markdown file:

```markdown
<img src="/assets/images/test1.jpg" imagick="jpg webp 600">

<img src="/assets/images/test2.webp" imagick="webp jpg 600">
```

Note that the order of the formats in the `imagick` attribute differ. I also don't have any `imagick` shared data, so the imagick plugin shouldn't do anything other that what's set up by the picture plugin.

This generates the following output:

```html
<picture>
    <source srcset="/assets/images/test1-600w.jpg" type="image/jpeg">
    <source srcset="/assets/images/test1-600w.webp" type="image/webp">
    <img src="/assets/images/test1.jpg">
</picture>

<picture>
    <source srcset="/assets/images/test2-600w.webp" type="image/webp">
    <source srcset="/assets/images/test2-600w.jpg" type="image/jpeg">
    <img src="/assets/images/test2.webp">
</picture>
```

For the first image, the JPEG format is included twice: once in a `source` element, and once in an `img` element. However, the `img` element refers to the original image, not the transformed image. As this isn't generated or copied into the build folder, this `img` returns a 404 (but the first `source` element is selected and displayed). Also, the `webp`, included in the second `source` element format will never get used, as browsers that support this format also support JPEGs, so the first `source` element is always used.

The order of source elements is fine for the second image, however, this still has the issue that the `src` for the `img` element doesn't exist. Also, I think it would be preferable for this `src` to point to the generate JPEG, since this would have broader browser support.

The seems picture plugin adds `source` elements for each format defined in the `imagick` attribute, but it also copies the original `img` as-is.

I think it would be better for the plugin to disregard the original `img` element and select one of the formats in the `imagick` attribute to be used as the source for a new `img` element that is generated along with the `source` elements. There are a couple of things that would need a little care here:

1. If generating a new `img` element, which source format should be used? It might make sense to specify an ordered list of preferred `img` source formats (something like  `["jpeg", "png", "webp", "avif"]`, perhaps). The first matching source should be used. If there are multiple sizes, then I'd suggest the largest image size is selected.

2. If generating a new `img` element, we'd loose any attributes on the original `img` element. It might make sense to introduce a `copyAttributes` option, like the one provided by the inline plugin.

Rather than creating a new `img` element, an alternative approach might be to update the `src` for the original `img` element to point to a generated image.

Note that what I've described above is for the case of a single image with. I think it's correct to still include a `source` for all image formats, even the one used for the `img` element, if there are multiple sizes in play. However, in the example above, there's an unnecessary `source` element.

I hope this example illustrates the issue I've seen. Please let me know if you need any more information.

---

As an aside, I did try to use an attribute of `imagick="webp jpg"`, i.e. without a width specified, as all I'm trying to do is generate multiple image formats, and I'd like to retain the original sizes of images. I don't think this is currently supported by the picture plugin. Is that correct?

**Comment by oscarotero** [comment]
Hi @cgwrench Thanks for the detailed explanation.
Indeed, the picture plugin generates the `source` elements in the same order as the formats defined in the `imagick` attribute. It's possible to reorder the formats from the most modern format (avif, jxl) to the oldest format (jpeg) and provide an option to configure a different order if desired.

The image in the img probably should be the latest image in the priority list. For example:

```php
<picture>
    <source srcset="/assets/images/test2-600w.avif" type="image/avif">
    <source srcset="/assets/images/test2-600w.webp" type="image/webp">
    <source srcset="/assets/images/test2-600w.jpg" type="image/jpeg">
    <img src="/assets/images/test2-600w.jpg">
</picture>
```
The last image in the priority list should be the best supported format (jpg in this example) so it should be the image choosed for the img, to ensure old browsers not supporting the `picture` element will be able to display this image.

And about the lack of width values, I'll take a look. The `@1` pixel density should be added automatically.

**Comment by oscarotero** [comment]
Okay, I'll work on that in order to have it ready for the incoming Lume 1.19

**Comment by oscarotero** [comment]
@cgwrench Can you try it now? Upgrade Lume to the latests development version `deno task lume upgrade --dev`

**Comment by oscarotero** [comment]
Hmm, this is because the image is exported twice, one by the imagick plugin and other by the picture. I just fixed it by removing the duplicated transformations (two transformations with the same format/extension and suffix).
