### ISSUE TITLE
Picture plugin enhancements

### ISSUE THREAD

**Issue by cgwrench** [lumeland/lume#493]
### Enter your suggestions in details:

I've been testing the picture plugin, as I'm looking to migrate from Eleventy (and it's image plugin) to Lume. There are a few additional features the Eleventy's image plugin offers that I'd love to see in Lume's picture plugin[^1]:

1. `width` and `height` attributes are added to the `img` element.
2. Images aren't scaled up beyond their original dimensions.
3. It's easy to add `deocding="async"` and `loading="lazy"` attributes to the `img` element.
4. It enforces that there is an `alt` attribute set on the `img` element.
5. A hash of the image's contents is included in the filename of generated images (to support setting long cache headers).

I thought I'd raise them here to see if any of these could be incorporated into the picture plugin. I'd be happy to try and implement some of these myself, if there is an appetite to add these.

I think item 5 is covered by https://github.com/lumeland/lume/issues/352, and I think it makes sense to be a separate plugin rather than something purely image related. I'd love to see some progress made on this (and would be happy to try and contribute this, but would need some guidance on the right approach to take).

I think items 3 & 4 are simple enough to do with a plugin I could write myself, so no worries if these don't become part of the picture plugin.

I don't think that item 2 is possible with the picture plugin. Is this currently possible? If not, is this a feature you'd like to see with the picture plugin?

Now for item 1, again this could be done as part of plugin I could write. However, this one gave me some pause for thought. Doing this myself would mean that I've have to read the contents of the generated images to work out their dimensions. As the imagick plugin has already read and processed the images, it seems a bit wasteful to re-read them. However, this is totally doable with another plugin that runs after the picture/imagick plugins, so it's also not a deal breaker if I have to write this myself.

Is adding `width` and `height` attributes to `img` elements something that could be done with the picture plugin?

[^1]: This has partially been covered by [this discussion](https://github.com/lumeland/lume/discussions/350). Apologies for re-raising some of these points.

**Comment by oscarotero** [comment]
For point 1: Yeah, your code looks reasonable. There's a repo for experimental / beta plugins: https://github.com/lumeland/experimental-plugins
If you want to work on this plugin, we can include it here, in order to test it.

For point 2: Ok, sorry for the missunderstanding. I'll check that.

For point 5: Great! let me know when you want to start!

**Comment by cgwrench** [comment]
I think point 2 is the only outstanding issue from this thread, and that seems to have been addressed by #530, so I think this issue can be closed.
