### ISSUE TITLE
tailwindcss arbitrary variants are broken

### ISSUE THREAD

**Issue by hesxenon** [lumeland/lume#498]
### Version

1.19.1

### Platform

linux

### What steps will reproduce the bug?

Setup a new lume project with jsx + tailwind, then create jsx layout that makes use of arbitrary variants like `[&:not(:focus)]`. 

### How often does it reproduce? Is there a required condition?

every time, it's not a heisenbug :)

### What is the expected behavior?

Arbitrary variants should work

### What do you see instead?

Arbitrary variants don't work

### Additional information

I've traced this bug a bit and the reason is that when the tailwind plugin processes the `page.content` the string is already html escaped (`[&amp;:not(:focus)]`) and thus the needed classes won't be generated.

While I can work around this by registering a processor before the tailwind plugin and just "un-escape" the content string it feels very brittle and hacky.

I'm not sure what the appropriate solution would be here but I _think_ it would make more sense to only escape the generated HTML before saving instead of adapting the tailwind plugin for this use case as this would prevent further bugs like this for other future plugins.

**Comment by oscarotero** [comment]
Hi.
I'm not a Tailwind expert. Do you mean something like this?

```jsx
export default function () {
  return <div className="[&:not(:focus)]">
    Hello world
  </div>
}
```

As I can see, the output html code is this:

```html
<!DOCTYPE html>
<div class="[&amp;:not(:focus)]">Hello world</div>
```

The code is not escaped by Lume, maybe it's done by JSX itself?

**Comment by hesxenon** [comment]
damn, I wasn't sure who's responsible for escaping the generated html - so it seems the jsx plugin should be investigated? If that's not possible I guess the only fix is for the tailwind plugin to "un-escape" the content before passing it to tailwind, no?

**Comment by oscarotero** [comment]
I think it is an issue from Tailwind side.

**Comment by hesxenon** [comment]
well yes and no - on one side it's tailwinds fault for building on a syntax that contains dangerous characters, on the other side this syntax is inside a string where it needn't be escaped.

So no, I don't think that we can just say tailwind has to change their syntax.

**Comment by hesxenon** [comment]
okay, I tried getting around this by passing `extensions: [".html", ".tsx"]` to the tailwindcss plugin options, to no avail :/ the respective classes sadly still aren't generated.

**Comment by oscarotero** [comment]
You can use the following processor, just before tailwindcss to fix the classnames:

```js
site.process([".html"], (page) => {
  page.content = page.content
    .replace(/class="([^"]+)"/, (match) => match.replace("&amp;", "&"));
})
```

**Comment by hesxenon** [comment]
yeah, I had that until yesterday when that solution stopped working 😅

maybe because I moved to mdx 🤔
