### ISSUE TITLE
[UX] Inline plugin should support rewriting path in `site.process()`

### ISSUE THREAD

**Issue by ngdangtu-vn** [lumeland/lume#506]
### Enter your suggestions in details:

This is how I setup `_config.js`

1. Install inline plugin
2. Install sass plugin
3. Add rewrite path to `_config.js`   
  ```js
site.process(['.css'], (p) => {
   if (!p.data.url) return void 0
   p.data.url = p.data.url.replace('style/', '')
})
  ```
4. Add `<link rel="stylesheet" href="/my-styles.css" inline>` to layout file

The `my-style.scss` is actually inside `/style/my-style.scss` and being rewritten to `/my-style.css`. At first I thought because the plugin ran early so I switch step 1 and step 3 position. But the result is still the same. The inline plugin requires us to input correct path before rewritten with the post-compiled file (instead scss, we go css).

This can be a bit confuse for later comeback. Is it possible to set path after rewritten only?

**Comment by ngdangtu-vn** [comment]
This can be solved by reordering like this: 2 → 3 → 1

Not great if you want to keep all installing plugins code in 1 block but it's clear that what is happening inside the lume :?

**Comment by oscarotero** [comment]
The plugins/processors are executed in the same order they are registered:

1. SASS plugin: will compile the scss files and convert `/style/my-style.scss` to `/style/my-style.css`
2. Rewrite processor: converts the file to `/my-style.css`
3. Inline plugin: It can detect the`/my-style.css` from the `<link>` element and inline it.

**Comment by ngdangtu-vn** [comment]
One day, I will write a document about this one. I keep forgetting it and make a mess :p
