### ISSUE TITLE
Add attribute "target" in anchor tag

### ISSUE THREAD

**Issue by alaminkouser** [lumeland/lume#508]
### Enter your suggestions in details:

I searched the document, but could not find the feature.

I want to add attribute "target" as "_blank" in all external links. So if the user opens a page which is external, it will open in new tab. I tried the DOMParser, but I was not able to do it.

NOTE: it will not be added in internal/site links.

**Comment by oscarotero** [comment]
You can use a processor for that. For example:

```js
// _config.ts

site.process([".html"], (page) => {
  page.document.querySelectorAll('a[href^="http"]').forEach((a) => {
    a.setAttribute("target", "_blank");
  });
});
```

**Comment by alaminkouser** [comment]
It is working. Thanks.
