### ISSUE TITLE
Incorrect version navigation on `deno.land/x`

### ISSUE THREAD

**Issue by citrusmunch** [lumeland/lume#511]
### Version

1.19.2 and 1.19.3

### Platform

Firefox

### What steps will reproduce the bug?

viewing version selection window in the sidebar at

https://deno.land/x/lume@v1.19.2
https://deno.land/x/lume@v1.19.3

### How often does it reproduce? Is there a required condition?

always

### What is the expected behavior?

proper listings

### What do you see instead?

listings for https://deno.land/x/lume@v1.19.2

+ v1.19.3 (latest)
+ v1.19.2
+ v1.19.2
+ v1.19.1
+ etc.

listings for https://deno.land/x/lume@v1.19.3

+ v1.19.2 (latest)
+ v1.19.2 (latest)
+ v1.19.1
+ etc.

### Additional information

It doesn't appear this happens on the few other modules I skimmed, so it doesn't seem to be a deno issue, or it's more difficult to reproduce than expected.

**Comment by citrusmunch** [comment]
v1.19.3
![Screen Shot 2023-11-20 at 15 21 08](https://github.com/lumeland/lume/assets/5790901/19bc54db-b8a7-4738-a2e8-d119d7026948)

v1.19.2
![Screen Shot 2023-11-20 at 15 21 26](https://github.com/lumeland/lume/assets/5790901/dc4cd52b-ec3f-4786-b657-2ce28b827383)

**Comment by oscarotero** [comment]
I think it's a deno.land/x issue. The version selector inside the module is correct:
<img width="1260" alt="imaxe" src="https://github.com/lumeland/lume/assets/377873/dc061d57-beab-4b92-9b10-080cb46751d2">
