### ISSUE TITLE
Picture/Imagick fails to display image starting with a date in the filename

### ISSUE THREAD

**Issue by enjikaka** [lumeland/lume#519]
### Version

1.19.4

### Platform

macOS

### What steps will reproduce the bug?

- Set up imagick & picture
- Try to use and image that starts with a date and continues with a name, for example `2021-01-30-herpderp.jpg`

https://github.com/enjikaka/lume-img-error

### How often does it reproduce? Is there a required condition?

100 % reproducible

### What is the expected behavior?

The image should load

### What do you see instead?

The image does not load

![localhost_3000_](https://github.com/lumeland/lume/assets/877455/206b0e85-39b8-4913-9a7f-e8ec38071893)

### Additional information

- If I change the format of the file name to `herpderp-2021-01-30.jpg` the image loads. 
- It only seems to happen when the file starts with a date? Tried `2-jordgubbe.jpg` and that works, so a number as start doesn't seem to be the trigger
- Images are referenced in HTML in `_site/` but the image files are not created

**Comment by enjikaka** [comment]
Aha. In my example repo linked there is a ”jordgubbar.jpg” so I guess the file is generated then. But the picture element doesnt reference that generated name, only the source file with date.

**Comment by oscarotero** [comment]
Can you try with [`resolve_urls` plugin](https://lume.land/plugins/resolve_urls/) installed?
