### ISSUE TITLE
Split core functionality in `mod.ts`

### ISSUE THREAD

**Issue by scarf005** [lumeland/lume#535]
### Enter your suggestions in details:

currently many features are packed into [`lume/mod.ts`](https://github.com/lumeland/lume/blob/12f8dc64b08a004c273548c9a0954bd8ec137188/mod.ts#L3-L11).

1. [`getOptionsFromCli`](https://github.com/lumeland/lume/blob/12f8dc64b08a004c273548c9a0954bd8ec137188/mod.ts#L64) is private.
2. [`lume`](https://github.com/lumeland/lume/blob/12f8dc64b08a004c273548c9a0954bd8ec137188/mod.ts#L29C1-L29C29) uses predefined plugins.
3. [ignorelist](https://github.com/lumeland/lume/blob/12f8dc64b08a004c273548c9a0954bd8ec137188/mod.ts#L40-L44) is private inside function body,

it may be beneficial to extract these features into separate files. for example, it would make creating an lightweight lume function without pre-defined modules (url, json, vento, etc...) with Cli support easier.

**Comment by oscarotero** [comment]
I guess `getOptionsFromCli()` can be moved to `core/utils/` folder. What do you think?
Do you want to work on a PR?

**Comment by scarf005** [comment]
yes, i'll open a PR.
