### ISSUE TITLE
robots.txt plugin

### ISSUE THREAD

**Issue by oscarotero** [lumeland/lume#543]
### Enter your suggestions in details:

It would be usefult to block AI agents, for example: https://darkvisitors.com/robots-txt-builder

**Comment by kwaa** [comment]
For the `Options` types, perhaps we can refer to [nuxt-modules/robots](https://github.com/nuxt-modules/robots).

**Comment by oscarotero** [comment]
That's a good reference, thanks! But Lume plugins always use objects for options, so maybe this structure fits better:

```js
site.use(robots({
  agents: [
    {
      name: "ChatGPT-User",
      disallow: "/",
    },
  ],
  sitemap: "https://lume.land/sitemap.xml"
}));
```

I'd like to include some shortcuts to make it more ergonomic:

```js
site.use(robots({
  agents: [
    "ChatGP-User", // shortcut to "disalow: /",
    "AI", // Shortcut to all AI agents.
  ]
}));
```

**Comment by kwaa** [comment]
> That's a good reference, thanks! But Lume plugins always use objects for options, so maybe this structure fits better:

Perhaps it would be more appropriate to use the `disallow` keyword rather than `agents`.

```ts
site.use(robots({
  disallow: ['ChatGPT-User'],
  rules: [{
    userAgent: '*',
    allow: '/'
  }],
  sitemap: 'https://lume.land/sitemap.xml',
}))
```

**Comment by oscarotero** [comment]
Thinking of privacity and good defaults, maybe the plugin should disable access by default and only grant access to bots explicity defined. For example:

```js
site.use(robots({
  allow: ["Google", "Bing", "Yahoo", "OpenAI"],
  paths: "/"
}));
```

This would generate this file:

```txt
User-Agent: *
Disallow: /

User-Agent: Googlebot
Allow: /

User-Agent: Bingbot
Allow: /

User-Agent: Yahoo-MMCrawler
Allow: /

User-Agent: ChatGPT-User
Allow: /
```

**Comment by kwaa** [comment]
> Thinking of privacity and good defaults, maybe the plugin should disable access by default and only grant access to bots explicity defined.

Ideally can let users set up to use blacklist or whitelist mode.

```ts
site.use(robots({
  whitelist: true,
  allow: ['ChatGPT-User']
}))

site.use(robots({
  // whitelist: false, (default)
  disallow: ['ChatGPT-User']
}))
```

**Comment by kwaa** [comment]
Given the myriad of possible UserAgent values, I likewise think it's best not to manage name conversions. (like `Google => Googlebot`, `ChatGPT => ChatGPT-User`)

https://darkvisitors.com/agents
