### ISSUE TITLE
Upgrading to Lume 2.0.x is breaking the build

### ISSUE THREAD

**Issue by doga** [lumeland/lume#545]
### Version

2.0.2

### Platform

deno 1.39.1 (release, x86_64-apple-darwin), macOS 12.7.2

### What steps will reproduce the bug?

```
git clone https://github.com/doga/qworum-website.git
cd qworum-website
deno task lume upgrade
deno task serve
```

produces:

```
Task serve deno task lume -s
Task lume echo "import 'lume/cli.ts'" | deno run --unstable -A - "-s"
Loading config file file:///Users/[path to project]/_config.ts
TypeError: Module not found "https://deno.land/x/lume@v2.0.2/core.ts".
    at https://deno.land/x/lume_langdata@v1.0.9/mod.ts:10:22
    at async createSite (https://deno.land/x/lume@v2.0.2/cli/run.ts:50:17)
    at async build (https://deno.land/x/lume@v2.0.2/cli/build.ts:31:16)
    at async Command.execute (https://deno.land/x/cliffy@v0.25.7/command/command.ts:1794:7)
    at async Command.parseCommand (https://deno.land/x/cliffy@v0.25.7/command/command.ts:1639:14)
    at async https://deno.land/x/lume@v2.0.2/cli.ts:121:3 {
  code: "ERR_MODULE_NOT_FOUND"
}
```

### How often does it reproduce? Is there a required condition?

This is a deterministic bug that happens each time I try upgrading from lume v1.19.4 to lume v2.0.x.

### What is the expected behavior?

`deno task serve` and  `deno task build`  must not crash.

### What do you see instead?

`deno task serve` is crashing (and so does `deno task build`):

```
Task serve deno task lume -s
Task lume echo "import 'lume/cli.ts'" | deno run --unstable -A - "-s"
Loading config file file:///Users/[path to project]/_config.ts
TypeError: Module not found "https://deno.land/x/lume@v2.0.2/core.ts".
    at https://deno.land/x/lume_langdata@v1.0.9/mod.ts:10:22
    at async createSite (https://deno.land/x/lume@v2.0.2/cli/run.ts:50:17)
    at async build (https://deno.land/x/lume@v2.0.2/cli/build.ts:31:16)
    at async Command.execute (https://deno.land/x/cliffy@v0.25.7/command/command.ts:1794:7)
    at async Command.parseCommand (https://deno.land/x/cliffy@v0.25.7/command/command.ts:1639:14)
    at async https://deno.land/x/lume@v2.0.2/cli.ts:121:3 {
  code: "ERR_MODULE_NOT_FOUND"
}
```

### Additional information

Reverting back to lume v1.19.4 in `import_map.json` fixes the buggy behaviour.

**Comment by oscarotero** [comment]
In Lume 2, there's no `/core.ts` file. The types are imported from the `deno.json` file and accessible from the global `Lume` namespace (See more info here: https://lume.land/blog/posts/lume-2/#typescript-improvements).

Seems that the `lume_langdata` plugin is trying to import `https://deno.land/x/lume@v2.0.2/core.ts`, which is what's failing.

**Comment by doga** [comment]
Thanks, that fixed it. 

Lume2 is looking fine from where I am standing, most notably Vento.

I've updated my _Lume_ plugins, hopefully other plugin developers are aware of this breaking Lume update:

- [https://deno.land/x/lume_navbardata](https://deno.land/x/lume_navbardata)
- [https://deno.land/x/lume_langdata](https://deno.land/x/lume_langdata)
- [https://deno.land/x/lume_cross_language_content](https://deno.land/x/lume_cross_language_content)
