### ISSUE TITLE
JSX onclick attributes are stripped during build

### ISSUE THREAD

**Issue by brimworks** [lumeland/lume#549]
### Version

2.0.1

### Platform

Mac

### What steps will reproduce the bug?

Write a simple JSX component with an `onClick` attribute:

(`_components/Button.jsx`)
```jsx
export default ({ }, helpers) => (
<button onClick="alert('hi')">Click Me!</button>
)
```

When this component is rendered, it strips out the `onclick` HTML attribute.

### How often does it reproduce? Is there a required condition?

Always

### What is the expected behavior?

When rendered, the `onClick` HTML attribute should remain unmolested.

### What do you see instead?

The `onClick` HTML attribute is stripped off.

**Comment by brimworks** [comment]
Note that if I use `onclick` attribute name I get:

```
Warning: Invalid event handler property `onclick`. React events use the camelCase naming convention, for example `onClick`.
    at button
```

...as this was the suggestion here: https://github.com/lumeland/lume/issues/396#issuecomment-1474031811

**Comment by oscarotero** [comment]
Seems that React cannot [render statically attributes for events](https://stackoverflow.com/questions/24440991/render-onclick-attribute-using-react-js-when-calling-rendercomponenttostaticmark).

You can use the `jsx_preact` plugin, that keeps the `onclick` attribute.

**Comment by brimworks** [comment]
Thanks for the response! Yes, switching to `jsx_preact` plugin fixes the problem. Perhaps a note about this should be added to the doc site... and maybe even make preact the default? Just some thoughts. I very much appreciate the help!
