### ISSUE TITLE
Parsing Exception: CSS selector query doesn't get attribute value

### ISSUE THREAD

**Issue by ngdangtu-vn** [lumeland/lume#556]
### Version

2.0.3

### Platform

any

### What steps will reproduce the bug?

The issue was submitted in discord: https://discord.com/channels/794537085641818124/1197989006789595156/1197989006789595156

1. Add `_data.yml`
  ```yml
  metas:
    title: "=title"
    description: "=summary"
    image: "$.feed-image"
  ```
2. Add content that has this HTML element: `<img alt="Reading tracker app with Airtable and Deno Fresh, showing the Airtable and Deno logos." class="feed-image" src="/img/posts/reading-tracker-post-3-large.webp" width="1000">`

### How often does it reproduce? Is there a required condition?

Always.

### What is the expected behavior?

The reporter expects to have the `src` set in place of meta `og:image`.

### What do you see instead?

Nothing. the behaviou is correct. But it doesn't make sense for users.

### Additional information

The source of problem: https://github.com/lumeland/lume/blob/main/core/utils/data_values.ts#L26

This is an UX bug. This happens due to the convention only return the `innerHTML`. If it is a void element, nothing will returns. The design needs improve or to be removed as it makes users confused. Need further discussion about this feature.

**Comment by ngdangtu-vn** [comment]
So far we have 3 cases:

1. Only need children text node, for instance `h1`, `p`
2. Only need specific attr, for instance `img` with `[src]`
3. The element provide rich data to use: `a` with `[href]` and child node

I also think about the nested element. But I don't think we need to support it. Users should point it directly to the element contains the info.

**Comment by oscarotero** [comment]
I see the problem. The solution of allowing the attribute name is a good idea, but `[src]` is confusing because it's a valid selector. I'd use a different syntax. An idea: the [`attr()` function ](https://developer.mozilla.org/en-US/docs/Web/CSS/attr). For eaxmple: 

```
$.feed-image attr(src)
```

Other solution is to make it more automatic:

- If the selector is to get an URL, get the value from `href` or `src` attribute.
- If not, get the value from the element content.

**Comment by ngdangtu-vn** [comment]
> If the selector is to get an URL, get the value from href or src attribute.

I have the 3rd case where we wouldn't know what user may need:

> 3. The element provides rich data to use: a with [href] and child node

It could be child text node from the element or it could be href.


I don't mind the `attr()` css function. Mind if I do this PR?

**Comment by oscarotero** [comment]
Sure! PR is very appreciated 👍
