### ISSUE TITLE
add arrow indicator for url transformation

### ISSUE THREAD

**Issue by scarf005** [lumeland/lume#557]
### Enter your suggestions in details:

It took me embarrassingly long time figuring out which is the original URL and which is the modified one, but making it explicit would be nice.

#### As-is

```
🔥 /index.html /posts/index.tsx
```

#### To-be

```
🔥 /posts/index.tsx -> /index.html 
```

#### Additional notes

I'm willing to open a PR when accepted (since it's tiny)

**Comment by oscarotero** [comment]
I wouldn't want to change the order of the files, because the most important part (I think) is the final URL. What do you think about reversed arrow?

```
🔥 /index.html <- /posts/index.tsx
```

**Comment by scarf005** [comment]
i too think the final URL is important. however since most of the time sentences are read from left-to-right (e.g typescript function signature), thought using `->` might make sense.

**Comment by oscarotero** [comment]
I'm thinking of maybe the original file would be visible only in `DEBUG` mode, but not by default (INFO mode). When the site has many pages or files to copy, there is too much text in the terminal. In DEBUG mode we can show them in the same order you're proposing. What do you think?

**Comment by scarf005** [comment]
i think it's better to be explicit by default.
