### ISSUE TITLE
Copying an underscored file removes the underscore

### ISSUE THREAD

**Issue by cgwrench** [lumeland/lume#569]
### Version

v2.0.3

### Platform

Windows

### What steps will reproduce the bug?

I'm trying to copy a file whose filename begins with an underscore, like the following [example from the docs](https://lume.land/docs/configuration/copy-static-files/#ignored-files):

```javascript
// Copy a underscored file
site.copy("_headers");
```

### What is the expected behavior?

I'd expect to see a `_headers` file in the `_site` output directory.

### What do you see instead?

Instead, I see a `headers` file (note the missling leading underscore).

### Additional information

Is this the expected behaviour? If so, how can I copy a file and retain it's leading underscore?

**Comment by oscarotero** [comment]
Hmm, I guess you're using the `slugifyUrls` plugin, right? By default, this plugin slugify the url of all files, and I could confirm that `_headers` is converted to `headers`.
I have to think of a good solution for this use case, but for now, you can configure the plugin to only slugify html pages:

```js
site.use(slugifyUrls({
  extensions: [".html"]
}));
```

**Comment by cgwrench** [comment]
I am using the `slugifyUrls` plugin. This behaviour is a little surprising, but thanks for the explanation and workaround.

**Comment by oscarotero** [comment]
Yes, I'm agree that this behavior is not right. I'll change it in the next lume version
