### ISSUE TITLE
Add ability to change sort direction for date

### ISSUE THREAD

**Issue by kevinlang** [lumeland/lume#57]
I see this documentation here: https://lumeland.github.io/creating-pages/searching/

And I see that `date` is the default sort. As far as I can tell it dates in ascending order (oldest first). I would like to sort in descending order (newest first), but could not find how to.

Perhaps looking something like:
```
search.pages("type=post", "date=desc")
```

Cheers,

**Comment by kevinlang** [comment]
I found how to do it, in my case just using nunjucks built-in `reverse` function.

```
search.pages("type=post", "date=desc") | reverse
```

May be worth adding docs, though.

**Comment by oscarotero** [comment]
ATM, the sort argument only accepts the field name (`date` by default), but it's a good idea to include support for asc/desc. I'll work on that. Thanks!
