### ISSUE TITLE
`--unstable` deprecation warning

### ISSUE THREAD

**Issue by mash-graz** [lumeland/lume#572]
### Version

lume v2.0.3

### Platform

deno 1.40.4 (release, x86_64-unknown-linux-gnu)

### What steps will reproduce the bug?

```
❯ deno task lume
Task lume echo "import 'lume/cli.ts'" | deno run --unstable -A -
⚠️  The `--unstable` flag is deprecated and will be removed in Deno 2.0. Use granular `--unstable-*` flags instead.
Learn more at: https://docs.deno.com/runtime/manual/tools/unstable_flags
...
```

### What do you see instead?

The unstable argument used in the task description `--unstable` should be removed or replaced by a list of more specific `--unstable-*` arguments.

**Comment by oscarotero** [comment]
Thanks. This is already fixed and will be available in the next version of Lume.
Meanwhile, you can remove the `--unstable` flag in your _config file because it's no longer required.

**Comment by mash-graz** [comment]
Thanks!

**Comment by mash-graz** [comment]
Fixed: https://github.com/lumeland/lume/commit/bc4e25e36fa78a461b96c411fc47b7ab37b4c7b3
