### ISSUE TITLE
Minify <style> CSS from UnoCSS, when using `cssFile: false`

### ISSUE THREAD

**Issue by danklammer** [lumeland/lume#578]
### Enter your suggestions in details:

Currently there is no way to minify the `<style>` CSS from UnoCSS, when using `cssFile: false`.

Even when using the Minify HTML plugin, the CSS within the <style> tag is unminified.

![unminified_embedded_css](https://github.com/lumeland/lume/assets/1743221/9e3dbd39-8066-463e-8bd2-c2c3c15c1b2b)

**Comment by oscarotero** [comment]
Hi!
Thanks for mentioning this. I just found a bug in the unocss plugin that might be the cause of your problem. Can you upgrade Lume to the latest development version and confirm it works fine now? Run `deno task lume upgrade --dev`.

**Comment by danklammer** [comment]
You are so fast! That fixes it — thank you!
