### ISSUE TITLE
Search plugin seems to be missing pages generated by the multilanguage plugin

### ISSUE THREAD

**Issue by mindreframer** [lumeland/lume#583]
### Version

https://deno.land/x/lume@v2.1.1

### Platform

OSX (12.7.3)

### What steps will reproduce the bug?

- configure multilanguage plugin
- create some pages with same `id` for different languages
- render a list of all pages like 
```
<ul>
  {{ for page of search.pages("") }}
  <li>{{ page.title }} - {{page.url}} - {{page.layout}}</li>
  {{ /for }}
</ul>
```

-> pages with multilang features are missing in the list

### How often does it reproduce? Is there a required condition?

consistently

### What is the expected behavior?

multilang pages should be included in search with empty string

### What do you see instead?

- nothing

### Additional information

Feel free to ask for a bug reproduction in code, if for some reason this bug is not reproducible

**Comment by mindreframer** [comment]
correction: this only manifests with JSX files. Multilang Markdown files are visible in search.pages result

**Comment by mindreframer** [comment]
I have made a reproduction repo: https://github.com/mindreframer/lume-bug-page-search

**Comment by mindreframer** [comment]
And it seems it is not related to the extension. I have markdown files, and some of them are in the search results, some not.

**Comment by mindreframer** [comment]
The fix/workaround is to include `/` at the end of the URL: 

- https://github.com/mindreframer/lume-bug-page-search/commit/c5be812bf9dd5826bd85d1c62cffbd7622564afe

Then the pages are included in the search result.

**Comment by oscarotero** [comment]
That's not a bug.

`search.pages()` only returns HTML pages. This means the url must end with `.html` or `/` (which is equivalent to `/index.html`).

For example: `/pathname` is a non-HTML page, it's just a file without extension. But `/pathname/` is a HTML page because is exported to `/pathname/index.html`.

**Comment by mindreframer** [comment]
Thank you for the response! Sorry, been absent last 2 days. OK, good to know, that a missing slash at the end is considered a non-HTML page. Maybe it makes sense to document somewhere, I went through the complete documentation and could not figure out the reason for this behaviour. 

And thanks for Lume, I enjoy using it so far!
