### ISSUE TITLE
.well-known support

### ISSUE THREAD

**Issue by oscarotero** [lumeland/lume#585]
.well-known is a folder to store things like verification files, security.txt, etc.
Due it starts with dot, it's ignored by Lume. Maybe this should be an exception and treat this folder as a regular folder.

PD: Does a `well_known` plugin  make sense?

**Comment by kwaa** [comment]
This would be helpful for [Hatsu](https://hatsu.cli.rs) integration, but I don't think a specialized plugin is needed - just treat as a regular folder.

**Comment by oscarotero** [comment]
Right. I just made some changes to don't ignore this folder by default.

**Comment by oscarotero** [comment]
Landed in Lume 2.1.3
