### ISSUE TITLE
`deno task lume` fails directly after init

### ISSUE THREAD

**Issue by z0rrn** [lumeland/lume#595]
### Version

Lume v2.1.3 with Deno v1.42.1

### Platform

Linux with GNU, amd64, MXLinux

### What steps will reproduce the bug?

1. Install Deno
2. Initialize Lume `deno run -A https://lume.land/init.ts` (Vanilla JS, without Plugins/Themes/CMS)
3. Run any task like `deno task lume`

### How often does it reproduce? Is there a required condition?

For me it always worked.

### What is the expected behavior?

The site builds correctly.

### What do you see instead?

user@system:~/projects/test-lume$ deno task lume
Task lume echo "import 'lume/cli.ts'" | deno run -A -
TypeError: not found
    at async Command.fn (https://deno.land/x/lume@v2.1.3/cli.ts:146:23)
    at async Command.execute (https://deno.land/x/cliffy@v0.25.7/command/command.ts:1794:7)
    at async Command.parseCommand (https://deno.land/x/cliffy@v0.25.7/command/command.ts:1639:14)
    at async https://deno.land/x/lume@v2.1.3/cli.ts:156:3 {
  code: "ERR_MODULE_NOT_FOUND"
}

### Additional information

I installed Deno with [Proto](https://moonrepo.dev/proto).

**Comment by oscarotero** [comment]
Hmm, I can't reproduce this error (even installing Deno with Proto).

The error says [this file doesn't exist](https://deno.land/x/lume@v2.1.3/cli.ts?source=#L146) but the file exists ([it's here](https://deno.land/x/lume@v2.1.3/cli/build.ts?source)).

Could it be a temporary error from land/x registry?

**Comment by z0rrn** [comment]
Yeah, I think that was the issue. After rerunning the command later it immediately worked.

Thanks Anyway.
