### ISSUE TITLE
Add image support in feeds.

### ISSUE THREAD

**Issue by negrel** [lumeland/lume#598]
### Enter your suggestions in details:

Add image support to feed plugin.

[JSON feed spec](https://www.jsonfeed.org/version/1.1/) supports image and banner image but it seems to be non standard in RSS spec. However, some implementations use a meta tag to add OG image to rss feed: https://grafana.com/blog/news.xml.

I'm not sure how this should be implemented for RSS feed...

I have a working example [here](https://github.com/prismelabs/prismeanalytics.com/blob/master/plugins/feed.ts) and I could make a PR if you want.

**Comment by oscarotero** [comment]
Hi.
Good idea. A PR would be great.
Thanks!
