### ISSUE TITLE
Lume failse to build/serve with atypical Linux directory structure.

### ISSUE THREAD

**Issue by computerscience-person** [lumeland/lume#602]
### Version

2.1.4

### Platform

Linux (NixOS)

### What steps will reproduce the bug?

1. Setup Lume (`deno run -A https://lume.land/init.ts`
2. Run lume task (`deno task lume`)

Error:

```
Task lume echo "import 'lume/cli.ts'" | deno run -A - "--" "version"
Loading config file
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: recursive directory iterator cannot open directory: No such file or directory [/usr/share/fonts]
```

### How often does it reproduce? Is there a required condition?

Probably required by lume to load fonts.

### What do you see instead?

```
Task lume echo "import 'lume/cli.ts'" | deno run -A - "--" "version"
Loading config file file:///mnt/Shtuffs/home/Dev/CCS222/final/_config.ts
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: recursive directory iterator cannot open directory: No such file or directory [/usr/share/fonts]
```

### Additional information

NixOS doesn't follow a typical Linux filesystem, and thus, when Lume tries to load fonts from `/usr/share/fonts`, it errors. Maybe I missed a configuration option to change default font directory?

**Comment by oscarotero** [comment]
Hi.
I'm not familiarized with NixOS filesystem. It seems the project directory is `file:///mnt/Shtuffs/home/Dev/CCS222/final/`. Why is trying to read the `/usr/share/fonts` directory? Is there any symbolic link to this folder?

**Comment by computerscience-person** [comment]
Probably to look for system/user fonts, I'd imagine.

**Comment by computerscience-person** [comment]
> Probably to look for system/user fonts, I'd imagine.

I may have missed it in the documentation, but it would be nice if there were a way to configure where lume looks for fonts.

**Comment by oscarotero** [comment]
Lume doesn't look for fonts. It only processes the files in the `src` directory of your project. Can I see your _config.ts file? Maybe there's a plugin or something that want to access to that folder

**Comment by computerscience-person** [comment]
Nothing much, probably shiraha?

```ts
import lume from "lume/mod.ts";
import shiraha from "shiraha/mod.ts";

const site = lume();

site.use(shiraha());

export default site;
```

**Comment by computerscience-person** [comment]
It was a shiraha problem, not lume.
