### ISSUE TITLE
@std/log not found in registry-staging.deno.com

### ISSUE THREAD

**Issue by kuspoes** [lumeland/lume#609]
### Version

2.2.0

### Platform

Macos

### What steps will reproduce the bug?

after installing deno using CLI `deno run -A https://lume.land/init.ts`
then build site for first time using `deno task lume` produce errors

### What is the expected behavior?

build process is done without error.

### What do you see instead?

```sh
Task lume echo "import 'lume/cli.ts'" | deno run -A -
TypeError: Import 'https://registry-staging.deno.com/@std/log/meta.json' failed: error sending request for url (https://registry-staging.deno.com/@std/log/meta.json): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known
    at https://deno.land/x/lume@v2.2.0/deps/log.ts:1:15
    at async Command.fn (https://deno.land/x/lume@v2.2.0/cli.ts:146:23)
    at async Command.execute (https://deno.land/x/cliffy@v0.25.7/command/command.ts:1794:7)
    at async Command.parseCommand (https://deno.land/x/cliffy@v0.25.7/command/command.ts:1639:14)
    at async https://deno.land/x/lume@v2.2.0/cli.ts:156:3 {
  code: "ERR_MODULE_NOT_FOUND"
}
```

### Additional information

the error is failed to lookup address, when I open https://registry-staging.deno.com/@std/log/meta.json directly using browser the requested resource could not be loaded.

Already trying several times using different internet connections/providers (VPN etc) but always failed to open the url.

**Comment by oscarotero** [comment]
That's weird. It works fine to me.
What's your Deno version?

**Comment by oscarotero** [comment]
@kuspoes After asking to Deno team, it seems that you're using an older Deno version. That URL was the JSR url, during the early days before it became JSR
