### ISSUE TITLE
How to use "lume-code" and "Tip caution..." in "tailwind typography"

### ISSUE THREAD

**Issue by iStudyMen** [lumeland/lume#613]
### Enter your suggestions in details:

`lume-code` and `Tip caution...` is very `cool` , but I can't use that in "tailwind typography"。
![捕4获](https://github.com/lumeland/lume/assets/45355403/e5dd1d52-7ae4-45de-9d44-9732894a4926)
![捕获](https://github.com/lumeland/lume/assets/45355403/e81a5c6b-85bf-4030-ae64-54d35df4822c)

**Comment by oscarotero** [comment]
Captions and `lume-core` are not part of Lume. They have been created specifically for their use cases.

Captions are generated with this plugin for markdown-it: https://www.npmjs.com/package/@mdit/plugin-alert and the styles are applied here: https://github.com/lumeland/ds/blob/main/src/components/body.css#L65-L116

I don't know if tailwind has a plugin for that, but you can copy/paste these styles (or create others by your own) if you want.

`lume-code` is a web component I created for lume.land site. The css code is here https://github.com/lumeland/lume.land/blob/main/_includes/styles/components/code.css and I have a processor to change the HTML code in the build here https://github.com/lumeland/lume.land/blob/main/_config.ts#L66

**Comment by iStudyMen** [comment]
好的，我已经解决了这个问题，在我的[Blog Theme](https://deno.land/x/lume_theme_blog@v0.9)新版本中。
