### ISSUE TITLE
buildOrder: make page render after all plugins are run

### ISSUE THREAD

**Issue by iacore** [lumeland/lume#629]
### Enter your suggestions in details:

so the use case is like this

I want this:

1. normal HTML pages are rendered
2. resolve_urls rewrites the link
3. Atom feed file is generated by reading the HTML files

instead, I get this

1. normal HTML pages are rendered
2. Atom feed file is generated by reading the HTML files
3. resolve_urls rewrites the link

Do I need to write a plugin to deal with this use case?

**Comment by oscarotero** [comment]
The [feed plugin](https://lume.land/plugins/feed/) fixes this problem, because you can add the feed plugin after other plugins.

**Comment by iacore** [comment]
> The [feed plugin](https://lume.land/plugins/feed/) fixes this problem, because you can add the feed plugin after other plugins.

Thanks. This should tell me how to write my own plugin.

**Comment by oscarotero** [comment]
@iacore Why do you want to write a Feed plugin?
If you're missing something from the existing one, maybe we can add it.

**Comment by iacore** [comment]
I have my own .tsx template.

Other than missing a feed plugin, I think I need a plugin that renders a page after all plugins are run.

**Comment by iacore** [comment]
> Other than missing a feed plugin, I think I need a plugin that renders a page after all plugins are run.

@oscarotero how do I write a plugin like this? alternatively, should `buildOrder` affect plugins as well?

**Comment by oscarotero** [comment]
If I understand correctly, you want to create a page dynamically. One way to do that is with a processor:

```js
import { Page } from "lume/core/file.ts";

site.process("*", (_, pages) => {
  const newPage = Page.create({
    url: "/new-page-url/",
    content: "Content of the page",
  });

  pages.push(newPage);
});
```

If you want to render the page like the rest of the pages (with the layouts, preprocessors, processors, etc), it's a bit tricky, because Lume is not prepared for that. Maybe you can use the `renderPageOnDemand` function from the renderer class. I didn't test it but perhaps this works:

```js
import { Page } from "lume/core/file.ts";

site.process("*", async (_, pages) => {
  const newPage = Page.create({
    url: "/new-page-url/",
    layout: "main-layout.vto",
    title: "Page title",
    content: "Content of the page {{ title }}",
    templateEngine: [".vto"],
  });

  await site.renderer.renderPageOnDemand(newPage);

  pages.push(newPage);
});
```
