### ISSUE TITLE
Search misses pages that have a tag with spaces

### ISSUE THREAD

**Issue by basus** [lumeland/lume#635]
### Version

2.2.3

### Platform

macOS Sonoma 14.5 with Deno 1.45.1

### What steps will reproduce the bug?

I'm trying to use the following snippet to get all the tags that are currently known and then count the number of pages associated with each tag:

```html
    <ul id="tag-list">
      {{ for tag of search.values("tags").sort() }}
      <li class="tag">
        <a href="{{ tag |> slugify}}">{{ tag }}</a>
        <span class="tag-count">{{ search.pages(tag).length }}</span>
      </li>
      {{ /for }}
    </ul>
```

### What do you see instead?

For most tags, I get the right count. But for tags with spaces like `"hello world"`, the tag shows up in the list given by the first `search`, but the second `search` always has a length of 0.

### Additional information

I'm pretty new to using Lume, so maybe there are more idiomatic ways or working with tags that I'm not aware of?

**Comment by oscarotero** [comment]
You have to put the tags between quotes:

```js
search.pages("'tag with spaces'")
```

**Comment by basus** [comment]
Ahh ok, I managed to get it working with the following:

```
    <ul id="tag-list">
      {{ for tag of search.values("tags").sort() }}
      {{> tag = tag.includes(' ') ? "'".concat(tag, "'") : tag }}
      <li class="tag">
        <a href="{{ tag |> slugify}}">{{ tag }}</a>
        <span class="tag-count">{{ search.pages(tag).length }}</span>
      </li>
      {{ /for }}
    </ul>
```

**Comment by oscarotero** [comment]
Or even simpler:

```html
    <ul id="tag-list">
      {{ for tag of search.values("tags").sort() }}
      <li class="tag">
        <a href="{{ tag |> slugify}}">{{ tag }}</a>
        <span class="tag-count">{{ search.pages(`"${tag}"`).length }}</span>
      </li>
      {{ /for }}
    </ul>
```

**Comment by basus** [comment]
Yes, that worked perfectly. Thank you. Still getting used to the templating system.
