### ISSUE TITLE
[sitemap plugin] lastmod is ctime

### ISSUE THREAD

**Issue by iacore** [lumeland/lume#643]
### What steps will reproduce the bug?

```
import sitemap from "lume/plugins/sitemap.ts";

site.use(sitemap());
```

### How often does it reproduce? Is there a required condition?

100%

### What is the expected behavior?

it should be mtime

### What do you see instead?

inside sitemap.xml:

`<lastmod>(ctime here)</lastmod>`

### Additional information

data.date is ctime i think

**Comment by oscarotero** [comment]
It makes sense.
`date` value is used to assign a date to a page, but and this date can mean anything. By default Lume uses the creation date, but technically it could be what do you want (you can assign the date you want in the frontmatter).

I this case, I agree that `mtime` makes more sense, but this value is not available automatically in the page date. Maybe Lume should have both dates, but I'm not completely sure about that.

As a workaround, you can create a preprocessor to obtain this data:

```js
site.preprocess([".html"], (pages) => {
  for (const page of pages) {
    const info = page.src.entry?.getInfo();
    page.data.lastmod = info?.mtime;
  }
});
```

**Comment by iacore** [comment]
wouldn't what your proposed be the default for a **sitemap**? i assume only search engines use read a sitemap.

**Comment by oscarotero** [comment]
lastmod is not a reliable value. Sometimes in some CI environments it's the present time (the moment where the file is created after cloning the repo, instead of when this file content was modified for the last time). Another option is using Git Last Updated value, but this also doesn't work for CI like GitHub Actions, because the repository is cloned without the history (only the last commit).

**Comment by iacore** [comment]
well that is cursed. you should probably paste this paragraph to https://lume.land/plugins/sitemap/

**Comment by oscarotero** [comment]
Fair enough. I've updated the documentation including that.
