### ISSUE TITLE
Extra spaces after the opening dashes of the frontmatter trigger the TOC plugin to interpret them as h2

### ISSUE THREAD

**Issue by ooker777** [lumeland/lume#644]
I initialize a bare project with `lume init`, then create this simple markdown file. Notice there is a space after the first 3 dashes:
```md
--- 
key: value
---
Body text
```
The result:
```html
<!DOCTYPE html>
<hr>
<h2>key: value</h2>
<p>Body text</p>
```
If there isn't any space, then the result will be:
```html
<!DOCTYPE html>
<p>Body text</p>
```

**Comment by oscarotero** [comment]
This bug is from Deno's `std/front-matter` package that returns the front matter as invalid due this space. I've created an issue: https://github.com/denoland/std/issues/5673

**Comment by oscarotero** [comment]
The bug has been fixed, I can close this.
