### ISSUE TITLE
Weird deno version requirement 

### ISSUE THREAD

**Issue by iacore** [lumeland/lume#658]
Why Lume has Deno version requirement now? It wasn't the case before.

### What steps will reproduce the bug?

```
❯ deno run -A https://lume.land/init.ts

Lume needs Deno v1.46.0 or greater
Your current Deno version is 1.45.5
Run deno upgrade and try again
```

**Comment by oscarotero** [comment]
It always had version requirement but it was far below the latest version.
With Lume 2.3 I had to update to the latest Deno version due this bug https://github.com/denoland/deno/issues/25008 that was fixed recently.

**Comment by iacore** [comment]
Lume going multi-threaded?

**Comment by oscarotero** [comment]
> Lume going multi-threaded?

Not exactly. The build process is run in a worker, so it can be reload after changing the `_config.ts` file. [More info](https://lume.land/blog/posts/lume-2.3.0-andres-do-barro/#restart-after-modifying-the-_config.ts-and-_cms.ts-files).

**Comment by iacore** [comment]
You have solved the reloading problem. Nice!
