### ISSUE TITLE
Using `outExtension` causes esbuild to copy original and processed file.

### ISSUE THREAD

**Issue by kawarbon** [lumeland/lume#668]
### Version

2.3.2

### Platform

Windows 11 24H2 (26100.1742)

### What steps will reproduce the bug?

1. Use `outExtension` to append 'min' suffix to a minified bundled JS file:
```ts
site.use(esbuild({
  options: {
    bundle: true,
    minify: true,
    outExtension: { ".js": ".min.js" },
  },
}));
```

### How often does it reproduce? Is there a required condition?

As long as `outExtension` is being present and used, it will cause this problem.

### What is the expected behavior?

It's supposed to process a `.js` file as usual, and then rename it to `.min.js` during processing.

### What do you see instead?

Instead, the user receives both `.min.js` and the original `.ts` file, when without `outExtension` the user only receives `.js`.

### Additional information

It would've been possible to prevent by being able to edit `outfile` but that causes the user to have an error where esbuild claims the usage of `outfile` and `outdir` cannot be utilised at the same time, despite `outdir` having never been specified by the user.

**Comment by oscarotero** [comment]
Done 13796a7fe66c007aaca6a23084233247a46235fb

It will be available in the next version (2.3.3)
