### ISSUE TITLE
Transform Images plugin: Output images cannot be animated

### ISSUE THREAD

**Issue by akimon658** [lumeland/lume#671]
### Version

2.3.2

### Platform

macOS

### What steps will reproduce the bug?

Convert animated images using the Transform Images plugin.
Note that you need to add `.gif` extension to convert GIFs.
```ts
site.use(transformImages({
  extensions: [".jpg", ".jpeg", ".png", ".webp", ".gif"],
}))
```

### How often does it reproduce? Is there a required condition?

Always

### What is the expected behavior?

Output images should be animated as well.

### What do you see instead?

Generated files are not animated, no matter what format they are.

**Comment by oscarotero** [comment]
Thanks!
I just fixed it and will be available in the next version.
Meanwhile, you can upgrade to the latest development version (`deno task lume upgrade --dev`).
