### ISSUE TITLE
ImageTransform broken after 2.4.1 upgrade?

### ISSUE THREAD

**Issue by RickCogley** [lumeland/lume#688]
### Version

2.4.1

### Platform

macOS, Netlify

### What steps will reproduce the bug?

If you clone this and run lume locally:
https://github.com/eSolia/japanactivationcapital.com/tree/redesign20241031
... you might see that `_site/media` has no generated images at all. 

I had removed `transform-images` tags from images, and removed the `/media/_data.yml` for testing when I was not sure what was causing trouble with a different, now-resolved problem. Then I upgraded to 2.4.0 yesterday (?) and 2.4.1 this AM, and decided to revert those to get the benefit of the transforms. 

### How often does it reproduce? Is there a required condition?

Seems always

### What is the expected behavior?

Transformed images appear in `_site/media`

### What do you see instead?

No transformed images in `_site/media`

**Comment by RickCogley** [comment]
I upgraded a different repo, and noticed this: 

```
❯ cd ../julie_portfolio/
❯ lume upgrade
Task lume export TZ='Asia/Tokyo' && echo "import 'lume/cli.ts'" | deno run -A - "upgrade"
Warning The following packages contained npm lifecycle scripts (preinstall/install/postinstall) that were not executed:
┠─ npm:sharp@0.33.5
┃
┠─ This may cause the packages to not work correctly.
┠─ Lifecycle scripts are only supported when using a `node_modules` directory.
┠─ Enable it in your deno config file:
┖─ "nodeModulesDir": "auto"
Update successful!
Your Lume version is: v2.4.1
```

Is this relevant?

**Comment by oscarotero** [comment]
It's not relevant. This happens in Deno 2.x for npm packages that have lifecycle scripts (that must run `preinstall`, `install` or `postinstall` events). Deno only can run these scripts is the package is instaled in a node_modules directory.
Fortunately, the script of sharp is only to check and validate the installation, so it works without running it.

I'll take a look to your problem.

**Comment by oscarotero** [comment]
The problem is you're statically copying `.jpg`, `.png` and `.avif` files here: https://github.com/eSolia/japanactivationcapital.com/blob/redesign20241031/_config.ts#L128

Copied files are not processed (another case of confusion between copying and loading files, I hope to change the behavior in Lume 3).
After removing these extensions (to keep only `.pdf`), it works fine.

BTW, the `matches` option doesn't exist. https://github.com/eSolia/japanactivationcapital.com/blob/redesign20241031/_config.ts#L56

**Comment by RickCogley** [comment]
Oof, sorry about that and thanks for setting me straight. I bet I assumed something worked as I was changing things, because files got left in _site.

**Comment by RickCogley** [comment]
Just to close the loop, everything is working as expected now. Thanks again!
