### ISSUE TITLE
help: `deno task build` in github workflow failed

### ISSUE THREAD

**Issue by familyboat** [lumeland/lume#696]
### Version

2.4.2

### Platform

debian on wsl

### What steps will reproduce the bug?

You can check my [repository](https://github.com/familyboat/coral_blog). I followed the steps in [`how to deploy to deno deploy`](https://lume.land/docs/advanced/deployment/#deno-deploy). After deployed, I can not access any html file in _site. It seems that no html file is in _site. 

I noticed that `deno task build` in github workflow failed. You can check [this one](https://github.com/familyboat/coral_blog/actions/runs/12097325758). I do not know what those logs mean. Maybe I should contact with `deno deploy team`. But I want to hear from you first.

### How often does it reproduce? Is there a required condition?

I can always reproduce it. Just follow the steps in [`how to deploy to deno deploy`](https://lume.land/docs/advanced/deployment/#deno-deploy).

### What is the expected behavior?

There should have html file in _site and I can access it.

### What do you see instead?

No html file in _site at all.

### Additional information

No.

**Comment by familyboat** [comment]
Sorry, I think I know what happened now.

**Comment by oscarotero** [comment]
The error says: `APIError: The project is not in GitHub Actions mode.`
You have to configure the project in deno deploy to GitHub Actions mode

**Comment by familyboat** [comment]
Thanks, I will close this issue.
