### ISSUE TITLE
question: `precompile` for `compilerOptions.jsx` is supported? 

### ISSUE THREAD

**Issue by familyboat** [lumeland/lume#699]
I have a question about `jsx` or `jsx-preact` engine. I know `react-jsx` for `compilerOptions.jsx` is supported, so how about `precompile`. Is it supported? If does, how can I make it. (I have tried directly changing it to `precompile`.)

Thanks for your time!

**Comment by oscarotero** [comment]
`precompile` is supported by `jsx-preact` (not by `jsx`).

Replacing `react-jsx` to `precompile` is enough:

```jsonc
{
  // ... other options
  "compilerOptions": {
    "jsx": "precompile",
    "jsxImportSource": "npm:preact"
  }
}
```

**Comment by familyboat** [comment]
Thanks!
