### ISSUE TITLE
Is the server port options taken in account from the configuration file?

### ISSUE THREAD

**Issue by e-roux** [lumeland/lume#704]
### Version

2.4.2

### Platform

Darwin

### What steps will reproduce the bug?

After bootstrapping a site with `deno run -A https://lume.land/init.ts` with the configuration:

```ts
import lume from "lume/mod.ts";

const site = lume({
  server: {
    port: 8000,
  },
});

export default site;
```

the site is accessible on port 3000 but not 8000

### How often does it reproduce? Is there a required condition?

always

### What is the expected behavior?

```shell
Task serve deno task lume -s
Task lume echo "import 'lume/cli.ts'" | deno run -A - "-s"
Loading config file file:///private/tmp/lumi/_config.ts
🍾 Site built into ./_site
  0 files generated in 0.00 seconds
  Server started at:
  http://localhost:8000/ (local)
  http://192.168.178.30:8000/ (network)
```

### What do you see instead?

```shell
Task serve deno task lume -s
Task lume echo "import 'lume/cli.ts'" | deno run -A - "-s"
Loading config file file:///private/tmp/lumi/_config.ts
🍾 Site built into ./_site
  0 files generated in 0.00 seconds
  Server started at:
  http://localhost:3000/ (local)
  http://192.168.178.30:3000/ (network)
```

### Additional information

The port is taken in account when passed to the command line

**Comment by oscarotero** [comment]
Sorry, this is a bug. Seems that the default url for server mode (`localhost:3000`) overrides the port. I'll fix it in the next version.
Meanwhile, you can use `--port` flag (`serve deno task lume -s --port=8000`)
