### ISSUE TITLE
Tags don't propagate on layouts

### ISSUE THREAD

**Issue by fserb** [lumeland/lume#89]
I'm not sure if this is a feature request or a bug.

if you have:

_include/mylayout.njk
```
---
tags: mytag
---
```

page.njk
```
---
layout: mylayout.njk
---
```

Then I'd expect that `page.njk` would be part of `mytag`. Other data seems to propagate properly, but tags seem to be ignored. When used like this:

```
---
renderOrder: 1
---
{%- for post in search.pages('mytag') -%}
```

**Comment by fserb** [comment]
we seem to only save `content` from `#renderPage`. I think it would make sense to update `data` too?

**Comment by oscarotero** [comment]
Data in layouts doesn't affect to the pages, it's used only for rendering. You can use `_data.*` files to apply the same tag to all files in a directory.
Why do you want to do this?

**Comment by fserb** [comment]
It's a bit quality of life. It feels it should just work.

My use case is: I have a special type of post, that has a different layout and I want to search all of those. Mostly to avoid having to do:
```
layout: x
tags: x
```
everywhere. In my case, `_data` will probably solve it.

**Comment by oscarotero** [comment]
Note that you can search a page not only by tags but any other value. For example:

```njk
{%- for post in search.pages('layout=mylayout.njk') -%}
```

**Comment by fserb** [comment]
That totally solves it. :)

"The purpose of layouts is rendering pages, not assign data. You have _data.* files and folders for that purpose."

That's fair, I guess.
