### ISSUE TITLE
data.content not available if document contains an async filter

### ISSUE THREAD

**Issue by fserb** [lumeland/lume#92]
As the title says.

If you have an async filter `site.filter('x', async () => {}, true)` and try, for example, to build an RSS feed with the content of the document, the whole `page.data.content` is empty, even if `renderOrder` is used.

**Comment by oscarotero** [comment]
Not sure to understand.
The rendered content of the page is saved in `page.content`. `page.data.content` stores the initial content (before render).

**Comment by fserb** [comment]
ahn, wrong issue. Let me open a proper one.
