### ISSUE TITLE
Error on install: unable to parse import map JSON

### ISSUE THREAD

**Issue by bradeneast** [lumeland/lume#98]
I have deno 1.10.3 installed and working properly with other modules. I'm trying to install Lume, so I run the standard installation command:
```bash
deno run -A https://deno.land/x/lume/install.js
```
After deno finishes downloading the files, I get this error:
```bash
error: Unable to parse import map JSON
```

- I've tried re-installing deno.
- I've installed other packages that use import_map.json with no problems.
- Being new to deno, I'm not sure how to troubleshoot from here.

**Comment by oscarotero** [comment]
The last stable version of Deno is 1.10.3. Are you using an unstable version?

In Deno 1.10.3 it works fine:
<img width="564" alt="imaxe" src="https://user-images.githubusercontent.com/377873/120840095-138ac980-c56a-11eb-9e8a-a71de878ea36.png">

**Comment by bradeneast** [comment]
My mistake. 1.10.4 was a typo.
Yes, I am using Deno 1.10.3 :)

**Comment by bradeneast** [comment]
My mistake. 1.10.4 was a typo.
Yes, I am using Deno 1.10.3 :)

**Comment by oscarotero** [comment]
Can i have more info? operating system, a screenshot or something?

**Comment by bradeneast** [comment]
Totally! Here's a video.
I'm on Windows 10 and just upgrade Deno earlier today. It may not be an issue with Lume at all, but I thought I would check after exhausting my other troubleshooting.

https://user-images.githubusercontent.com/43307367/120843443-b70cb780-c533-11eb-9ed8-9efb97b39b2d.mp4

**Comment by oscarotero** [comment]
Wow, thanks!
I didn't test the installation process on Windows. Let me try

**Comment by valtlai** [comment]
I guess it’s related to `join()` and we should use `posix.join()` instead.

**Comment by oscarotero** [comment]
Yes, thanks @valtlai It was that.
@bradeneast Can you try this?

```
deno run -A https://raw.githubusercontent.com/lumeland/lume/master/install.js
```

**Comment by bradeneast** [comment]
That worked. I'm glad it wasn't a waste of your time.
Thanks very much!

**Comment by oscarotero** [comment]
Thanks for reporting.
I'm going to release a new version now, then you can run "lume upgrade".
